export default function AccountingTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=financial">Financial</a>
            <span className="sep">/</span>
            <span className="current">Accounting Template</span>
          </div>

          <div className="eyebrow">Financial template</div>
          <h1>AI Excel Accounting Template for Small Business <span className="accent">Bookkeeping</span></h1>
          <p className="lede">
            Track daily transactions, expenses, invoices, cash flow, and financial records with an AI-generated Excel bookkeeping template designed for small businesses. Formula Byte helps business owners automate bookkeeping workflows using intelligent spreadsheets with built-in formulas, reporting dashboards, and organized financial tracking systems.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>15</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate accounting spreadsheets for:</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Freelancers</span>
          <span className="use-case-pill"><span className="dot"></span>Ecommerce brands</span>
          <span className="use-case-pill"><span className="dot"></span>Agencies</span>
          <span className="use-case-pill"><span className="dot"></span>Contractors</span>
          <span className="use-case-pill"><span className="dot"></span>Consultants</span>
          <span className="use-case-pill"><span className="dot"></span>Startups</span>
          <span className="use-case-pill"><span className="dot"></span>Service businesses</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Accounting-Ledger<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">F8</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=SUM</span>(<span className="num">F5:F7</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header preview-hide-mobile">F</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Date</div>
            <div className="preview-cell preview-header-cell">Description</div>
            <div className="preview-cell preview-header-cell">Category</div>
            <div className="preview-cell preview-header-cell">Type</div>
            <div className="preview-cell preview-header-cell">Reference</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Amount</div>

            {/* Row 2 - Income section */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell preview-header-cell" style={{gridColumn: 'span 2'}}>INCOME TRANSACTIONS</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-hide-mobile"></div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">2026-01-15</div>
            <div className="preview-cell text">Client payment - Project Alpha</div>
            <div className="preview-cell text">Revenue</div>
            <div className="preview-cell text">Income</div>
            <div className="preview-cell text">INV-001</div>
            <div className="preview-cell principal">$5,000</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">2026-01-18</div>
            <div className="preview-cell text">Consulting services</div>
            <div className="preview-cell text">Services</div>
            <div className="preview-cell text">Income</div>
            <div className="preview-cell text">INV-002</div>
            <div className="preview-cell principal">$2,500</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">2026-01-22</div>
            <div className="preview-cell text">Product sales</div>
            <div className="preview-cell text">Sales</div>
            <div className="preview-cell text">Income</div>
            <div className="preview-cell text">SALE-001</div>
            <div className="preview-cell principal">$1,800</div>

            {/* Row 6 - Total Income */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Total Income</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell selected">$9,300</div>

            {/* Row 7 - Expenses section */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell preview-header-cell" style={{gridColumn: 'span 2'}}>EXPENSE TRANSACTIONS</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-hide-mobile"></div>

            {/* Row 8 */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text">2026-01-12</div>
            <div className="preview-cell text">Office rent</div>
            <div className="preview-cell text">Rent</div>
            <div className="preview-cell text">Expense</div>
            <div className="preview-cell text">EXP-001</div>
            <div className="preview-cell interest">$2,000</div>

            {/* Row 9 */}
            <div className="preview-row-num">9</div>
            <div className="preview-cell text">2026-01-14</div>
            <div className="preview-cell text">Software subscriptions</div>
            <div className="preview-cell text">Software</div>
            <div className="preview-cell text">Expense</div>
            <div className="preview-cell text">EXP-002</div>
            <div className="preview-cell interest">$350</div>

            {/* Row 10 */}
            <div className="preview-row-num">10</div>
            <div className="preview-cell text">2026-01-20</div>
            <div className="preview-cell text">Office supplies</div>
            <div className="preview-cell text">Supplies</div>
            <div className="preview-cell text">Expense</div>
            <div className="preview-cell text">EXP-003</div>
            <div className="preview-cell interest">$180</div>

            {/* Row 11 - Total Expenses */}
            <div className="preview-row-num">11</div>
            <div className="preview-cell text">Total Expenses</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell">$2,530</div>

            {/* Row 12 - Net */}
            <div className="preview-row-num">12</div>
            <div className="preview-cell text">NET INCOME</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell balance">$6,770</div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Total Income:</span>
              <span className="val">$9.3K</span>
            </div>
            <div className="preview-status-item">
              <span>Expenses:</span>
              <span className="val">$2.5K</span>
            </div>
            <div className="preview-status-item">
              <span>Net Income:</span>
              <span className="val serif">$6.8K</span>
            </div>
            <div className="preview-status-item">
              <span>Margin:</span>
              <span className="val">73%</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">Ledger</button>
              <button className="preview-tab">Income</button>
              <button className="preview-tab">Expenses</button>
              <button className="preview-tab">Dashboard</button>
              <button className="preview-tab">+5</button>
            </div>
          </div>
        </div>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What is an Excel Bookkeeping Template?</h2>
              <p className="intro">A structured financial spreadsheet used to record, organize, and monitor business financial transactions and maintain accurate bookkeeping records.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel bookkeeping template</strong> is a comprehensive accounting system that tracks every financial transaction in your business. It records income, expenses, invoices, payments, and cash flow to provide a complete picture of your business financial health.
              </p>
              <p>
                A well-structured bookkeeping template helps small businesses maintain accurate financial records, simplify tax preparation, support loan applications, and make informed business decisions based on real-time financial data.
              </p>
              <ul className="bulleted">
                <li><strong>Daily transaction logs</strong> — sales, expenses, payments, refunds</li>
                <li><strong>Income tracking</strong> — revenue sources, client payments, receivables</li>
                <li><strong>Expense management</strong> — categorization, vendor tracking, cost analysis</li>
                <li><strong>Invoice tracking</strong> — accounts receivable, payment status, aging</li>
                <li><strong>Financial reporting</strong> — profit & loss, cash flow, summaries</li>
              </ul>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>From business description to accounting system in seconds.</h2>
              <p className="intro">Describe your bookkeeping workflow, and Formula Byte generates a complete accounting system with automated formulas and financial dashboards.</p>
            </div>
            <div className="row-body">
              <div className="steps">
                <div className="step">
                  <div className="step-num">1</div>
                  <div>
                    <h3>Describe your business</h3>
                    <p>Business type, transaction categories, income sources, expense types, reporting needs — in plain English or a quick form.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">2</div>
                  <div>
                    <h3>AI builds your accounting system</h3>
                    <p>SUM, IF, and financial formulas are wired to your transactions. Categories organize automatically based on your business workflow.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">3</div>
                  <div>
                    <h3>Financial formulas calculate automatically</h3>
                    <p>Total income, expenses, profit margins, and cash flow update instantly as you record transactions.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">4</div>
                  <div>
                    <h3>Generate financial reports</h3>
                    <p>Income statements, expense analysis, profit summaries, and cash flow dashboards appear on dedicated sheets.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>What every generated <span className="serif-accent">bookkeeping system</span> includes.</h2>
              <p className="intro">Complete accounting workflow — transaction tracking, expense management, invoicing, and financial dashboards in one template.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">📝</div>
                  <h3>Transaction tracking</h3>
                  <p>Record every financial transaction with automatic categorization and organized ledgers.</p>
                  <ul>
                    <li>Daily transaction logs</li>
                    <li>Automatic categorization</li>
                    <li>Date & time stamps</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">💰</div>
                  <h3>Income management</h3>
                  <p>Track revenue sources, client payments, and receivables with automatic rollup.</p>
                  <ul>
                    <li>Multiple income streams</li>
                    <li>Payment tracking</li>
                    <li>Receivables monitoring</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">💸</div>
                  <h3>Expense tracking</h3>
                  <p>Organize business expenses by category with vendor tracking and cost analysis.</p>
                  <ul>
                    <li>Category-based organization</li>
                    <li>Vendor tracking</li>
                    <li>Cost analysis</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">📊</div>
                  <h3>Financial dashboards</h3>
                  <p>Visual reports summarize income, expenses, profit, and cash flow at a glance.</p>
                  <ul>
                    <li>Profit & loss summaries</li>
                    <li>Cash flow monitoring</li>
                    <li>Financial health metrics</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Eight worksheets, <span className="serif-accent">one</span> generation.</h2>
              <p className="intro">A complete bookkeeping workspace — every sheet linked, every formula wired, every dashboard ready on open.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                  <div className="spec-head-cell">Type</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Transaction Ledger</span>
                  <span className="spec-purpose">Main log for all daily financial transactions with automatic categorization.</span>
                  <span className="spec-tag">Core</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Income Tracker</span>
                  <span className="spec-purpose">Monitors revenue sources, client payments, and receivables.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Expense Ledger</span>
                  <span className="spec-purpose">Tracks all business expenses with category-based organization.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Invoice Register</span>
                  <span className="spec-purpose">Manages customer invoices, payment status, and accounts receivable.</span>
                  <span className="spec-tag">Operations</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Accounts Payable</span>
                  <span className="spec-purpose">Organizes vendor payments, due dates, and outstanding obligations.</span>
                  <span className="spec-tag">Operations</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Cash Flow Dashboard</span>
                  <span className="spec-purpose">Visualizes cash movement, balances, and flow trends.</span>
                  <span className="spec-tag">Dashboard</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Profit & Loss Report</span>
                  <span className="spec-purpose">Calculates revenue, expenses, and net profit automatically.</span>
                  <span className="spec-tag">Report</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Financial Summary</span>
                  <span className="spec-purpose">Generates complete financial statements and business insights.</span>
                  <span className="spec-tag">Report</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Under the hood</div>
              <h2>The formulas that <span className="serif-accent">power</span> your bookkeeping.</h2>
              <p className="intro">Every Formula Byte accounting template is wired up with essential financial functions — generated, linked, and tested automatically.</p>
            </div>
            <div className="row-body">
              <div className="formula-grid">
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=SUM</span>(<span className="arg">range</span>)</div>
                  <div className="formula-desc">Calculates <em>total income</em>, <em>total expenses</em>, and category subtotals instantly.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=IF</span>(<span className="arg">condition, true, false</span>)</div>
                  <div className="formula-desc">Enables <em>conditional categorization</em> and automated transaction classification.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=XLOOKUP</span>(<span className="arg">value, range, return</span>)</div>
                  <div className="formula-desc">Retrieves <em>transaction details</em> and references across worksheets.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=Income</span> - <span className="fn">=Expenses</span></div>
                  <div className="formula-desc">Calculates <em>net profit</em> and operating margins automatically.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=SUMIFS</span>(<span className="arg">sum, range, criteria</span>)</div>
                  <div className="formula-desc">Sums transactions <em>by category</em>, date range, or multiple conditions.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=Pivot Tables</span></div>
                  <div className="formula-desc">Creates <em>dynamic reports</em> for expense analysis and income breakdowns.</div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Four business types, <span className="serif-accent">one</span> bookkeeping engine.</h2>
              <p className="intro">Customize the accounting system for any business structure — same engine, different workflows.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">R</div>
                    <div>
                      <h4>Retail business bookkeeping</h4>
                      <div className="industry-tagline">SHOPS · STORES · LOCAL</div>
                    </div>
                  </div>
                  <p>Track sales revenue, inventory costs, supplier payments, and operational expenses. Ideal for retail stores managing daily transactions and profit margins.</p>
                  <ul>
                    <li>Product sales tracking</li>
                    <li>Inventory cost management</li>
                    <li>Supplier payment tracking</li>
                    <li>Daily profit monitoring</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">F</div>
                    <div>
                      <h4>Freelancer accounting</h4>
                      <div className="industry-tagline">CONSULTANTS · CREATIVE</div>
                    </div>
                  </div>
                  <p>Manage client invoices, project payments, business expenses, and tax planning for independent professionals and consultants.</p>
                  <ul>
                    <li>Client invoice tracking</li>
                    <li>Project revenue management</li>
                    <li>Business expense categorization</li>
                    <li>Tax planning summaries</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">E</div>
                    <div>
                      <h4>Ecommerce bookkeeping</h4>
                      <div className="industry-tagline">SHOPIFY · AMAZON · ETSY</div>
                    </div>
                  </div>
                  <p>Track marketplace sales, platform fees, advertising expenses, inventory purchases, and multi-channel financial reporting.</p>
                  <ul>
                    <li>Platform sales tracking</li>
                    <li>Fee & expense management</li>
                    <li>Inventory cost tracking</li>
                    <li>Multi-channel reporting</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">🚀</div>
                    <div>
                      <h4>Startup bookkeeping</h4>
                      <div className="industry-tagline">FUNDED · GROWTH · PRE-IPO</div>
                    </div>
                  </div>
                  <p>Monitor burn rate, runway, operational expenses, funding allocation, and financial metrics for investor reporting and cash management.</p>
                  <ul>
                    <li>Burn rate tracking</li>
                    <li>Runway calculation</li>
                    <li>Operational expense monitoring</li>
                    <li>Investor financial reporting</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Manual bookkeeping vs. <span className="serif-accent">Formula Byte.</span></h2>
              <p className="intro">Most accounting templates are static files with limited customization. Formula Byte generates AI-powered bookkeeping systems tailored to your business.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual bookkeeping</div>
                  <h3>Spreadsheets built by hand</h3>
                  <ul>
                    <li>Manual transaction entry</li>
                    <li>Error-prone calculations</li>
                    <li>Time-consuming categorization</li>
                    <li>Limited financial visibility</li>
                    <li>Basic reporting, no dashboards</li>
                    <li>Difficult to customize for business needs</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>Generated, automated, accurate</h3>
                  <ul>
                    <li>Automated transaction organization</li>
                    <li>Instant profit calculations</li>
                    <li>Financial formulas wired automatically</li>
                    <li>Clear financial dashboards</li>
                    <li>Profit & loss reporting included</li>
                    <li>Fully customizable for your business</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-generated <span className="serif-accent">bookkeeping</span> templates.</h2>
              <p className="intro">Faster setup, fewer errors, better financial insights — every calculation you need already built in.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster bookkeeping setup</h3>
                  <p>Generate complete accounting systems instantly instead of spending hours on manual spreadsheet creation.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">90%</span>
                    <span className="benefit-stat-label">Less setup time</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Better financial organization</h3>
                  <p>Structured transaction categories improve accounting visibility and make financial reporting clearer.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Organized</span>
                    <span className="benefit-stat-label">Transaction history</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Reduce bookkeeping errors</h3>
                  <p>Automated SUM, IF, and profit formulas eliminate calculation mistakes and ensure accounting accuracy.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">100%</span>
                    <span className="benefit-stat-label">Formula accuracy</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Improved business insights</h3>
                  <p>Financial dashboards and profit analysis help you understand revenue, expenses, and cash flow trends.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Real-time</span>
                    <span className="benefit-stat-label">Financial insights</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Easier tax preparation</h3>
                  <p>Organized transaction records and profit summaries simplify tax filing and financial reporting.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Tax-ready</span>
                    <span className="benefit-stat-label">Financial records</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Support loan applications</h3>
                  <p>Professional financial statements and profit reports improve loan approval chances.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Bank-ready</span>
                <span className="benefit-stat-label">Financial reports</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This <span className="serif-accent">Bookkeeping</span> Spreadsheet?</h2>
              <p className="intro">This accounting solution is ideal for businesses and professionals managing financial records.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>Freelancers</h4></div>
                <div className="audience-cell"><h4>Ecommerce sellers</h4></div>
                <div className="audience-cell"><h4>Startups</h4></div>
                <div className="audience-cell"><h4>Agencies</h4></div>
                <div className="audience-cell"><h4>Consultants</h4></div>
                <div className="audience-cell"><h4>Contractors</h4></div>
                <div className="audience-cell"><h4>Accountants</h4></div>
                <div className="audience-cell"><h4>Finance managers</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple transaction tracking or advanced bookkeeping management, Formula Byte helps automate accounting spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating bookkeeping templates with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet track income and expenses automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates accounting spreadsheets with automated calculations for income, expenses, and profit reporting.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include financial dashboards?</summary>
                  <div className="faq-a">Yes. The spreadsheet can include profit & loss dashboards, cash flow visualizations, and financial reporting.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize the bookkeeping categories?</summary>
                  <div className="faq-a">Absolutely. Income categories, expense types, transaction classifications, and reporting formats can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte bookkeeping templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for small business bookkeeping?</summary>
                  <div className="faq-a">Yes. Small businesses commonly use bookkeeping spreadsheets to monitor financial health, track transactions, and simplify tax preparation.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other financial templates you might need.</h2>
              <p className="intro">Same engine, different financial workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/balance-sheet-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Balance Sheet</h4>
                  <p>Track assets, liabilities, and equity with automated calculations.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/income-statement-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Income Statement</h4>
                  <p>Revenue, expenses, and net income — calculated automatically.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/cash-flow-template/" className="related-card">
                  <div className="glyph">C</div>
                  <h4>Cash Flow Statement</h4>
                  <p>Monitor cash movement and liquidity with automated tracking.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/invoice-template/" className="related-card">
                  <div className="glyph">V</div>
                  <h4>Invoice Template</h4>
                  <p>Professional invoices with auto-numbering, taxes, and totals.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">Bookkeeping</span> Spreadsheet?</h2>
            <p>Stop building accounting spreadsheets manually.</p>
            <p>Describe your bookkeeping workflow, and Formula Byte will generate a professional AI-powered Excel accounting template with automated formulas, transaction ledgers, financial dashboards, and organized reporting structures in seconds.</p>
            <p>Create smarter bookkeeping systems with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
