export default function AmortizationScheduleTemplatePage() {
  return (
    <>
 
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=financial">Financial</a>
            <span className="sep">/</span>
            <span className="current">Amortization Schedule</span>
          </div>

          <div className="eyebrow">Financial template</div>
          <h1>AI Amortization<br /><span className="accent">Schedule</span> Template</h1>
          <p className="lede">
            Track loan payments, interest, and principal balances with an AI-generated Excel amortization schedule — built with PMT formulas, payoff timelines, and repayment dashboards in seconds.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>12</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>15 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/?template=amortization-schedule" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-suggest">
            <span>Try:</span>
            <button className="chip">Mortgage with extra payments</button>
            <button className="chip">Business loan repayment</button>
            <button className="chip">Student loan payoff tracker</button>
            <button className="chip">Auto loan dashboard</button>
          </div>
        </div>
      </section>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Amortization-Schedule<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">D4</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=PMT</span>(<span className="num">0.065</span>/12, <span className="num">360</span>, -<span className="num">250000</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header preview-hide-mobile">F</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Month</div>
            <div className="preview-cell preview-header-cell">Date</div>
            <div className="preview-cell preview-header-cell">Payment</div>
            <div className="preview-cell preview-header-cell">Principal</div>
            <div className="preview-cell preview-header-cell">Interest</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Balance</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">1</div>
            <div className="preview-cell text">Jan 2026</div>
            <div className="preview-cell">$1,580.17</div>
            <div className="preview-cell principal">$226.84</div>
            <div className="preview-cell interest">$1,353.33</div>
            <div className="preview-cell balance preview-hide-mobile">$249,773.16</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">2</div>
            <div className="preview-cell text">Feb 2026</div>
            <div className="preview-cell">$1,580.17</div>
            <div className="preview-cell principal">$228.07</div>
            <div className="preview-cell interest">$1,352.10</div>
            <div className="preview-cell balance preview-hide-mobile">$249,545.09</div>

            {/* Row 4 — selected */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">3</div>
            <div className="preview-cell text">Mar 2026</div>
            <div className="preview-cell selected">$1,580.17</div>
            <div className="preview-cell principal">$229.31</div>
            <div className="preview-cell interest">$1,350.86</div>
            <div className="preview-cell balance preview-hide-mobile">$249,315.78</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">6</div>
            <div className="preview-cell text">Apr 2026</div>
            <div className="preview-cell">$1,580.17</div>
            <div className="preview-cell principal">$230.55</div>
            <div className="preview-cell interest">$1,349.62</div>
            <div className="preview-cell balance preview-hide-mobile">$249,085.23</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">7</div>
            <div className="preview-cell text">May 2026</div>
            <div className="preview-cell">$1,580.17</div>
            <div className="preview-cell principal">$231.80</div>
            <div className="preview-cell interest">$1,348.37</div>
            <div className="preview-cell balance preview-hide-mobile">$248,853.43</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">8</div>
            <div className="preview-cell text">Jun 2026</div>
            <div className="preview-cell">$1,580.17</div>
            <div className="preview-cell principal">$233.06</div>
            <div className="preview-cell interest">$1,347.11</div>
            <div className="preview-cell balance preview-hide-mobile">$248,620.37</div>

            {/* Row 8 — sparkline */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell faded">…</div>
            <div className="preview-cell sparkline" style={{gridColumn: 'span 2'}}>
              <svg width="140" height="22" viewBox="0 0 140 22" preserveAspectRatio="none">
                <defs>
                  <linearGradient id="spark-grad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="#8171D0" stopOpacity="0.35"/>
                    <stop offset="100%" stopColor="#8171D0" stopOpacity="0"/>
                  </linearGradient>
                </defs>
                <path d="M0,3 L14,4 L28,5 L42,7 L56,9 L70,11 L84,13 L98,15 L112,17 L126,19 L140,21 L140,22 L0,22 Z" fill="url(#spark-grad)"/>
                <path d="M0,3 L14,4 L28,5 L42,7 L56,9 L70,11 L84,13 L98,15 L112,17 L126,19 L140,21" fill="none" stroke="#8171D0" strokeWidth="1.5"/>
              </svg>
            </div>
            <div className="preview-cell faded preview-hide-mobile">↓ falling</div>

            {/* Row 9 - last row */}
            <div className="preview-row-num">360</div>
            <div className="preview-cell text">360</div>
            <div className="preview-cell text">Dec 2055</div>
            <div className="preview-cell">$1,580.17</div>
            <div className="preview-cell principal">$1,571.65</div>
            <div className="preview-cell interest">$8.52</div>
            <div className="preview-cell balance preview-hide-mobile">$0.00</div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Loan:</span>
              <span className="val">$250,000</span>
            </div>
            <div className="preview-status-item">
              <span>Rate:</span>
              <span className="val">6.50%</span>
            </div>
            <div className="preview-status-item">
              <span>Term:</span>
              <span className="val">30 yr</span>
            </div>
            <div className="preview-status-item">
              <span>Total interest:</span>
              <span className="val serif">$318,861</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">Summary</button>
              <button className="preview-tab">Schedule</button>
              <button className="preview-tab">Dashboard</button>
              <button className="preview-tab">+5</button>
            </div>
          </div>
        </div>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What is an amortization schedule?</h2>
              <p className="intro">A structured spreadsheet that breaks down every loan payment into principal, interest, and remaining balance over the full repayment term.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel amortization schedule</strong> is a month-by-month breakdown of how a loan is repaid. Each row shows how much of that month's payment goes to <strong>interest</strong>, how much to <strong>principal</strong>, and what the <strong>remaining balance</strong> looks like afterward.
              </p>
              <p>
                Early in a loan, most of every payment is interest. As the balance shrinks, more goes to principal. An amortization schedule makes this shift visible — so you can plan budgets, evaluate refinancing, and see exactly when you'll be debt-free.
              </p>
              <ul className="bulleted">
                <li><strong>Loan amount, interest rate, and term</strong> set the foundation</li>
                <li><strong>Monthly payment</strong> calculated automatically with PMT</li>
                <li><strong>Principal &amp; interest split</strong> shown for every period</li>
                <li><strong>Remaining balance</strong> updated row by row</li>
                <li><strong>Payoff summary</strong> with total interest and final date</li>
              </ul>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>From loan terms to full schedule in seconds.</h2>
              <p className="intro">Describe your financing, and Formula Byte generates the complete spreadsheet — formulas, dashboards, and payoff projections included.</p>
            </div>
            <div className="row-body">
              <div className="steps">
                <div className="step">
                  <div className="step-num">1</div>
                  <div>
                    <h3>Describe your loan</h3>
                    <p>Loan amount, interest rate, term, start date, payment frequency — in plain English or a quick form.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">2</div>
                  <div>
                    <h3>AI builds the schedule</h3>
                    <p>PMT, IPMT, and PPMT formulas are wired to your inputs. Every row recalculates automatically as you change terms.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">3</div>
                  <div>
                    <h3>Dashboards generate themselves</h3>
                    <p>Principal vs. interest charts, payoff timelines, and balance trends appear on a dedicated dashboard sheet.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">4</div>
                  <div>
                    <h3>Model extra payments</h3>
                    <p>Add one-time or recurring extra payments and see exactly how much interest you'd save and how much earlier you'd be debt-free.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>What every generated <span className="serif-accent">amortization</span> schedule ships with.</h2>
              <p className="intro">Four pillars of loan tracking — automatic, accurate, and built to support real financial decisions.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">$</div>
                  <h3>Monthly payment tracking</h3>
                  <p>Every payment row records installments, dates, and balance impact — the full life of the loan in one view.</p>
                  <ul>
                    <li>Monthly installments &amp; dates</li>
                    <li>Principal &amp; interest split</li>
                    <li>Running balance per period</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">π</div>
                  <h3>Principal &amp; interest breakdown</h3>
                  <p>See where every dollar goes. The early-loan interest burden and the principal acceleration over time are both visible.</p>
                  <ul>
                    <li>Interest paid per period</li>
                    <li>Cumulative interest tracked</li>
                    <li>Principal reduction visualized</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">▢</div>
                  <h3>Remaining balance monitoring</h3>
                  <p>Outstanding balance, percentage paid off, and payoff projections — refreshed on every input change.</p>
                  <ul>
                    <li>Live balance per row</li>
                    <li>Percent-paid tracker</li>
                    <li>Projected payoff date</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">+</div>
                  <h3>Extra payment analysis</h3>
                  <p>Model one-time or recurring extra payments. The template shows interest savings and shortened terms in real time.</p>
                  <ul>
                    <li>Early-payoff scenarios</li>
                    <li>Total interest saved</li>
                    <li>Months shaved off term</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Eight worksheets, <span className="serif-accent">one</span> generation.</h2>
              <p className="intro">A complete amortization workspace — every sheet linked, every formula wired, every dashboard ready on open.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                  <div className="spec-head-cell">Type</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Loan Summary</span>
                  <span className="spec-purpose">Stores loan details, terms, and computed monthly payment.</span>
                  <span className="spec-tag">Inputs</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Payment Schedule</span>
                  <span className="spec-purpose">Tracks monthly repayments, dates, principal, interest, and balance.</span>
                  <span className="spec-tag">Core</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Principal Breakdown</span>
                  <span className="spec-purpose">Monitors how the principal reduces over each payment period.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Interest Analysis</span>
                  <span className="spec-purpose">Tracks interest paid per period and cumulative interest total.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Remaining Balance</span>
                  <span className="spec-purpose">Displays outstanding balances, percent paid, and projected payoff.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Extra Payment Calculator</span>
                  <span className="spec-purpose">Models early-payoff scenarios, interest savings, and term reduction.</span>
                  <span className="spec-tag">Scenario</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Financial Forecast</span>
                  <span className="spec-purpose">Visualizes repayment progress with charts and trend dashboards.</span>
                  <span className="spec-tag">Dashboard</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Loan Comparison</span>
                  <span className="spec-purpose">Side-by-side comparison of multiple loan terms, rates, and payments.</span>
                  <span className="spec-tag">Compare</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Under the hood</div>
              <h2>The formulas that <span className="serif-accent">do</span> the work.</h2>
              <p className="intro">Every Formula Byte amortization template is wired up with industry-standard financial functions — generated, linked, and tested automatically.</p>
            </div>
            <div className="row-body">
              <div className="formula-grid">
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=PMT</span>(<span className="arg">rate, nper, pv</span>)</div>
                  <div className="formula-desc">Calculates the <em>monthly payment</em> for a loan based on rate, number of periods, and present value.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=IPMT</span>(<span className="arg">rate, per, nper, pv</span>)</div>
                  <div className="formula-desc">Returns the <em>interest portion</em> of a payment for a specific period.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=PPMT</span>(<span className="arg">rate, per, nper, pv</span>)</div>
                  <div className="formula-desc">Returns the <em>principal portion</em> of a payment for a specific period.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=CUMIPMT</span>(<span className="arg">rate, nper, pv, start, end</span>)</div>
                  <div className="formula-desc">Computes the <em>cumulative interest</em> paid between two periods.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=CUMPRINC</span>(<span className="arg">rate, nper, pv, start, end</span>)</div>
                  <div className="formula-desc">Computes the <em>cumulative principal</em> paid between two periods.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=NPER</span>(<span className="arg">rate, pmt, pv</span>)</div>
                  <div className="formula-desc">Calculates the <em>number of periods</em> needed to pay off the loan.</div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Four loan types, <span className="serif-accent">one</span> template engine.</h2>
              <p className="intro">Customize the schedule for any kind of financing — same engine, different defaults.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">M</div>
                    <div>
                      <h4>Mortgage amortization</h4>
                      <div className="industry-tagline">15–30 YR · FIXED OR ARM</div>
                    </div>
                  </div>
                  <p>Track monthly mortgage payments, interest costs, and principal reduction. Ideal for homeowners modeling refinance or early payoff.</p>
                  <ul>
                    <li>Monthly mortgage payments</li>
                    <li>Interest costs &amp; PMI lines</li>
                    <li>Remaining balance &amp; equity</li>
                    <li>Early-payoff opportunities</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">B</div>
                    <div>
                      <h4>Business loan repayment</h4>
                      <div className="industry-tagline">SBA · COMMERCIAL · LINE</div>
                    </div>
                  </div>
                  <p>Manage commercial loan payments and repayment schedules. Built for startups and growing businesses tracking debt.</p>
                  <ul>
                    <li>Commercial loan payments</li>
                    <li>Financing cost analysis</li>
                    <li>Repayment schedules</li>
                    <li>Debt planning forecasts</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">S</div>
                    <div>
                      <h4>Student loan tracker</h4>
                      <div className="industry-tagline">FEDERAL · PRIVATE · REFI</div>
                    </div>
                  </div>
                  <p>Monitor monthly payments, interest accrual, and loan balances across federal and private student debt.</p>
                  <ul>
                    <li>Monthly payments per loan</li>
                    <li>Interest accumulation</li>
                    <li>Extra-payment strategies</li>
                    <li>Debt reduction timelines</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">A</div>
                    <div>
                      <h4>Auto loan schedule</h4>
                      <div className="industry-tagline">36–84 MO · NEW OR USED</div>
                    </div>
                  </div>
                  <p>Track vehicle financing payments, remaining balances, and total cost of borrowing across the loan term.</p>
                  <ul>
                    <li>Vehicle financing payments</li>
                    <li>Remaining loan balances</li>
                    <li>Interest costs &amp; total paid</li>
                    <li>Repayment timeline view</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Manual tracking vs. <span className="serif-accent">Formula Byte.</span></h2>
              <p className="intro">Most amortization spreadsheets are static files you fight to customize. Formula Byte generates one tailored to your loan in seconds.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual loan tracking</div>
                  <h3>Spreadsheets built by hand</h3>
                  <ul>
                    <li>Manual payment entry every month</li>
                    <li>Time-consuming interest calculations</li>
                    <li>Error-prone formulas you rewrite</li>
                    <li>Limited forecasting capability</li>
                    <li>Extra-payment scenarios are painful</li>
                    <li>Basic tracking, no dashboards</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>Generated, automated, accurate</h3>
                  <ul>
                    <li>Automated payment calculation</li>
                    <li>Instant interest calculations</li>
                    <li>Repayment accuracy guaranteed</li>
                    <li>Loan forecasting included</li>
                    <li>Extra-payment analysis built in</li>
                    <li>Dashboards on every generation</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-generated <span className="serif-accent">amortization</span> schedules.</h2>
              <p className="intro">Faster setup, fewer errors, sharper financial decisions — every number you'd want already calculated.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster loan planning</h3>
                  <p>Generate a complete amortization schedule in seconds instead of spending hours building and testing formulas manually.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">90%</span>
                    <span className="benefit-stat-label">Less setup time</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Avoid calculation errors</h3>
                  <p>PMT, IPMT, and PPMT formulas are wired automatically — no more typos, broken references, or math mistakes.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">100%</span>
                    <span className="benefit-stat-label">Formula accuracy</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Model what-if scenarios</h3>
                  <p>Test extra payments, refinance terms, or different interest rates and see exactly how they affect your payoff timeline.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Unlimited</span>
                    <span className="benefit-stat-label">Scenario testing</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Visualize progress</h3>
                  <p>Charts and dashboards show principal vs. interest trends, remaining balance, and payoff progress at a glance.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Built-in</span>
                    <span className="benefit-stat-label">Visual dashboards</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Track total interest cost</h3>
                  <p>Cumulative interest calculations show exactly how much your loan costs — and how to reduce that number with extra payments.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Real-time</span>
                    <span className="benefit-stat-label">Interest tracking</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Export and share</h3>
                  <p>Download your completed schedule as an Excel file or open directly in Google Sheets — works everywhere your team works.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">2</span>
                    <span className="benefit-stat-label">Platform options</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently asked questions.</h2>
              <p className="intro">Everything you need to know about amortization schedules and Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">What is an amortization schedule?</summary>
                  <div className="faq-a">
                    An amortization schedule is a complete table showing each periodic payment on a loan over time. It breaks down how much of each payment goes toward principal vs. interest, and shows the remaining balance after every payment. Formula Byte generates these schedules automatically with built-in formulas.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">How do I calculate monthly payments in Excel?</summary>
                  <div className="faq-a">
                    Formula Byte uses the Excel PMT function: =PMT(rate, nper, pv). Rate is your interest rate per period, nper is the total number of payments, and pv is the loan amount (entered as negative). The AI generates these formulas automatically — no manual Excel work needed.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I include extra payments in the schedule?</summary>
                  <div className="faq-a">
                    Yes. The generated template includes an Extra Payment Calculator worksheet where you can model additional principal payments. The schedule automatically recalculates to show how extra payments reduce interest and shorten your loan term.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this work for different loan types?</summary>
                  <div className="faq-a">
                    Absolutely. Describe any loan — mortgage, auto loan, student loan, business loan, personal loan — and Formula Byte generates an appropriate amortization schedule with correct formulas and structure for that loan type.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize the payment frequency?</summary>
                  <div className="faq-a">
                    Yes. Specify monthly, biweekly, or weekly payments when generating your template. The AI adjusts all formulas, schedules, and calculations automatically based on your chosen payment frequency.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Do the templates work in Google Sheets?</summary>
                  <div className="faq-a">
                    Yes. All Formula Byte templates work in both Excel and Google Sheets. Generate once, export to your preferred platform, and all formulas and formatting remain intact.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">How accurate are the calculations?</summary>
                  <div className="faq-a">
                    Formula Byte uses standard financial formulas like PMT, IPMT, PPMT, and cumulative interest calculations. These are the same formulas used by banks and financial institutions, ensuring accuracy to the penny.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this template free to use?</summary>
                  <div className="faq-a">
                    Yes. The amortization schedule template is completely free to generate and use. Describe your loan details, generate the schedule, and download it — no credit card or subscription required.
                  </div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Stop calculating manually. <span className="accent">Start tracking smart.</span></h2>
            <p>Generate your AI-powered amortization schedule in seconds — perfect formulas, complete tracking, and payoff insights included.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/?template=amortization-schedule" className="btn btn-primary btn-lg">Generate amortization schedule →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse more templates</a>
            </div>
          </div>
        </section>
      </div>
 

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}