export default function BalanceSheetTemplatePage() {
  return (
    <>
      <link rel="stylesheet" href="/page-styles/amortization-schedule-template.css" />

      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=financial">Financial</a>
            <span className="sep">/</span>
            <span className="current">Balance Sheet</span>
          </div>

          <div className="eyebrow">Financial template</div>
          <h1>AI Excel <span className="accent">Balance Sheet</span> Template</h1>
          <p className="lede">
            Track assets, liabilities, equity, and business financial health with an AI-generated Excel balance sheet template designed for small business reporting and financial analysis.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>15</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="/auth?template=balance-sheet" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-suggest">
            <span>Try:</span>
            <button className="chip">Small business balance sheet</button>
            <button className="chip">Startup financial statement</button>
            <button className="chip">Ecommerce financial report</button>
            <button className="chip">Freelancer accounting template</button>
          </div>
        </div>
      </section>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Balance-Sheet<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">D12</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=SUM</span>(<span className="num">D5:D11</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header preview-hide-mobile">F</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Account</div>
            <div className="preview-cell preview-header-cell">Category</div>
            <div className="preview-cell preview-header-cell">Type</div>
            <div className="preview-cell preview-header-cell">Amount</div>
            <div className="preview-cell preview-header-cell">Notes</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Reference</div>

            {/* Row 2 - Current Assets */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell preview-header-cell" style={{gridColumn: 'span 2'}}>CURRENT ASSETS</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-hide-mobile"></div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">Cash</div>
            <div className="preview-cell text">Asset</div>
            <div className="preview-cell text">Current</div>
            <div className="preview-cell">$125,000</div>
            <div className="preview-cell text">Bank accounts</div>
            <div className="preview-cell text preview-hide-mobile">D5</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">Accounts Receivable</div>
            <div className="preview-cell text">Asset</div>
            <div className="preview-cell text">Current</div>
            <div className="preview-cell">$85,000</div>
            <div className="preview-cell text">Outstanding invoices</div>
            <div className="preview-cell text preview-hide-mobile">D6</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">Inventory</div>
            <div className="preview-cell text">Asset</div>
            <div className="preview-cell text">Current</div>
            <div className="preview-cell">$67,000</div>
            <div className="preview-cell text">Products stock</div>
            <div className="preview-cell text preview-hide-mobile">D7</div>

            {/* Row 6 - Total Current Assets */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Total Current Assets</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell selected">$277,000</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text preview-hide-mobile"></div>

            {/* Row 7 - Non-current Assets */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell preview-header-cell" style={{gridColumn: 'span 2'}}>NON-CURRENT ASSETS</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-hide-mobile"></div>

            {/* Row 8 */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text">Equipment</div>
            <div className="preview-cell text">Asset</div>
            <div className="preview-cell text">Fixed</div>
            <div className="preview-cell">$145,000</div>
            <div className="preview-cell text">Machinery & tools</div>
            <div className="preview-cell text preview-hide-mobile">D12</div>

            {/* Row 9 */}
            <div className="preview-row-num">9</div>
            <div className="preview-cell text">Property</div>
            <div className="preview-cell text">Asset</div>
            <div className="preview-cell text">Fixed</div>
            <div className="preview-cell">$320,000</div>
            <div className="preview-cell text">Building & land</div>
            <div className="preview-cell text preview-hide-mobile">D13</div>

            {/* Row 10 - Total Assets */}
            <div className="preview-row-num">10</div>
            <div className="preview-cell text">TOTAL ASSETS</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell balance">$742,000</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text preview-hide-mobile"></div>

            {/* Row 11 - Liabilities header */}
            <div className="preview-row-num">11</div>
            <div className="preview-cell preview-header-cell" style={{gridColumn: 'span 2'}}>LIABILITIES</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-hide-mobile"></div>

            {/* Row 12 - Current Liabilities */}
            <div className="preview-row-num">12</div>
            <div className="preview-cell preview-header-cell" style={{gridColumn: 'span 2'}}>Current Liabilities</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-hide-mobile"></div>

            {/* Row 13 */}
            <div className="preview-row-num">13</div>
            <div className="preview-cell text">Accounts Payable</div>
            <div className="preview-cell text">Liability</div>
            <div className="preview-cell text">Current</div>
            <div className="preview-cell interest">$45,000</div>
            <div className="preview-cell text">Vendor payments</div>
            <div className="preview-cell text preview-hide-mobile">D20</div>

            {/* Row 14 */}
            <div className="preview-row-num">14</div>
            <div className="preview-cell text">Short-term Debt</div>
            <div className="preview-cell text">Liability</div>
            <div className="preview-cell text">Current</div>
            <div className="preview-cell interest">$28,000</div>
            <div className="preview-cell text">Due within 12 months</div>
            <div className="preview-cell text preview-hide-mobile">D21</div>

            {/* Row 15 */}
            <div className="preview-row-num">15</div>
            <div className="preview-cell text">Total Liabilities</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell">$218,000</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text preview-hide-mobile"></div>

            {/* Row 16 - Equity */}
            <div className="preview-row-num">16</div>
            <div className="preview-cell preview-header-cell" style={{gridColumn: 'span 2'}}>EQUITY</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-hide-mobile"></div>

            {/* Row 17 */}
            <div className="preview-row-num">17</div>
            <div className="preview-cell text">Owner's Equity</div>
            <div className="preview-cell text">Equity</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell principal">$524,000</div>
            <div className="preview-cell text">Net business value</div>
            <div className="preview-cell text preview-hide-mobile">D28</div>

            {/* Row 18 - Verification */}
            <div className="preview-row-num">18</div>
            <div className="preview-cell text">TOTAL LIABILITIES & EQUITY</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text"></div>
            <div className="preview-cell balance">$742,000</div>
            <div className="preview-cell text" style={{color: 'var(--success)'}}>✓ Balanced</div>
            <div className="preview-cell text preview-hide-mobile"></div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Total Assets:</span>
              <span className="val">$742K</span>
            </div>
            <div className="preview-status-item">
              <span>Liabilities:</span>
              <span className="val">$218K</span>
            </div>
            <div className="preview-status-item">
              <span>Equity:</span>
              <span className="val serif">$524K</span>
            </div>
            <div className="preview-status-item">
              <span>Ratio:</span>
              <span className="val">3.4×</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">Balance Sheet</button>
              <button className="preview-tab">Assets</button>
              <button className="preview-tab">Dashboard</button>
              <button className="preview-tab">+5</button>
            </div>
          </div>
        </div>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What is an Excel Balance Sheet Template?</h2>
              <p className="intro">A structured financial spreadsheet used to organize and analyze a company's assets, liabilities, and equity at a specific point in time.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel balance sheet template</strong> is a financial statement that provides a snapshot of your business's financial health. It shows what your business <strong>owns</strong> (assets), what it <strong>owes</strong> (liabilities), and the <strong>owner's equity</strong> — all organized in one place.
              </p>
              <p>
                The balance sheet follows the fundamental accounting equation: <strong>Assets = Liabilities + Equity</strong>. This means everything your business owns is either funded by debt or owner investment. A well-structured balance sheet helps you understand financial position, support loan applications, and make informed business decisions.
              </p>
              <ul className="bulleted">
                <li><strong>Current assets</strong> — cash, inventory, accounts receivable</li>
                <li><strong>Non-current assets</strong> — equipment, property, long-term investments</li>
                <li><strong>Current liabilities</strong> — accounts payable, short-term debt, taxes</li>
                <li><strong>Long-term liabilities</strong> — loans, leases, deferred revenue</li>
                <li><strong>Owner's equity</strong> — retained earnings, shareholder equity, net worth</li>
              </ul>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>From business description to financial statement in seconds.</h2>
              <p className="intro">Describe your business structure, and Formula Byte generates a complete balance sheet with automated formulas and financial dashboards.</p>
            </div>
            <div className="row-body">
              <div className="steps">
                <div className="step">
                  <div className="step-num">1</div>
                  <div>
                    <h3>Describe your business</h3>
                    <p>Business type, asset categories, liability structure, reporting period — in plain English or a quick form.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">2</div>
                  <div>
                    <h3>AI builds your balance sheet</h3>
                    <p>SUM, IF, and financial formulas are wired to your accounts. Categories organize automatically based on your business structure.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">3</div>
                  <div>
                    <h3>Financial formulas calculate automatically</h3>
                    <p>Total assets, liabilities, equity, and key financial ratios update instantly as you enter or adjust account balances.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">4</div>
                  <div>
                    <h3>Generate financial reports</h3>
                    <p>Asset summaries, liability analysis, equity breakdowns, and financial health dashboards appear on dedicated sheets.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>What every generated <span className="serif-accent">balance sheet</span> includes.</h2>
              <p className="intro">Complete financial tracking system — assets, liabilities, equity, and reporting dashboards in one template.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">$</div>
                  <h3>Asset tracking</h3>
                  <p>Monitor everything your business owns with organized categories for current and non-current assets.</p>
                  <ul>
                    <li>Cash & bank accounts</li>
                    <li>Inventory & equipment</li>
                    <li>Property & investments</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">L</div>
                  <h3>Liability management</h3>
                  <p>Track what your business owes with current and long-term liability categories.</p>
                  <ul>
                    <li>Accounts payable</li>
                    <li>Loans & debt</li>
                    <li>Tax obligations</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">E</div>
                  <h3>Equity calculation</h3>
                  <p>Automatic owner's equity and retained earnings calculations show net business value.</p>
                  <ul>
                    <li>Owner's equity tracking</li>
                    <li>Retained earnings</li>
                    <li>Net worth calculation</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">📊</div>
                  <h3>Financial dashboards</h3>
                  <p>Visual reports summarize assets, liabilities, equity, and financial ratios at a glance.</p>
                  <ul>
                    <li>Balance sheet summaries</li>
                    <li>Financial ratios</li>
                    <li>Trend analysis</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Eight worksheets, <span className="serif-accent">one</span> generation.</h2>
              <p className="intro">A complete balance sheet workspace — every sheet linked, every formula wired, every dashboard ready on open.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                  <div className="spec-head-cell">Type</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Balance Sheet</span>
                  <span className="spec-purpose">Main statement with assets, liabilities, and equity organized by category.</span>
                  <span className="spec-tag">Core</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Asset Register</span>
                  <span className="spec-purpose">Detailed tracking of all business assets with values and categories.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Liability Tracker</span>
                  <span className="spec-purpose">Monitors financial obligations, payment schedules, and debt terms.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Equity Summary</span>
                  <span className="spec-purpose">Calculates owner's equity, retained earnings, and net business value.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Accounts Receivable</span>
                  <span className="spec-purpose">Tracks customer balances, payment terms, and collection status.</span>
                  <span className="spec-tag">Operations</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Accounts Payable</span>
                  <span className="spec-purpose">Organizes vendor payments, due dates, and outstanding obligations.</span>
                  <span className="spec-tag">Operations</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Financial Dashboard</span>
                  <span className="spec-purpose">Visualizes financial position with charts, ratios, and trends.</span>
                  <span className="spec-tag">Dashboard</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Reporting Summary</span>
                  <span className="spec-purpose">Generates financial statements, summaries, and business insights.</span>
                  <span className="spec-tag">Report</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Under the hood</div>
              <h2>The formulas that <span className="serif-accent">power</span> your balance sheet.</h2>
              <p className="intro">Every Formula Byte balance sheet template is wired up with essential financial functions — generated, linked, and tested automatically.</p>
            </div>
            <div className="row-body">
              <div className="formula-grid">
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=SUM</span>(<span className="arg">range</span>)</div>
                  <div className="formula-desc">Calculates <em>total assets</em>, <em>total liabilities</em>, and category subtotals instantly.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=IF</span>(<span className="arg">condition, true, false</span>)</div>
                  <div className="formula-desc">Enables <em>conditional formatting</em> and automated account categorization.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=XLOOKUP</span>(<span className="arg">value, range, return</span>)</div>
                  <div className="formula-desc">Retrieves <em>account details</em> and references across worksheets.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=Assets</span> - <span className="fn">=Liabilities</span></div>
                  <div className="formula-desc">Calculates <em>owner's equity</em> using the fundamental accounting equation.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=ROUND</span>(<span className="arg">value, decimals</span>)</div>
                  <div className="formula-desc">Ensures <em>financial accuracy</em> and proper decimal formatting for all monetary values.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=SUBTOTAL</span>(<span className="arg">function, range</span>)</div>
                  <div className="formula-desc">Creates <em>filtered totals</em> that adapt when you filter accounts or categories.</div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Four business types, <span className="serif-accent">one</span> balance sheet engine.</h2>
              <p className="intro">Customize the financial statement for any business structure — same engine, different categories.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">S</div>
                    <div>
                      <h4>Small business balance sheet</h4>
                      <div className="industry-tagline">RETAIL · SERVICE · LOCAL</div>
                    </div>
                  </div>
                  <p>Track business assets, operational liabilities, and owner equity. Ideal for local businesses monitoring financial health and loan applications.</p>
                  <ul>
                    <li>Business assets & equipment</li>
                    <li>Operational liabilities</li>
                    <li>Owner equity tracking</li>
                    <li>Financial performance</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">E</div>
                    <div>
                      <h4>Ecommerce financial statement</h4>
                      <div className="industry-tagline">SHOPIFY · AMAZON · ETSY</div>
                    </div>
                  </div>
                  <p>Manage inventory value, revenue balances, supplier liabilities, and multi-channel financial reporting for online sellers.</p>
                  <ul>
                    <li>Inventory value tracking</li>
                    <li>Platform balances</li>
                    <li>Supplier liabilities</li>
                    <li>Multi-channel reporting</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">F</div>
                    <div>
                      <h4>Freelancer financial reporting</h4>
                      <div className="industry-tagline">CONSULTANTS · CONTRACTORS</div>
                    </div>
                  </div>
                  <p>Track client receivables, business expenses, tax obligations, and personal business equity for independent professionals.</p>
                  <ul>
                    <li>Client receivables</li>
                    <li>Operating expenses</li>
                    <li>Tax planning</li>
                    <li>Business equity</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">🚀</div>
                    <div>
                      <h4>Startup financial position</h4>
                      <div className="industry-tagline">FUNDED · GROWTH · PRE-IPO</div>
                    </div>
                  </div>
                  <p>Monitor investor equity, business liabilities, funding allocation, operational assets, and financial growth for investor reporting.</p>
                  <ul>
                    <li>Investor equity tracking</li>
                    <li>Funding allocation</li>
                    <li>Burn rate & runway</li>
                    <li>Investor reporting</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Manual reporting vs. <span className="serif-accent">Formula Byte.</span></h2>
              <p className="intro">Most balance sheet templates are static files with limited customization. Formula Byte generates AI-powered financial systems tailored to your business.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual financial reporting</div>
                  <h3>Spreadsheets built by hand</h3>
                  <ul>
                    <li>Manual account entry & categorization</li>
                    <li>Error-prone equity calculations</li>
                    <li>Time-consuming formula setup</li>
                    <li>Limited financial visibility</li>
                    <li>Basic reporting, no dashboards</li>
                    <li>Difficult to customize for business needs</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>Generated, automated, accurate</h3>
                  <ul>
                    <li>Automated account organization</li>
                    <li>Instant equity calculations</li>
                    <li>Financial formulas wired automatically</li>
                    <li>Clear financial dashboards</li>
                    <li>Balance sheet & ratio reporting included</li>
                    <li>Fully customizable for your business</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-generated <span className="serif-accent">balance sheet</span> templates.</h2>
              <p className="intro">Faster financial reporting, improved accuracy, better business decisions — every calculation you need already built in.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster financial reporting</h3>
                  <p>Generate complete balance sheet structures instantly instead of spending hours on manual spreadsheet creation and formula setup.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">90%</span>
                    <span className="benefit-stat-label">Less setup time</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Better financial organization</h3>
                  <p>Structured asset and liability categories improve accounting visibility and make financial reporting clearer and more consistent.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Organized</span>
                    <span className="benefit-stat-label">Account structure</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Reduce accounting errors</h3>
                  <p>Automated SUM, IF, and equity formulas eliminate calculation mistakes and ensure balance sheet accuracy.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">100%</span>
                    <span className="benefit-stat-label">Formula accuracy</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Improved business insights</h3>
                  <p>Financial dashboards and ratio analysis help you understand assets, liabilities, and equity trends for better decisions.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Real-time</span>
                    <span className="benefit-stat-label">Financial insights</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Easier financial analysis</h3>
                  <p>Visual reports and summaries simplify business performance evaluation and stakeholder communication.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Built-in</span>
                    <span className="benefit-stat-label">Analysis tools</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Support loan applications</h3>
                  <p>Professional balance sheet formatting and calculations improve loan approval chances and investor confidence.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Bank-ready</span>
                    <span className="benefit-stat-label">Financial statements</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently asked questions.</h2>
              <p className="intro">Everything you need to know about balance sheet templates and Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">What is a balance sheet template?</summary>
                  <div className="faq-a">
                    A balance sheet template is a pre-structured Excel spreadsheet that organizes a company's assets, liabilities, and equity at a specific point in time. Formula Byte generates these templates automatically with built-in formulas, financial categories, and reporting dashboards.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the balance sheet calculate assets and liabilities automatically?</summary>
                  <div className="faq-a">
                    Yes. Formula Byte generates balance sheet templates with automated SUM formulas, category totals, and equity calculations. All financial formulas are wired automatically — no manual Excel work needed.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize the balance sheet structure?</summary>
                  <div className="faq-a">
                    Absolutely. Asset categories, liability sections, equity calculations, and reporting formats can all be customized. Describe your business structure, and Formula Byte generates a tailored balance sheet with the right accounts and categories.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this template work in Google Sheets?</summary>
                  <div className="faq-a">
                    Yes. All Formula Byte balance sheet templates work in both Microsoft Excel and Google Sheets. Generate once, export to your preferred platform, and all formulas and formatting remain intact.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for small business financial reporting?</summary>
                  <div className="faq-a">
                    Yes. Small businesses commonly use balance sheet spreadsheets to monitor financial position, support loan applications, and maintain accurate accounting records. Formula Byte templates are designed specifically for small business needs.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">What financial formulas are included?</summary>
                  <div className="faq-a">
                    Formula Byte includes SUM, IF, XLOOKUP, SUBTOTAL, and equity calculation formulas. These automate asset totals, liability summaries, owner's equity, and financial ratios — all wired together and ready to use.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I track multiple business entities?</summary>
                  <div className="faq-a">
                    Yes. You can generate balance sheet templates for multiple business entities, departments, or divisions. Each template is independent and can be customized for that specific entity's structure and reporting needs.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this balance sheet template free to use?</summary>
                  <div className="faq-a">
                    Yes. The balance sheet template is completely free to generate and use. Describe your business structure, generate the balance sheet, and download it — no credit card or subscription required.
                  </div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Stop building financial statements manually. <span className="accent">Start automating.</span></h2>
            <p>Generate your AI-powered balance sheet template in seconds — professional formulas, financial dashboards, and reporting systems included.</p>
            <div className="btn-row">
              <a href="/auth?template=balance-sheet" className="btn btn-primary btn-lg">Generate balance sheet →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse more templates</a>
            </div>
          </div>
        </section>
      </div>

 

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}