export default function BusinessBudgetTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=financial">Financial</a>
            <span className="sep">/</span>
            <span className="current">Business Budget</span>
          </div>

          <div className="eyebrow">Financial template</div>
          <h1>AI Excel Business Budget Template for Small Business <span className="accent">Financial Planning</span></h1>
          <p className="lede">
            Track income, expenses, cash flow, and business financial performance with an AI-generated Excel business budget template designed for smarter budgeting and operational planning. Formula Byte helps businesses automate budget management using intelligent spreadsheets with built-in formulas, forecasting dashboards, and organized expense tracking systems.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>18</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate business budget spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Startups</span>
          <span className="use-case-pill"><span className="dot"></span>Ecommerce brands</span>
          <span className="use-case-pill"><span className="dot"></span>Agencies</span>
          <span className="use-case-pill"><span className="dot"></span>Contractors</span>
          <span className="use-case-pill"><span className="dot"></span>Freelancers</span>
          <span className="use-case-pill"><span className="dot"></span>Consultants</span>
          <span className="use-case-pill"><span className="dot"></span>Personal business budgeting</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Business-Budget<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">E8</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=SUM</span>(<span className="num">E5:E7</span>) - <span className="fn">SUM</span>(<span className="num">B5:B16</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header preview-hide-mobile">F</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Item</div>
            <div className="preview-cell preview-header-cell">Jan</div>
            <div className="preview-cell preview-header-cell">Feb</div>
            <div className="preview-cell preview-header-cell">Mar</div>
            <div className="preview-cell preview-header-cell">Total</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Notes</div>

            {/* Row 2 - Income section */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text faded">INCOME</div>
            <div className="preview-cell text faded"></div>
            <div className="preview-cell text faded"></div>
            <div className="preview-cell text faded"></div>
            <div className="preview-cell text faded"></div>
            <div className="preview-cell text faded preview-hide-mobile"></div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">Product Sales</div>
            <div className="preview-cell">$15,000</div>
            <div className="preview-cell">$16,500</div>
            <div className="preview-cell">$18,000</div>
            <div className="preview-cell">$49,500</div>
            <div className="preview-cell text preview-hide-mobile">Core revenue</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">Service Revenue</div>
            <div className="preview-cell">$8,000</div>
            <div className="preview-cell">$8,500</div>
            <div className="preview-cell">$9,200</div>
            <div className="preview-cell">$25,700</div>
            <div className="preview-cell text preview-hide-mobile">Consulting</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">Subscription Income</div>
            <div className="preview-cell">$3,500</div>
            <div className="preview-cell">$3,800</div>
            <div className="preview-cell">$4,200</div>
            <div className="preview-cell">$11,500</div>
            <div className="preview-cell text preview-hide-mobile">MRR</div>

            {/* Row 6 - Total Income */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell preview-header-cell">Total Income</div>
            <div className="preview-cell preview-header-cell">$26,500</div>
            <div className="preview-cell preview-header-cell">$28,800</div>
            <div className="preview-cell preview-header-cell">$31,400</div>
            <div className="preview-cell preview-header-cell">$86,700</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile"></div>

            {/* Row 7 - Expenses section */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text faded">EXPENSES</div>
            <div className="preview-cell text faded"></div>
            <div className="preview-cell text faded"></div>
            <div className="preview-cell text faded"></div>
            <div className="preview-cell text faded"></div>
            <div className="preview-cell text faded preview-hide-mobile"></div>

            {/* Row 8 */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text">Rent</div>
            <div className="preview-cell">$3,000</div>
            <div className="preview-cell">$3,000</div>
            <div className="preview-cell">$3,000</div>
            <div className="preview-cell">$9,000</div>
            <div className="preview-cell text preview-hide-mobile">Office lease</div>

            {/* Row 9 */}
            <div className="preview-row-num">9</div>
            <div className="preview-cell text">Payroll</div>
            <div className="preview-cell">$12,000</div>
            <div className="preview-cell">$12,500</div>
            <div className="preview-cell">$13,000</div>
            <div className="preview-cell">$37,500</div>
            <div className="preview-cell text preview-hide-mobile">Salaries</div>

            {/* Row 10 */}
            <div className="preview-row-num">10</div>
            <div className="preview-cell text">Marketing</div>
            <div className="preview-cell">$2,500</div>
            <div className="preview-cell">$2,800</div>
            <div className="preview-cell">$3,200</div>
            <div className="preview-cell">$8,500</div>
            <div className="preview-cell text preview-hide-mobile">Ads & promo</div>

            {/* Row 11 */}
            <div className="preview-row-num">11</div>
            <div className="preview-cell text">Software</div>
            <div className="preview-cell">$800</div>
            <div className="preview-cell">$850</div>
            <div className="preview-cell">$900</div>
            <div className="preview-cell">$2,550</div>
            <div className="preview-cell text preview-hide-mobile">SaaS tools</div>

            {/* Row 12 - Total Expenses */}
            <div className="preview-row-num">12</div>
            <div className="preview-cell preview-header-cell">Total Expenses</div>
            <div className="preview-cell preview-header-cell">$18,300</div>
            <div className="preview-cell preview-header-cell">$19,150</div>
            <div className="preview-cell preview-header-cell">$20,100</div>
            <div className="preview-cell preview-header-cell">$57,550</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile"></div>

            {/* Row 13 - Profit */}
            <div className="preview-row-num">13</div>
            <div className="preview-cell preview-header-cell">NET PROFIT</div>
            <div className="preview-cell preview-header-cell">$8,200</div>
            <div className="preview-cell preview-header-cell">$9,650</div>
            <div className="preview-cell preview-header-cell">$11,300</div>
            <div className="preview-cell preview-header-cell">$29,150</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">31% margin</div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Total Income:</span>
              <span className="val">$86,700</span>
            </div>
            <div className="preview-status-item">
              <span>Total Expenses:</span>
              <span className="val">$57,550</span>
            </div>
            <div className="preview-status-item">
              <span>Net Profit:</span>
              <span className="val">$29,150</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">Budget</button>
              <button className="preview-tab">Income</button>
              <button className="preview-tab">Expenses</button>
              <button className="preview-tab">Forecast</button>
              <button className="preview-tab">+4</button>
            </div>
          </div>
        </div>
      </div>

      {/* CREATE AN AI BUSINESS BUDGET SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Business Budget Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the budget spreadsheet you need, and Formula Byte automatically generates a professional Excel budgeting system with:</p>
            </div>
            <div className="row-body">
              <ul className="bulleted">
                <li>Income tracking</li>
                <li>Expense categorization</li>
                <li>Budget forecasting</li>
                <li>Monthly financial summaries</li>
                <li>Operational cost analysis</li>
                <li>Cash flow planning</li>
                <li>Automated spreadsheet formulas</li>
                <li>Financial dashboards</li>
                <li>Business performance reporting</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually creating budget spreadsheets, Formula Byte builds AI-powered budgeting systems tailored to your financial workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel Business Budget Template?</h2>
              <p className="intro">A structured spreadsheet used to plan, organize, and monitor business income and expenses over a specific period.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel business budget template</strong> is a structured spreadsheet used to plan, organize, and monitor business income and expenses over a specific period. It helps businesses manage operational costs, forecast financial performance, and improve budgeting decisions.
              </p>
              <p>
                A business budget spreadsheet typically includes:
              </p>
              <ul className="bulleted">
                <li>Revenue tracking</li>
                <li>Expense categories</li>
                <li>Budget forecasts</li>
                <li>Financial summaries</li>
                <li>Profit analysis</li>
                <li>Operational cost tracking</li>
                <li>Cash flow planning</li>
                <li>Monthly and yearly budgeting reports</li>
              </ul>
              <p>Formula Byte generates AI-powered budget spreadsheets designed for financial planning and business expense management.</p>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How Business Budgeting Works</h2>
              <p className="intro">Business budgeting is the process of estimating income, planning expenses, and controlling operational spending.</p>
            </div>
            <div className="row-body">
              <p>Business budgeting is the process of estimating income, planning expenses, and controlling operational spending to maintain financial stability and profitability.</p>
              <p style={{marginTop: '18px'}}>A structured budget helps businesses:</p>
              <ul className="bulleted">
                <li>Allocate resources efficiently</li>
                <li>Monitor operational costs</li>
                <li>Plan future expenses</li>
                <li>Forecast business growth</li>
                <li>Improve financial decision-making</li>
                <li>Reduce overspending risks</li>
              </ul>
              <p style={{marginTop: '18px'}}>Most business budgets track:</p>
              <ul className="bulleted">
                <li>Revenue projections</li>
                <li>Fixed expenses</li>
                <li>Variable expenses</li>
                <li>Marketing costs</li>
                <li>Payroll expenses</li>
                <li>Operational spending</li>
                <li>Profit margins</li>
                <li>Financial forecasts</li>
              </ul>
              <p style={{marginTop: '18px'}}>Formula Byte simplifies this process using AI-generated budgeting spreadsheets and automated financial calculations.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY SMALL BUSINESSES NEED BUDGET PLANNING SYSTEMS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Small Businesses Need Budget Planning Systems</h2>
              <p className="intro">Managing finances without a structured budgeting system often creates financial confusion and operational risks.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without a budgeting system</div>
                  <h3>Managing finances without a structured budgeting system often creates:</h3>
                  <ul>
                    <li>Uncontrolled spending</li>
                    <li>Poor cash flow management</li>
                    <li>Financial uncertainty</li>
                    <li>Budget calculation errors</li>
                    <li>Revenue forecasting issues</li>
                    <li>Overspending problems</li>
                    <li>Inconsistent financial planning</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With a structured budget</div>
                  <h3>A properly organized business budget helps companies:</h3>
                  <ul>
                    <li>Monitor financial health</li>
                    <li>Control operational costs</li>
                    <li>Improve spending decisions</li>
                    <li>Forecast future growth</li>
                    <li>Maintain profitability</li>
                    <li>Organize financial data</li>
                    <li>Improve cash flow visibility</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI <span className="serif-accent">Budget</span> Spreadsheet</h2>
              <p className="intro">Four pillars of budget tracking — automatic, accurate, and built to support real business decisions.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">$</div>
                  <h3>Income Tracking</h3>
                  <p>Track all business revenue streams with automatic categorization and real-time summaries.</p>
                  <ul>
                    <li>Product sales</li>
                    <li>Service revenue</li>
                    <li>Client payments</li>
                    <li>Subscription income</li>
                    <li>Investment earnings</li>
                    <li>Other business revenue streams</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>The spreadsheet automatically organizes revenue categories and financial summaries.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">E</div>
                  <h3>Expense Management</h3>
                  <p>Monitor all operational expenses with organized tracking and automated calculations.</p>
                  <ul>
                    <li>Rent</li>
                    <li>Utilities</li>
                    <li>Payroll</li>
                    <li>Marketing costs</li>
                    <li>Software subscriptions</li>
                    <li>Inventory purchases</li>
                    <li>Operational expenses</li>
                    <li>Vendor payments</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This helps businesses maintain structured financial organization and expense visibility.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">F</div>
                  <h3>Budget Forecasting</h3>
                  <p>Formula Byte can generate forecasting systems that help businesses predict and plan.</p>
                  <ul>
                    <li>Predict future expenses</li>
                    <li>Estimate monthly cash flow</li>
                    <li>Forecast profitability</li>
                    <li>Analyze financial performance</li>
                    <li>Prepare growth strategies</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This improves long-term financial planning and budgeting accuracy.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">C</div>
                  <h3>Cash Flow Monitoring</h3>
                  <p>Cash flow management is one of the most important parts of business budgeting.</p>
                  <ul>
                    <li>Incoming revenue tracking</li>
                    <li>Expense monitoring</li>
                    <li>Monthly balance summaries</li>
                    <li>Financial forecasting dashboards</li>
                    <li>Operational cash flow analysis</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This helps businesses maintain financial stability and operational efficiency.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI BUDGETING AUTOMATION FOR MODERN BUSINESSES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Budgeting Automation for Modern Businesses</h2>
              <p className="intro">Skip the manual setup. The AI understands budgeting instructions from natural language prompts.</p>
            </div>
            <div className="row-body">
              <p>Traditional budget spreadsheets require manual setup and repetitive calculations.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure budgeting worksheets</li>
                <li>Generate Excel formulas</li>
                <li>Organize expense categories</li>
                <li>Build financial dashboards</li>
                <li>Create forecasting systems</li>
                <li>Generate budget summaries</li>
                <li>Apply spreadsheet formatting</li>
                <li>Automate financial calculations</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands budgeting instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a small business monthly budget spreadsheet"</button>
                  <button className="chip">"Build a startup expense tracking dashboard"</button>
                  <button className="chip">"Generate an ecommerce budget forecasting template"</button>
                  <button className="chip">"Create a business cash flow planning spreadsheet"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Business Budget Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete budgeting spreadsheet with 8 worksheets — each generated, formatted, and wired up automatically.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Income Tracker</span>
                  <span className="spec-purpose">Monitors business revenue</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Expense Ledger</span>
                  <span className="spec-purpose">Tracks operational expenses</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Budget Forecast</span>
                  <span className="spec-purpose">Predicts future financial performance</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Cash Flow Dashboard</span>
                  <span className="spec-purpose">Monitors financial movement</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Payroll Budget Sheet</span>
                  <span className="spec-purpose">Organizes employee expenses</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Marketing Budget Tracker</span>
                  <span className="spec-purpose">Tracks advertising and campaign costs</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Financial Summary</span>
                  <span className="spec-purpose">Generates reporting overviews</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Profit Analysis Dashboard</span>
                  <span className="spec-purpose">Tracks profitability and spending trends</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BUDGET CATEGORIES INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Budget categories</div>
              <h2>Budget Categories <span className="serif-accent">Included</span></h2>
              <p className="intro">Comprehensive expense and income categories organized for complete business budget tracking.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">FE</div>
                  <h3>Fixed Expenses</h3>
                  <p>Track recurring operational costs such as:</p>
                  <ul>
                    <li>Rent</li>
                    <li>Salaries</li>
                    <li>Insurance</li>
                    <li>Software subscriptions</li>
                    <li>Utilities</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">VE</div>
                  <h3>Variable Expenses</h3>
                  <p>Monitor changing business costs including:</p>
                  <ul>
                    <li>Advertising</li>
                    <li>Shipping</li>
                    <li>Inventory purchases</li>
                    <li>Equipment costs</li>
                    <li>Contractor payments</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">RF</div>
                  <h3>Revenue Forecasting</h3>
                  <p>Estimate:</p>
                  <ul>
                    <li>Monthly income</li>
                    <li>Quarterly growth</li>
                    <li>Seasonal revenue trends</li>
                    <li>Profit projections</li>
                    <li>Financial targets</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">CF</div>
                  <h3>Cash Flow Planning</h3>
                  <p>Manage:</p>
                  <ul>
                    <li>Incoming cash flow</li>
                    <li>Outgoing expenses</li>
                    <li>Monthly balances</li>
                    <li>Financial reserves</li>
                    <li>Liquidity planning</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Under the hood</div>
              <h2>Built-In Excel Formulas and <span className="serif-accent">Budget</span> Automation</h2>
              <p className="intro">Every Formula Byte business budget template is wired up with industry-standard financial functions.</p>
            </div>
            <div className="row-body">
              <div className="formula-grid">
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=SUM</span>(<span className="arg">range</span>)</div>
                  <div className="formula-desc">Calculates totals for income, expenses, and profit categories.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=IF</span>(<span className="arg">condition, value_if_true, value_if_false</span>)</div>
                  <div className="formula-desc">Creates conditional logic for budget calculations and alerts.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=XLOOKUP</span>(<span className="arg">lookup_value, lookup_array, return_array</span>)</div>
                  <div className="formula-desc">Retrieves budget details and financial data across worksheets.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">Forecasting calculations</span></div>
                  <div className="formula-desc">Dynamic financial dashboards with trend analysis.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">Conditional formatting</span></div>
                  <div className="formula-desc">Budget tracking systems with visual indicators.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">Expense analysis formulas</span></div>
                  <div className="formula-desc">Profitability summaries and spending insights.</div>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>These spreadsheet automations reduce manual budgeting work and improve financial accuracy.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Business Budget Templates by <span className="serif-accent">Industry</span></h2>
              <p className="intro">Customize the budget for any business type — same structure, different focus.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">SB</div>
                    <div>
                      <h4>Small Business Budget Spreadsheet</h4>
                      <div className="industry-tagline">GENERAL · RETAIL · SERVICE</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Operational expenses</li>
                    <li>Revenue growth</li>
                    <li>Payroll costs</li>
                    <li>Financial performance</li>
                    <li>Cash reserves</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Ideal for startups and growing businesses.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">EC</div>
                    <div>
                      <h4>Ecommerce Budget Template</h4>
                      <div className="industry-tagline">SHOPIFY · AMAZON · ETSY</div>
                    </div>
                  </div>
                  <p>Manage:</p>
                  <ul>
                    <li>Product costs</li>
                    <li>Advertising spend</li>
                    <li>Inventory expenses</li>
                    <li>Marketplace fees</li>
                    <li>Revenue forecasting</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for Shopify, Amazon, Etsy, and WooCommerce businesses.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">FR</div>
                    <div>
                      <h4>Freelancer Budget Spreadsheet</h4>
                      <div className="industry-tagline">CONSULTANTS · FREELANCERS</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Client income</li>
                    <li>Monthly expenses</li>
                    <li>Tax estimates</li>
                    <li>Subscription costs</li>
                    <li>Profitability</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Designed for consultants, freelancers, and independent professionals.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">ST</div>
                    <div>
                      <h4>Startup Financial Budget Template</h4>
                      <div className="industry-tagline">FUNDED · GROWTH · INVESTOR</div>
                    </div>
                  </div>
                  <p>Monitor:</p>
                  <ul>
                    <li>Investor funding</li>
                    <li>Burn rate</li>
                    <li>Operational expenses</li>
                    <li>Growth forecasting</li>
                    <li>Financial runway</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for startup financial planning and investor reporting.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINANCIAL REPORTS AND BUDGET ANALYSIS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Financial Reports and Budget Analysis</h2>
              <p className="intro">Every generated budget system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte budget spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Monthly budget summaries</li>
                <li>Expense analysis reports</li>
                <li>Profit forecasting reports</li>
                <li>Cash flow summaries</li>
                <li>Financial performance dashboards</li>
                <li>Operational spending reports</li>
                <li>Revenue tracking insights</li>
                <li>Budget comparison analysis</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve financial visibility and support better business planning.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Budget Spreadsheet vs. <span className="serif-accent">Manual</span> Budget Tracking</h2>
              <p className="intro">Seven dimensions where AI-powered budget spreadsheets outperform manual budget tracking.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual Budget Tracking</div>
                  <h3>Manual budget tracking</h3>
                  <ul>
                    <li>Manual calculations</li>
                    <li>Limited forecasting</li>
                    <li>Error-prone reporting</li>
                    <li>Time-consuming setup</li>
                    <li>Basic tracking</li>
                    <li>Often inconsistent</li>
                    <li>Limited customization</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>AI-generated spreadsheets</h3>
                  <ul>
                    <li>Automated calculations</li>
                    <li>Included forecasting</li>
                    <li>High accuracy</li>
                    <li>Fast setup</li>
                    <li>Dashboard-based</li>
                    <li>Structured organization</li>
                    <li>High customization</li>
                  </ul>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify budgeting and financial planning workflows.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">Budget</span> Templates</h2>
              <p className="intro">Faster setup, fewer errors, sharper financial insights — every number you'd want already calculated.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster Budget Creation</h3>
                  <p>Generate complete business budgeting systems instantly without manual spreadsheet setup.</p>
                </div>
                <div className="benefit-card">
                  <h3>Better Financial Organization</h3>
                  <p>Structured budgeting worksheets improve financial visibility and expense management.</p>
                </div>
                <div className="benefit-card">
                  <h3>Reduced Budgeting Errors</h3>
                  <p>Automated formulas reduce financial mistakes and reporting inconsistencies.</p>
                </div>
                <div className="benefit-card">
                  <h3>Improved Financial Forecasting</h3>
                  <p>Budget dashboards help businesses analyze growth trends and operational spending more effectively.</p>
                </div>
                <div className="benefit-card">
                  <h3>Smarter Business Decisions</h3>
                  <p>Clear financial reporting supports better budgeting strategies and profitability planning.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing <span className="serif-accent">Business Budget</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated budget into a real financial planning tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Update Budget Data Regularly</h3>
                  <p>Consistent updates improve financial forecasting and budget accuracy.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Organize Expense Categories Properly</h3>
                  <p>Structured budgeting categories improve reporting quality and financial visibility.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Monitor Spending Trends</h3>
                  <p>Regular reviews help identify:</p>
                  <ul>
                    <li>Overspending risks</li>
                    <li>Revenue changes</li>
                    <li>Expense growth</li>
                    <li>Profitability issues</li>
                    <li>Financial opportunities</li>
                  </ul>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Review Financial Forecasts Monthly</h3>
                  <p>Monthly budget reviews help businesses maintain better operational planning and financial control.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most business budget templates are static spreadsheets with limited flexibility.</p>
            </div>
            <div className="row-body">
              <p>Most business budget templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated budgeting systems tailored to your business workflow, expense structure, and financial planning requirements.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Budget planning spreadsheets</li>
                <li>Expense management systems</li>
                <li>Financial dashboards</li>
                <li>Revenue forecasting tools</li>
                <li>Cash flow tracking sheets</li>
                <li>Operational finance reports</li>
                <li>Automated budget formulas</li>
                <li>Business-specific budgeting workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually building budgeting spreadsheets, Formula Byte automates financial planning using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This <span className="serif-accent">Business Budget</span> Spreadsheet?</h2>
              <p className="intro">This spreadsheet solution is ideal for businesses and professionals managing budgets and expenses.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>Startups</h4></div>
                <div className="audience-cell"><h4>Ecommerce brands</h4></div>
                <div className="audience-cell"><h4>Agencies</h4></div>
                <div className="audience-cell"><h4>Consultants</h4></div>
                <div className="audience-cell"><h4>Contractors</h4></div>
                <div className="audience-cell"><h4>Freelancers</h4></div>
                <div className="audience-cell"><h4>Finance managers</h4></div>
                <div className="audience-cell"><h4>Business owners</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple expense tracking or advanced budget forecasting, Formula Byte helps automate business budget spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating business budget templates with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet forecast business expenses automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates budget spreadsheets with automated forecasting formulas and financial calculations.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include financial dashboards?</summary>
                  <div className="faq-a">Yes. The spreadsheet can include budgeting dashboards, summaries, and financial analysis visuals.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize budget categories?</summary>
                  <div className="faq-a">Absolutely. Revenue categories, expense sections, forecasting layouts, and budgeting structures can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte business budget templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for small business budgeting?</summary>
                  <div className="faq-a">Yes. Small businesses commonly use budgeting spreadsheets to manage expenses, monitor financial performance, and forecast profitability.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other financial templates you might need.</h2>
              <p className="intro">Same engine, different financial workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/profit-and-loss-template/" className="related-card">
                  <div className="glyph">P</div>
                  <h4>Profit &amp; Loss</h4>
                  <p>Monthly and yearly P&amp;L with built-in formulas and margin tracking.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/balance-sheet-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Balance Sheet</h4>
                  <p>Track assets, liabilities, equity, and financial position.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/amortization-schedule-template/" className="related-card">
                  <div className="glyph">A</div>
                  <h4>Amortization Schedule</h4>
                  <p>Track loan payments, interest, principal balances, and repayment progress.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/invoice-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Invoice Template</h4>
                  <p>Professional invoices with auto-numbering, taxes, and totals.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">Business Budget</span> Spreadsheet?</h2>
            <p>Stop building budgeting spreadsheets manually.</p>
            <p>Describe your budgeting workflow, and Formula Byte will generate a professional AI-powered Excel business budget template with automated formulas, forecasting dashboards, expense tracking systems, and organized financial reporting structures in seconds.</p>
            <p>Create smarter budgeting spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}
