export default function BusinessBudgetTemplatePage() {
  return (
    <>
      <link rel="stylesheet" href="/page-styles/amortization-schedule-template.css" />

      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=financial">Financial</a>
            <span className="sep">/</span>
            <span className="current">Business Budget</span>
          </div>

          <div className="eyebrow">Financial template</div>
          <h1>AI Business <span className="accent">Budget</span> Template</h1>
          <p className="lede">
            Track income, expenses, cash flow, and business financial performance with an AI-generated Excel business budget template designed for smarter budgeting and operational planning.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>18</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="/auth?template=business-budget" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-suggest">
            <span>Try:</span>
            <button className="chip">Small business monthly budget</button>
            <button className="chip">Startup expense tracker</button>
            <button className="chip">Ecommerce budget forecast</button>
            <button className="chip">Freelancer budget planner</button>
          </div>
        </div>
      </section>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Business-Budget<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">E8</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=SUM</span>(<span className="num">E5:E7</span>) - <span className="fn">SUM</span>(<span className="num">B5:B16</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header preview-hide-mobile">F</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Category</div>
            <div className="preview-cell preview-header-cell">Budget</div>
            <div className="preview-cell preview-header-cell">Actual</div>
            <div className="preview-cell preview-header-cell">Variance</div>
            <div className="preview-cell preview-header-cell">Notes</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Reference</div>

            {/* Row 2 - Income section */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell preview-header-cell" style={{gridColumn: 'span 2'}}>INCOME</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-hide-mobile"></div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">Product Sales</div>
            <div className="preview-cell">$85,000</div>
            <div className="preview-cell">$92,000</div>
            <div className="preview-cell principal">+$7,000</div>
            <div className="preview-cell text">Above target</div>
            <div className="preview-cell text preview-hide-mobile">B3</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">Service Revenue</div>
            <div className="preview-cell">$45,000</div>
            <div className="preview-cell">$43,000</div>
            <div className="preview-cell interest">-$2,000</div>
            <div className="preview-cell text">Below target</div>
            <div className="preview-cell text preview-hide-mobile">B4</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">Total Income</div>
            <div className="preview-cell">$130,000</div>
            <div className="preview-cell selected">$135,000</div>
            <div className="preview-cell principal">+$5,000</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text preview-hide-mobile"></div>

            {/* Row 6 - Expenses section */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell preview-header-cell" style={{gridColumn: 'span 2'}}>EXPENSES</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-hide-mobile"></div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">Payroll</div>
            <div className="preview-cell">$52,000</div>
            <div className="preview-cell">$51,000</div>
            <div className="preview-cell principal">-$1,000</div>
            <div className="preview-cell text">Under budget</div>
            <div className="preview-cell text preview-hide-mobile">B7</div>

            {/* Row 8 */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text">Rent</div>
            <div className="preview-cell">$12,000</div>
            <div className="preview-cell">$12,000</div>
            <div className="preview-cell">$0</div>
            <div className="preview-cell text">On target</div>
            <div className="preview-cell text preview-hide-mobile">B8</div>

            {/* Row 9 */}
            <div className="preview-row-num">9</div>
            <div className="preview-cell text">Marketing</div>
            <div className="preview-cell">$8,000</div>
            <div className="preview-cell">$9,500</div>
            <div className="preview-cell interest">+$1,500</div>
            <div className="preview-cell text">Over budget</div>
            <div className="preview-cell text preview-hide-mobile">B9</div>

            {/* Row 10 */}
            <div className="preview-row-num">10</div>
            <div className="preview-cell text">Software</div>
            <div className="preview-cell">$3,500</div>
            <div className="preview-cell">$3,200</div>
            <div className="preview-cell principal">-$300</div>
            <div className="preview-cell text">Savings</div>
            <div className="preview-cell text preview-hide-mobile">B10</div>

            {/* Row 11 */}
            <div className="preview-row-num">11</div>
            <div className="preview-cell text">Total Expenses</div>
            <div className="preview-cell">$75,500</div>
            <div className="preview-cell">$75,700</div>
            <div className="preview-cell interest">+$200</div>
            <div className="preview-cell text"></div>
            <div className="preview-cell text preview-hide-mobile"></div>

            {/* Row 12 - Profit */}
            <div className="preview-row-num">12</div>
            <div className="preview-cell preview-header-cell" style={{gridColumn: 'span 2'}}>NET PROFIT</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-hide-mobile"></div>

            {/* Row 13 */}
            <div className="preview-row-num">13</div>
            <div className="preview-cell text">Profit</div>
            <div className="preview-cell">$54,500</div>
            <div className="preview-cell balance">$59,300</div>
            <div className="preview-cell principal">+$4,800</div>
            <div className="preview-cell text">Above target</div>
            <div className="preview-cell text preview-hide-mobile"></div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Total Income:</span>
              <span className="val">$135K</span>
            </div>
            <div className="preview-status-item">
              <span>Total Expenses:</span>
              <span className="val">$75.7K</span>
            </div>
            <div className="preview-status-item">
              <span>Net Profit:</span>
              <span className="val serif">$59.3K</span>
            </div>
            <div className="preview-status-item">
              <span>Margin:</span>
              <span className="val">43.9%</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">Budget</button>
              <button className="preview-tab">Forecast</button>
              <button className="preview-tab">Cash Flow</button>
              <button className="preview-tab">+5</button>
            </div>
          </div>
        </div>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What is an Excel Business Budget Template?</h2>
              <p className="intro">A structured spreadsheet used to plan, organize, and monitor business income and expenses over a specific period for financial planning and operational control.</p>
            </div>
            <div className="row-body">
              <p>
                A <strong>business budget template</strong> is a financial planning tool that helps you estimate income, plan expenses, and track actual performance against budget targets. It's essential for <strong>maintaining profitability</strong>, managing cash flow, and making informed business decisions.
              </p>
              <p>
                Effective budgeting helps businesses <strong>allocate resources efficiently</strong>, monitor operational costs, forecast financial performance, and maintain financial stability. Instead of reacting to financial surprises, a good budget lets you plan ahead and adjust spending based on data.
              </p>
              <ul className="bulleted">
                <li><strong>Revenue tracking</strong> — product sales, service income, client payments</li>
                <li><strong>Expense categorization</strong> — fixed costs, variable expenses, operational spending</li>
                <li><strong>Budget forecasting</strong> — monthly cash flow, profit projections, growth planning</li>
                <li><strong>Variance analysis</strong> — budget vs. actual, spending trends, cost control</li>
                <li><strong>Financial dashboards</strong> — profit margins, expense ratios, performance insights</li>
              </ul>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>From business description to budget system in seconds.</h2>
              <p className="intro">Describe your budgeting workflow, and Formula Byte generates a complete business budget with automated calculations and forecasting dashboards.</p>
            </div>
            <div className="row-body">
              <div className="steps">
                <div className="step">
                  <div className="step-num">1</div>
                  <div>
                    <h3>Describe your budgeting needs</h3>
                    <p>Business type, income sources, expense categories, budget period, forecasting requirements — in plain English or a quick form.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">2</div>
                  <div>
                    <h3>AI builds your budget structure</h3>
                    <p>SUM, IF, and variance formulas are wired to your income and expense categories. Budget targets and forecasting systems organize automatically.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">3</div>
                  <div>
                    <h3>Financial formulas calculate automatically</h3>
                    <p>Income totals, expense summaries, profit calculations, and budget variances update instantly as you enter or adjust financial data.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">4</div>
                  <div>
                    <h3>Generate budget dashboards</h3>
                    <p>Variance analysis, profit trends, expense breakdowns, and cash flow forecasts appear on dedicated dashboard sheets for quick insights.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>What every generated <span className="serif-accent">business budget</span> includes.</h2>
              <p className="intro">Complete budgeting system — income tracking, expense management, forecasting, and financial dashboards in one template.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">$</div>
                  <h3>Income tracking</h3>
                  <p>Monitor all revenue streams with organized categories and automated totaling for accurate financial forecasting.</p>
                  <ul>
                    <li>Product & service revenue</li>
                    <li>Client payment tracking</li>
                    <li>Multi-channel income</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">📊</div>
                  <h3>Expense management</h3>
                  <p>Categorize and track all operational costs with budget targets and variance analysis.</p>
                  <ul>
                    <li>Fixed & variable expenses</li>
                    <li>Payroll & operational costs</li>
                    <li>Marketing & software spend</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">📈</div>
                  <h3>Budget forecasting</h3>
                  <p>Predict future income and expenses with automated forecasting models and trend analysis.</p>
                  <ul>
                    <li>Monthly cash flow forecasts</li>
                    <li>Profit projections</li>
                    <li>Seasonal trend analysis</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">💰</div>
                  <h3>Cash flow monitoring</h3>
                  <p>Track financial movement with incoming revenue, outgoing expenses, and balance projections.</p>
                  <ul>
                    <li>Monthly cash flow tracking</li>
                    <li>Balance forecasting</li>
                    <li>Liquidity planning</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Eight worksheets, <span className="serif-accent">one</span> generation.</h2>
              <p className="intro">A complete budgeting workspace — every sheet linked, every formula wired, every dashboard ready on open.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                  <div className="spec-head-cell">Type</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Income Tracker</span>
                  <span className="spec-purpose">Monitors business revenue, product sales, service income, and payment collections.</span>
                  <span className="spec-tag">Core</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Expense Ledger</span>
                  <span className="spec-purpose">Tracks operational expenses, payroll, marketing, and all business spending.</span>
                  <span className="spec-tag">Core</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Budget Forecast</span>
                  <span className="spec-purpose">Predicts future income, expenses, and cash flow with automated forecasting models.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Cash Flow Dashboard</span>
                  <span className="spec-purpose">Monitors financial movement with monthly inflow, outflow, and balance summaries.</span>
                  <span className="spec-tag">Dashboard</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Payroll Budget Sheet</span>
                  <span className="spec-purpose">Organizes employee expenses, salaries, benefits, and contractor payments.</span>
                  <span className="spec-tag">Operations</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Marketing Budget Tracker</span>
                  <span className="spec-purpose">Tracks advertising and campaign costs with ROI analysis and spend optimization.</span>
                  <span className="spec-tag">Operations</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Financial Summary</span>
                  <span className="spec-purpose">Generates profit analysis, variance reports, and financial overviews.</span>
                  <span className="spec-tag">Report</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Profit Analysis Dashboard</span>
                  <span className="spec-purpose">Tracks profitability, margins, expense trends, and budget performance insights.</span>
                  <span className="spec-tag">Dashboard</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Under the hood</div>
              <h2>The formulas that <span className="serif-accent">power</span> your budget.</h2>
              <p className="intro">Every Formula Byte business budget template is wired up with essential financial functions — generated, linked, and tested automatically.</p>
            </div>
            <div className="row-body">
              <div className="formula-grid">
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=SUM</span>(<span className="arg">range</span>)</div>
                  <div className="formula-desc">Calculates <em>total income</em>, <em>total expenses</em>, and budget subtotals instantly.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=IF</span>(<span className="arg">condition, true, false</span>)</div>
                  <div className="formula-desc">Enables <em>budget alerts</em>, conditional formatting, and automated variance analysis.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=XLOOKUP</span>(<span className="arg">value, range, return</span>)</div>
                  <div className="formula-desc">Retrieves <em>account details</em>, expense categories, and budget references across worksheets.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=SUMIF</span>(<span className="arg">range, criteria, sum_range</span>)</div>
                  <div className="formula-desc">Calculates <em>category totals</em> for specific income or expense types.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=FORECAST</span>(<span className="arg">data, periods</span>)</div>
                  <div className="formula-desc">Predicts <em>future income</em> and expenses based on historical data trends.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=SUBTOTAL</span>(<span className="arg">function, range</span>)</div>
                  <div className="formula-desc">Creates <em>filtered totals</em> that adapt when you filter by category or period.</div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Four business types, <span className="serif-accent">one</span> budgeting engine.</h2>
              <p className="intro">Customize the budget structure for any business model — same engine, different categories and targets.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">S</div>
                    <div>
                      <h4>Small business budget spreadsheet</h4>
                      <div className="industry-tagline">RETAIL · SERVICE · LOCAL</div>
                    </div>
                  </div>
                  <p>Track operational expenses, revenue growth, payroll costs, and financial performance. Ideal for local businesses monitoring profitability and cash flow.</p>
                  <ul>
                    <li>Operational expenses</li>
                    <li>Revenue growth targets</li>
                    <li>Payroll budgeting</li>
                    <li>Financial performance</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">E</div>
                    <div>
                      <h4>Ecommerce budget template</h4>
                      <div className="industry-tagline">SHOPIFY · AMAZON · ETSY</div>
                    </div>
                  </div>
                  <p>Manage product costs, advertising spend, inventory expenses, marketplace fees, and revenue forecasting for online sellers.</p>
                  <ul>
                    <li>Product cost tracking</li>
                    <li>Advertising budget</li>
                    <li>Marketplace fees</li>
                    <li>Revenue forecasting</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">F</div>
                    <div>
                      <h4>Freelancer budget spreadsheet</h4>
                      <div className="industry-tagline">CONSULTANTS · CONTRACTORS</div>
                    </div>
                  </div>
                  <p>Track client income, monthly expenses, tax estimates, subscription costs, and profitability for independent professionals.</p>
                  <ul>
                    <li>Client income tracking</li>
                    <li>Monthly expenses</li>
                    <li>Tax planning</li>
                    <li>Profitability analysis</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">🚀</div>
                    <div>
                      <h4>Startup financial budget template</h4>
                      <div className="industry-tagline">FUNDED · GROWTH · STARTUP</div>
                    </div>
                  </div>
                  <p>Monitor investor funding, burn rate, operational expenses, growth forecasting, and financial runway for startup planning and investor reporting.</p>
                  <ul>
                    <li>Investor funding tracking</li>
                    <li>Burn rate analysis</li>
                    <li>Growth forecasting</li>
                    <li>Financial runway</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Manual budgeting vs. <span className="serif-accent">Formula Byte.</span></h2>
              <p className="intro">Most budget spreadsheets are static files with limited forecasting. Formula Byte generates AI-powered budgeting systems tailored to your business.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual budget tracking</div>
                  <h3>Spreadsheets built by hand</h3>
                  <ul>
                    <li>Manual expense entry & categorization</li>
                    <li>Time-consuming formula setup</li>
                    <li>Error-prone calculations</li>
                    <li>Limited forecasting capability</li>
                    <li>Basic reporting, no dashboards</li>
                    <li>Difficult to scale with growth</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>Generated, automated, accurate</h3>
                  <ul>
                    <li>Automated expense organization</li>
                    <li>Instant budget calculations</li>
                    <li>Forecasting formulas included</li>
                    <li>Financial dashboards built in</li>
                    <li>Variance analysis automated</li>
                    <li>Fully customizable for growth</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-generated <span className="serif-accent">business budget</span> templates.</h2>
              <p className="intro">Faster budget creation, better financial control, smarter decisions — every calculation and forecast you need already built in.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster budget creation</h3>
                  <p>Generate complete business budgeting systems instantly instead of spending hours on manual spreadsheet setup and formula construction.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">90%</span>
                    <span className="benefit-stat-label">Less setup time</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Better financial organization</h3>
                  <p>Structured budgeting worksheets improve financial visibility and make expense management clearer and more consistent.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Organized</span>
                    <span className="benefit-stat-label">Expense tracking</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Reduce budgeting errors</h3>
                  <p>Automated SUM, IF, and variance formulas eliminate calculation mistakes and ensure budget accuracy across all categories.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">100%</span>
                    <span className="benefit-stat-label">Formula accuracy</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Improve financial forecasting</h3>
                  <p>Budget dashboards help analyze income trends, expense patterns, and cash flow projections for smarter business planning.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Real-time</span>
                    <span className="benefit-stat-label">Financial insights</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Smarter spending decisions</h3>
                  <p>Variance analysis and expense tracking help identify overspending risks and opportunities for cost optimization.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Data-driven</span>
                    <span className="benefit-stat-label">Budget decisions</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Support business planning</h3>
                  <p>Professional budgeting and forecasting improve loan applications, investor presentations, and strategic planning.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Investor-ready</span>
                    <span className="benefit-stat-label">Financial plans</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently asked questions.</h2>
              <p className="intro">Everything you need to know about business budget templates and Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">What is a business budget template?</summary>
                  <div className="faq-a">
                    A business budget template is a pre-structured Excel spreadsheet that helps you plan, organize, and track business income and expenses. Formula Byte generates these templates automatically with built-in formulas, forecasting capabilities, and financial dashboards.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can this spreadsheet forecast business expenses automatically?</summary>
                  <div className="faq-a">
                    Yes. Formula Byte generates budget spreadsheets with automated forecasting formulas and financial calculations. The template can predict future income, expenses, and cash flow based on your historical data and growth assumptions.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include financial dashboards?</summary>
                  <div className="faq-a">
                    Yes. The spreadsheet includes budgeting dashboards, variance analysis, profit summaries, and cash flow visuals. All dashboards are generated automatically and update based on your budget data.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize budget categories?</summary>
                  <div className="faq-a">
                    Absolutely. Income categories, expense sections, forecasting layouts, and budgeting structures can all be customized. Describe your business model, and Formula Byte generates a tailored budget with the right categories and targets.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">
                    Yes. All Formula Byte budget templates work in both Microsoft Excel and Google Sheets. Generate once, export to your preferred platform, and all formulas and formatting remain intact.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for small business budgeting?</summary>
                  <div className="faq-a">
                    Yes. Small businesses commonly use budgeting spreadsheets to manage expenses, monitor financial performance, and forecast profitability. Formula Byte templates are designed specifically for small business needs and growth planning.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">What budgeting formulas are included?</summary>
                  <div className="faq-a">
                    Formula Byte includes SUM, IF, XLOOKUP, SUMIF, FORECAST, and SUBTOTAL formulas. These automate income totals, expense summaries, variance calculations, and cash flow forecasting — all wired together and ready to use.
                  </div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this business budget template free to use?</summary>
                  <div className="faq-a">
                    Yes. The business budget template is completely free to generate and use. Describe your budgeting workflow, generate the budget spreadsheet, and download it — no credit card or subscription required.
                  </div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Stop building budgets manually. <span className="accent">Start forecasting.</span></h2>
            <p>Generate your AI-powered business budget template in seconds — professional formulas, forecasting dashboards, and variance analysis included.</p>
            <div className="btn-row">
              <a href="/auth?template=business-budget" className="btn btn-primary btn-lg">Generate budget template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse more templates</a>
            </div>
          </div>
        </section>
      </div>

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}