export default function ContactListTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=management">Management</a>
            <span className="sep">/</span>
            <span className="current">Contact List</span>
          </div>

          <div className="eyebrow">Management template</div>
          <h1>AI Excel Contact List Template for Contact Management and <span className="accent">Organization</span></h1>
          <p className="lede">
            Organize names, phone numbers, email addresses, business details, and communication records with an AI-generated Excel contact list template designed for smarter contact management. Formula Byte helps individuals and businesses automate contact organization using intelligent spreadsheets with searchable records, categorization systems, and customizable contact tracking workflows.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>10</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>15 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate contact list spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Business contacts</span>
          <span className="use-case-pill"><span className="dot"></span>Customer management</span>
          <span className="use-case-pill"><span className="dot"></span>Client directories</span>
          <span className="use-case-pill"><span className="dot"></span>Networking databases</span>
          <span className="use-case-pill"><span className="dot"></span>Employee records</span>
          <span className="use-case-pill"><span className="dot"></span>Vendor lists</span>
          <span className="use-case-pill"><span className="dot"></span>Personal contacts</span>
          <span className="use-case-pill"><span className="dot"></span>Team communication management</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Contact-List<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">E5</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=IF</span>(<span className="num">D5</span><span className="op">=</span><span className="str">"Client"</span>, <span className="str">"High"</span>, <span className="str">"Normal"</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header preview-hide-mobile">F</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Name</div>
            <div className="preview-cell preview-header-cell">Email</div>
            <div className="preview-cell preview-header-cell">Phone</div>
            <div className="preview-cell preview-header-cell">Category</div>
            <div className="preview-cell preview-header-cell">Company</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Notes</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">Sarah Johnson</div>
            <div className="preview-cell">sarah.j@company.com</div>
            <div className="preview-cell">(555) 123-4567</div>
            <div className="preview-cell">Client</div>
            <div className="preview-cell">TechCorp Inc.</div>
            <div className="preview-cell text preview-hide-mobile">Project lead</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">Michael Chen</div>
            <div className="preview-cell">mchen@vendor.net</div>
            <div className="preview-cell">(555) 234-5678</div>
            <div className="preview-cell">Vendor</div>
            <div className="preview-cell">SupplyHub LLC</div>
            <div className="preview-cell text preview-hide-mobile">Main supplier</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">Emily Davis</div>
            <div className="preview-cell">emily.d@startup.io</div>
            <div className="preview-cell">(555) 345-6789</div>
            <div className="preview-cell selected">Networking</div>
            <div className="preview-cell">InnovateLab</div>
            <div className="preview-cell text preview-hide-mobile">Conference 2025</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">James Wilson</div>
            <div className="preview-cell">jwilson@agency.com</div>
            <div className="preview-cell">(555) 456-7890</div>
            <div className="preview-cell">Partner</div>
            <div className="preview-cell">Creative Agency</div>
            <div className="preview-cell text preview-hide-mobile">Design partner</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Lisa Anderson</div>
            <div className="preview-cell">lisa.a@team.org</div>
            <div className="preview-cell">(555) 567-8901</div>
            <div className="preview-cell">Employee</div>
            <div className="preview-cell">Our Company</div>
            <div className="preview-cell text preview-hide-mobile">HR Manager</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">Robert Taylor</div>
            <div className="preview-cell">rtaylor@invest.com</div>
            <div className="preview-cell">(555) 678-9012</div>
            <div className="preview-cell">Investor</div>
            <div className="preview-cell">Capital Ventures</div>
            <div className="preview-cell text preview-hide-mobile">Seed round</div>

            {/* Row 8 */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text">Jennifer Martinez</div>
            <div className="preview-cell">j.martinez@client.co</div>
            <div className="preview-cell">(555) 789-0123</div>
            <div className="preview-cell">Client</div>
            <div className="preview-cell">Global Solutions</div>
            <div className="preview-cell text preview-hide-mobile">Q4 contract</div>

            {/* Row 9 */}
            <div className="preview-row-num">9</div>
            <div className="preview-cell text faded">...</div>
            <div className="preview-cell faded">...</div>
            <div className="preview-cell faded">...</div>
            <div className="preview-cell faded">...</div>
            <div className="preview-cell faded">...</div>
            <div className="preview-cell faded preview-hide-mobile">...</div>

            {/* Row 10 - Total */}
            <div className="preview-row-num">10</div>
            <div className="preview-cell preview-header-cell">TOTAL CONTACTS</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-header-cell">247</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Records</div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Total Contacts:</span>
              <span className="val">247</span>
            </div>
            <div className="preview-status-item">
              <span>Clients:</span>
              <span className="val">85</span>
            </div>
            <div className="preview-status-item">
              <span>Vendors:</span>
              <span className="val">42</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">All Contacts</button>
              <button className="preview-tab">Clients</button>
              <button className="preview-tab">Vendors</button>
              <button className="preview-tab">Employees</button>
              <button className="preview-tab">+4</button>
            </div>
          </div>
        </div>
      </div>

      {/* CREATE AN AI CONTACT LIST SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Contact List Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the contact spreadsheet you need, and Formula Byte automatically generates a professional Excel contact list with:</p>
            </div>
            <div className="row-body">
              <ul className="bulleted">
                <li>Name organization</li>
                <li>Phone number tracking</li>
                <li>Email address management</li>
                <li>Address records</li>
                <li>Notes sections</li>
                <li>Contact categorization</li>
                <li>Communication tracking</li>
                <li>Searchable contact layouts</li>
                <li>Automated spreadsheet formatting</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing contact records, Formula Byte creates AI-powered contact management systems tailored to your workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel Contact List Template?</h2>
              <p className="intro">A structured spreadsheet used to organize and manage contact information in one centralized location.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel contact list template</strong> is a structured spreadsheet used to organize and manage contact information in one centralized location. It helps users store communication details, track relationships, and maintain organized records for personal or professional use.
              </p>
              <p>
                A contact list spreadsheet typically includes:
              </p>
              <ul className="bulleted">
                <li>Full names</li>
                <li>Phone numbers</li>
                <li>Email addresses</li>
                <li>Company details</li>
                <li>Physical addresses</li>
                <li>Job titles</li>
                <li>Notes sections</li>
                <li>Communication history</li>
                <li>Contact categories</li>
              </ul>
              <p>Formula Byte generates AI-powered contact management spreadsheets designed for organization, communication tracking, and relationship management.</p>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How Contact Management Works</h2>
              <p className="intro">Contact management is the process of organizing, updating, and maintaining communication records.</p>
            </div>
            <div className="row-body">
              <p>Contact management is the process of organizing, updating, and maintaining communication records for individuals, businesses, customers, vendors, or teams.</p>
              <p style={{marginTop: '18px'}}>A structured contact management system helps users:</p>
              <ul className="bulleted">
                <li>Store contact information efficiently</li>
                <li>Improve communication workflows</li>
                <li>Organize networking relationships</li>
                <li>Access contact records quickly</li>
                <li>Maintain updated communication details</li>
                <li>Track business and personal interactions</li>
              </ul>
              <p style={{marginTop: '18px'}}>Most contact management systems include:</p>
              <ul className="bulleted">
                <li>Contact databases</li>
                <li>Communication records</li>
                <li>Categorized contact groups</li>
                <li>Notes sections</li>
                <li>Follow-up reminders</li>
                <li>Search and filtering systems</li>
              </ul>
              <p style={{marginTop: '18px'}}>Formula Byte simplifies this process using AI-generated contact spreadsheets and intelligent organization systems.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY PEOPLE USE CONTACT LIST TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why People Use Contact List Templates</h2>
              <p className="intro">Managing contacts without a structured system often creates information chaos and communication gaps.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without a contact system</div>
                  <h3>Managing contacts without a structured system often creates:</h3>
                  <ul>
                    <li>Lost contact information</li>
                    <li>Duplicate records</li>
                    <li>Communication confusion</li>
                    <li>Unorganized networking data</li>
                    <li>Difficulty finding contact details</li>
                    <li>Outdated information</li>
                    <li>Poor follow-up management</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With a contact list</div>
                  <h3>A properly organized contact list helps users:</h3>
                  <ul>
                    <li>Maintain centralized records</li>
                    <li>Improve communication efficiency</li>
                    <li>Organize professional relationships</li>
                    <li>Manage customer information</li>
                    <li>Track networking opportunities</li>
                    <li>Simplify contact searches</li>
                    <li>Improve productivity</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI <span className="serif-accent">Contact</span> Spreadsheet</h2>
              <p className="intro">Four pillars of contact management — automatic, organized, and built to support real relationship tracking.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">C</div>
                  <h3>Contact Information Management</h3>
                  <p>Track all contact details with automatic organization and structured record-keeping.</p>
                  <ul>
                    <li>Full names</li>
                    <li>Mobile numbers</li>
                    <li>Email addresses</li>
                    <li>Company names</li>
                    <li>Job titles</li>
                    <li>Office locations</li>
                    <li>Website URLs</li>
                    <li>Social profiles</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>The spreadsheet automatically organizes communication records into structured layouts.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">G</div>
                  <h3>Contact Categorization</h3>
                  <p>Organize contacts into meaningful groups for better management and access.</p>
                  <ul>
                    <li>Business relationships</li>
                    <li>Clients</li>
                    <li>Vendors</li>
                    <li>Employees</li>
                    <li>Networking groups</li>
                    <li>Personal contacts</li>
                    <li>Departments</li>
                    <li>Industries</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Structured categorization improves communication management and record organization.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">N</div>
                  <h3>Notes and Follow-Up Tracking</h3>
                  <p>Formula Byte contact spreadsheets can include comprehensive relationship management tools.</p>
                  <ul>
                    <li>Follow-up reminders</li>
                    <li>Meeting notes</li>
                    <li>Relationship history</li>
                    <li>Communication summaries</li>
                    <li>Priority tags</li>
                    <li>Interaction tracking</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This improves networking organization and relationship management.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">S</div>
                  <h3>Search and Filtering Systems</h3>
                  <p>Monitor and organize contacts using intelligent search and organization systems.</p>
                  <ul>
                    <li>Searchable records</li>
                    <li>Dynamic filtering</li>
                    <li>Category sorting</li>
                    <li>Priority grouping</li>
                    <li>Department organization</li>
                    <li>Communication tracking dashboards</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This helps users access contact information more efficiently.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI CONTACT MANAGEMENT AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Contact Management Automation</h2>
              <p className="intro">Skip the manual setup. The AI understands contact management instructions from natural language prompts.</p>
            </div>
            <div className="row-body">
              <p>Traditional contact spreadsheets require manual formatting and repetitive data organization.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure contact databases</li>
                <li>Generate organization systems</li>
                <li>Create searchable layouts</li>
                <li>Build communication trackers</li>
                <li>Organize contact categories</li>
                <li>Generate follow-up systems</li>
                <li>Apply spreadsheet formatting</li>
                <li>Customize contact management workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands contact management instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a business contact management spreadsheet"</button>
                  <button className="chip">"Build a client directory with follow-up tracking"</button>
                  <button className="chip">"Generate a vendor contact database"</button>
                  <button className="chip">"Create a networking contact organizer"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Contact List Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete contact spreadsheet with 8 worksheets — each generated, formatted, and wired up automatically.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Contact Directory</span>
                  <span className="spec-purpose">Stores primary contact records</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Client List</span>
                  <span className="spec-purpose">Organizes customer information</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Vendor Database</span>
                  <span className="spec-purpose">Tracks supplier contacts</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Employee Directory</span>
                  <span className="spec-purpose">Manages team communication records</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Follow-Up Tracker</span>
                  <span className="spec-purpose">Monitors communication activities</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Networking Database</span>
                  <span className="spec-purpose">Organizes professional relationships</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Notes Section</span>
                  <span className="spec-purpose">Stores additional contact details</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Contact Dashboard</span>
                  <span className="spec-purpose">Visualizes communication data</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CONTACT CATEGORIES INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Contact categories</div>
              <h2>Contact Categories <span className="serif-accent">Included</span></h2>
              <p className="intro">Comprehensive categorization options organized for complete contact management.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">BC</div>
                  <h3>Business Contacts</h3>
                  <p>Track:</p>
                  <ul>
                    <li>Clients</li>
                    <li>Vendors</li>
                    <li>Team members</li>
                    <li>Business partners</li>
                    <li>Investors</li>
                    <li>Suppliers</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">PC</div>
                  <h3>Personal Contacts</h3>
                  <p>Manage:</p>
                  <ul>
                    <li>Family members</li>
                    <li>Friends</li>
                    <li>Emergency contacts</li>
                    <li>Community relationships</li>
                    <li>Personal networks</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">CRM</div>
                  <h3>Customer Relationship Management</h3>
                  <p>Monitor:</p>
                  <ul>
                    <li>Customer interactions</li>
                    <li>Follow-up schedules</li>
                    <li>Client communication history</li>
                    <li>Business opportunities</li>
                    <li>Networking activities</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">NC</div>
                  <h3>Networking Contacts</h3>
                  <p>Organize:</p>
                  <ul>
                    <li>Professional connections</li>
                    <li>Industry peers</li>
                    <li>Conference contacts</li>
                    <li>Alumni networks</li>
                    <li>Mentor relationships</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Under the hood</div>
              <h2>Built-In Excel Formulas and <span className="serif-accent">Contact</span> Automation</h2>
              <p className="intro">Every Formula Byte contact list template is wired up with intelligent organization and filtering functions.</p>
            </div>
            <div className="row-body">
              <div className="formula-grid">
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=VLOOKUP</span>(<span className="arg">lookup_value, table_array, col_index</span>)</div>
                  <div className="formula-desc">Search and retrieve contact information from the database.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=FILTER</span>(<span className="arg">range, criteria</span>)</div>
                  <div className="formula-desc">Dynamically filter contacts by category, company, or tags.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=COUNTIF</span>(<span className="arg">range, criteria</span>)</div>
                  <div className="formula-desc">Count contacts by category or analyze contact distribution.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">Conditional formatting</span></div>
                  <div className="formula-desc">Highlight priority contacts or outdated information.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">Data validation</span></div>
                  <div className="formula-desc">Dropdown menus for consistent category assignment.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">Contact sorting</span></div>
                  <div className="formula-desc">Automated organization by name, company, or category.</div>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>These spreadsheet automations improve contact management efficiency and reduce manual organization work.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Contact List Templates by <span className="serif-accent">Use Case</span></h2>
              <p className="intro">Customize the contact list for any management type — same structure, different focus.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">BC</div>
                    <div>
                      <h4>Business Contact Spreadsheet</h4>
                      <div className="industry-tagline">CLIENTS · VENDORS · TEAM</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Client information</li>
                    <li>Team communication</li>
                    <li>Vendor relationships</li>
                    <li>Company records</li>
                    <li>Networking contacts</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Ideal for small businesses and agencies.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">CM</div>
                    <div>
                      <h4>Client Contact Management Template</h4>
                      <div className="industry-tagline">CRM · SALES · SERVICE</div>
                    </div>
                  </div>
                  <p>Manage:</p>
                  <ul>
                    <li>Customer records</li>
                    <li>Follow-up activities</li>
                    <li>Communication history</li>
                    <li>Sales opportunities</li>
                    <li>Relationship tracking</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for consultants, agencies, and service providers.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">ED</div>
                    <div>
                      <h4>Employee Contact Directory</h4>
                      <div className="industry-tagline">INTERNAL · TEAM · HR</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Employee information</li>
                    <li>Department assignments</li>
                    <li>Internal communication records</li>
                    <li>Office contact details</li>
                    <li>Team organization</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Designed for internal business communication management.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">PO</div>
                    <div>
                      <h4>Personal Contact Organizer</h4>
                      <div className="industry-tagline">PERSONAL · FAMILY · SOCIAL</div>
                    </div>
                  </div>
                  <p>Monitor:</p>
                  <ul>
                    <li>Family contacts</li>
                    <li>Friend lists</li>
                    <li>Emergency contacts</li>
                    <li>Event planning contacts</li>
                    <li>Community communication</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for personal organization and networking.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CONTACT REPORTS AND COMMUNICATION INSIGHTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Contact Reports and Communication Insights</h2>
              <p className="intro">Every generated contact system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte contact spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Contact summaries</li>
                <li>Communication reports</li>
                <li>Networking organization dashboards</li>
                <li>Follow-up tracking reports</li>
                <li>Contact category analysis</li>
                <li>Relationship management insights</li>
                <li>Communication activity summaries</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into communication workflows and relationship management.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Contact Spreadsheet vs. <span className="serif-accent">Manual</span> Contact Management</h2>
              <p className="intro">Seven dimensions where AI-powered contact spreadsheets outperform manual contact management.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual Contact Management</div>
                  <h3>Manual contact organization</h3>
                  <ul>
                    <li>Often inconsistent</li>
                    <li>Limited functionality</li>
                    <li>Difficult to manage</li>
                    <li>Time-consuming</li>
                    <li>Manual categorization</li>
                    <li>Limited customization</li>
                    <li>Scattered records</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>AI-generated spreadsheets</h3>
                  <ul>
                    <li>Structured organization</li>
                    <li>Included search</li>
                    <li>Organized tracking</li>
                    <li>Fast setup</li>
                    <li>Automated categorization</li>
                    <li>High customization</li>
                    <li>Centralized database</li>
                  </ul>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify contact management and communication organization.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">Contact List</span> Templates</h2>
              <p className="intro">Faster setup, better organization, sharper management — every contact you need already tracked.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster Contact Organization</h3>
                  <p>Generate complete contact management systems instantly without manually formatting spreadsheets.</p>
                </div>
                <div className="benefit-card">
                  <h3>Better Communication Management</h3>
                  <p>Structured contact records improve networking and communication workflows.</p>
                </div>
                <div className="benefit-card">
                  <h3>Improved Data Organization</h3>
                  <p>Categorized contact systems help users maintain cleaner and more accessible records.</p>
                </div>
                <div className="benefit-card">
                  <h3>Reduced Information Loss</h3>
                  <p>Centralized contact databases help prevent missing or outdated communication details.</p>
                </div>
                <div className="benefit-card">
                  <h3>Easier Relationship Tracking</h3>
                  <p>Follow-up systems and notes sections improve customer and networking management.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing <span className="serif-accent">Contact</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated contact list into a real management tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Update Contact Information Regularly</h3>
                  <p>Consistent updates improve communication accuracy and data reliability.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Organize Contacts by Category</h3>
                  <p>Structured categories improve contact accessibility and workflow management.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Remove Duplicate Records</h3>
                  <p>Regular reviews help maintain cleaner and more organized communication databases.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Track Important Communication Notes</h3>
                  <p>Notes and reminders improve relationship management and follow-up consistency.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most contact list templates are static spreadsheets with limited flexibility.</p>
            </div>
            <div className="row-body">
              <p>Most contact list templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated contact management systems tailored to your communication workflow, relationship tracking needs, and organizational structure.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Contact databases</li>
                <li>Client directories</li>
                <li>Employee records</li>
                <li>Networking systems</li>
                <li>Communication trackers</li>
                <li>Follow-up management sheets</li>
                <li>Searchable contact dashboards</li>
                <li>AI-powered organization workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing contact records, Formula Byte automates contact spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This <span className="serif-accent">Contact</span> Spreadsheet?</h2>
              <p className="intro">This spreadsheet solution is ideal for professionals and individuals managing communication records.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>Agencies</h4></div>
                <div className="audience-cell"><h4>Consultants</h4></div>
                <div className="audience-cell"><h4>Freelancers</h4></div>
                <div className="audience-cell"><h4>Sales teams</h4></div>
                <div className="audience-cell"><h4>Recruiters</h4></div>
                <div className="audience-cell"><h4>Event organizers</h4></div>
                <div className="audience-cell"><h4>Professionals</h4></div>
                <div className="audience-cell"><h4>Personal networking users</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple contact organization or advanced communication tracking, Formula Byte helps automate contact spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating contact list templates with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet organize business and personal contacts?</summary>
                  <div className="faq-a">Yes. Formula Byte generates contact spreadsheets for both personal and professional contact management.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include follow-up tracking?</summary>
                  <div className="faq-a">Yes. The spreadsheet can include reminders, notes sections, and communication tracking systems.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize contact categories?</summary>
                  <div className="faq-a">Absolutely. Contact groups, labels, layouts, and communication sections can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte contact list templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for customer relationship management?</summary>
                  <div className="faq-a">Yes. Businesses commonly use contact spreadsheets to manage customer communication and networking relationships.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other management templates you might need.</h2>
              <p className="intro">Same engine, different management workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/invoice-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Invoice Template</h4>
                  <p>Professional invoices with auto-numbering, taxes, and totals.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/inventory-template/" className="related-card">
                  <div className="glyph">N</div>
                  <h4>Inventory Template</h4>
                  <p>Track stock levels, orders, and product management.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/calendar-template-2026/" className="related-card">
                  <div className="glyph">C</div>
                  <h4>Calendar Template</h4>
                  <p>Monthly planning, scheduling, and appointment tracking.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/to-do-list-template/" className="related-card">
                  <div className="glyph">T</div>
                  <h4>To-Do List Template</h4>
                  <p>Task management, priorities, and completion tracking.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">Contact Management</span> Spreadsheet?</h2>
            <p>Stop organizing contacts manually.</p>
            <p>Describe your communication workflow, and Formula Byte will generate a professional AI-powered Excel contact list template with searchable databases, follow-up tracking systems, communication dashboards, and organized relationship management workflows in seconds.</p>
            <p>Create smarter contact management spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}
