export default function CRMTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=management">Management</a>
            <span className="sep">/</span>
            <span className="current">CRM</span>
          </div>

          <div className="eyebrow">Management template</div>
          <h1>AI Excel CRM Template for Customer Relationship <span className="accent">Management</span></h1>
          <p className="lede">
            Manage customer information, sales interactions, follow-up activities, and business relationships with an AI-generated Excel CRM template designed for smarter customer management. Formula Byte helps businesses automate CRM workflows using intelligent spreadsheets with sales tracking systems, customer databases, communication logs, and performance dashboards.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>15</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate CRM spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Sales teams</span>
          <span className="use-case-pill"><span className="dot"></span>Agencies</span>
          <span className="use-case-pill"><span className="dot"></span>Consultants</span>
          <span className="use-case-pill"><span className="dot"></span>Freelancers</span>
          <span className="use-case-pill"><span className="dot"></span>Startups</span>
          <span className="use-case-pill"><span className="dot"></span>Customer support teams</span>
          <span className="use-case-pill"><span className="dot"></span>Client relationship management</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">CRM-System<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">H8</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=IF</span>(<span className="num">E8</span><span className="op">&gt;</span><span className="num">5000</span>, <span className="str">"Hot"</span>, <span className="str">"Warm"</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header">F</div>
            <div className="preview-col-header">G</div>
            <div className="preview-col-header preview-hide-mobile">H</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Customer</div>
            <div className="preview-cell preview-header-cell">Company</div>
            <div className="preview-cell preview-header-cell">Email</div>
            <div className="preview-cell preview-header-cell">Phone</div>
            <div className="preview-cell preview-header-cell">Stage</div>
            <div className="preview-cell preview-header-cell">Value</div>
            <div className="preview-cell preview-header-cell">Probability</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Next Action</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">TechCorp Inc.</div>
            <div className="preview-cell">Sarah Johnson</div>
            <div className="preview-cell">sarah@techcorp.com</div>
            <div className="preview-cell">(555) 123-4567</div>
            <div className="preview-cell">Proposal</div>
            <div className="preview-cell">$25,000</div>
            <div className="preview-cell">75%</div>
            <div className="preview-cell text preview-hide-mobile">Follow up call</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">Global Solutions</div>
            <div className="preview-cell">Michael Chen</div>
            <div className="preview-cell">m.chen@global.co</div>
            <div className="preview-cell">(555) 234-5678</div>
            <div className="preview-cell selected">Negotiation</div>
            <div className="preview-cell">$45,000</div>
            <div className="preview-cell">90%</div>
            <div className="preview-cell text preview-hide-mobile">Send contract</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">InnovateLab</div>
            <div className="preview-cell">Emily Davis</div>
            <div className="preview-cell">emily@innovate.io</div>
            <div className="preview-cell">(555) 345-6789</div>
            <div className="preview-cell">Discovery</div>
            <div className="preview-cell">$15,000</div>
            <div className="preview-cell">40%</div>
            <div className="preview-cell text preview-hide-mobile">Demo scheduled</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">Prime Agency</div>
            <div className="preview-cell">James Wilson</div>
            <div className="preview-cell">james@prime.com</div>
            <div className="preview-cell">(555) 456-7890</div>
            <div className="preview-cell">Qualified</div>
            <div className="preview-cell">$35,000</div>
            <div className="preview-cell">60%</div>
            <div className="preview-cell text preview-hide-mobile">Meeting set</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Capital Ventures</div>
            <div className="preview-cell">Lisa Anderson</div>
            <div className="preview-cell">lisa@capvent.com</div>
            <div className="preview-cell">(555) 567-8901</div>
            <div className="preview-cell">Closed Won</div>
            <div className="preview-cell">$50,000</div>
            <div className="preview-cell">100%</div>
            <div className="preview-cell text preview-hide-mobile">Onboarding</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">MegaCorp Ltd.</div>
            <div className="preview-cell">Robert Taylor</div>
            <div className="preview-cell">rtaylor@mega.net</div>
            <div className="preview-cell">(555) 678-9012</div>
            <div className="preview-cell">Prospecting</div>
            <div className="preview-cell">$60,000</div>
            <div className="preview-cell">20%</div>
            <div className="preview-cell text preview-hide-mobile">Initial contact</div>

            {/* Row 8 - Summary */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell preview-header-cell">PIPELINE TOTAL</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-header-cell">$230,000</div>
            <div className="preview-cell preview-header-cell">57% avg</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">7 active</div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Total Pipeline:</span>
              <span className="val">$230K</span>
            </div>
            <div className="preview-status-item">
              <span>Closed Won:</span>
              <span className="val">$50K</span>
            </div>
            <div className="preview-status-item">
              <span>Active Deals:</span>
              <span className="val">6</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">Pipeline</button>
              <button className="preview-tab">Customers</button>
              <button className="preview-tab">Follow-ups</button>
              <button className="preview-tab">Dashboard</button>
              <button className="preview-tab">+4</button>
            </div>
          </div>
        </div>
      </div>

      {/* CREATE AN AI CRM SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI CRM Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the CRM spreadsheet you need, and Formula Byte automatically generates a professional Excel CRM system with:</p>
            </div>
            <div className="row-body">
              <ul className="bulleted">
                <li>Customer databases</li>
                <li>Sales interaction tracking</li>
                <li>Lead management</li>
                <li>Follow-up reminders</li>
                <li>Sales pipeline monitoring</li>
                <li>Customer communication logs</li>
                <li>Performance dashboards</li>
                <li>Automated spreadsheet formulas</li>
                <li>Relationship management workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing customer records, Formula Byte creates AI-powered CRM systems tailored to your sales and communication workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel CRM Template?</h2>
              <p className="intro">A structured spreadsheet used to organize customer information, track sales activities, and manage follow-ups.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel CRM template</strong> is a structured spreadsheet used to organize customer information, track sales activities, manage follow-ups, and improve customer relationship management workflows.
              </p>
              <p>
                A CRM spreadsheet typically includes:
              </p>
              <ul className="bulleted">
                <li>Customer information</li>
                <li>Contact records</li>
                <li>Sales pipelines</li>
                <li>Communication history</li>
                <li>Follow-up tracking</li>
                <li>Lead management</li>
                <li>Sales forecasting</li>
                <li>Customer notes</li>
                <li>Performance reports</li>
              </ul>
              <p>Formula Byte generates AI-powered CRM spreadsheets designed for sales organization, customer management, and business growth workflows.</p>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How CRM Systems Work</h2>
              <p className="intro">Customer relationship management is the process of organizing customer data and tracking interactions.</p>
            </div>
            <div className="row-body">
              <p>Customer relationship management (CRM) is the process of organizing customer data, tracking interactions, and managing communication throughout the sales lifecycle.</p>
              <p style={{marginTop: '18px'}}>A structured CRM system helps businesses:</p>
              <ul className="bulleted">
                <li>Store customer information</li>
                <li>Track sales activities</li>
                <li>Monitor lead progress</li>
                <li>Improve follow-up consistency</li>
                <li>Strengthen customer relationships</li>
                <li>Increase sales efficiency</li>
                <li>Organize communication workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Most CRM systems include:</p>
              <ul className="bulleted">
                <li>Customer databases</li>
                <li>Sales tracking</li>
                <li>Lead pipelines</li>
                <li>Follow-up systems</li>
                <li>Interaction history</li>
                <li>Performance reporting</li>
                <li>Customer segmentation</li>
              </ul>
              <p style={{marginTop: '18px'}}>Formula Byte simplifies this process with AI-generated CRM spreadsheets and automated relationship management systems.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY BUSINESSES NEED CRM SYSTEMS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Businesses Need CRM Systems</h2>
              <p className="intro">Managing customer relationships without a structured CRM system often creates sales gaps and communication issues.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without a CRM system</div>
                  <h3>Managing customer relationships without a structured CRM system often creates:</h3>
                  <ul>
                    <li>Lost customer information</li>
                    <li>Missed follow-ups</li>
                    <li>Disorganized sales tracking</li>
                    <li>Communication gaps</li>
                    <li>Poor lead management</li>
                    <li>Limited customer visibility</li>
                    <li>Inconsistent sales processes</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With a CRM system</div>
                  <h3>A properly organized CRM spreadsheet helps businesses:</h3>
                  <ul>
                    <li>Improve customer communication</li>
                    <li>Organize sales activities</li>
                    <li>Track client relationships</li>
                    <li>Monitor sales opportunities</li>
                    <li>Increase productivity</li>
                    <li>Improve customer retention</li>
                    <li>Maintain centralized records</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI <span className="serif-accent">CRM</span> Spreadsheet</h2>
              <p className="intro">Four pillars of customer relationship management — automatic, organized, and built to support real sales growth.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">C</div>
                  <h3>Customer Information Management</h3>
                  <p>Track all customer details with automatic organization and structured database layouts.</p>
                  <ul>
                    <li>Customer names</li>
                    <li>Contact details</li>
                    <li>Company information</li>
                    <li>Job titles</li>
                    <li>Email addresses</li>
                    <li>Phone numbers</li>
                    <li>Business locations</li>
                    <li>Customer categories</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>The spreadsheet automatically organizes customer records into structured CRM layouts.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">S</div>
                  <h3>Sales Interaction Tracking</h3>
                  <p>Monitor all customer engagements with organized communication tracking systems.</p>
                  <ul>
                    <li>Calls</li>
                    <li>Emails</li>
                    <li>Meetings</li>
                    <li>Sales discussions</li>
                    <li>Customer inquiries</li>
                    <li>Support interactions</li>
                    <li>Communication history</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This helps businesses maintain organized customer engagement records.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">F</div>
                  <h3>Follow-Up and Task Management</h3>
                  <p>Formula Byte CRM spreadsheets can include comprehensive task and reminder systems.</p>
                  <ul>
                    <li>Follow-up reminders</li>
                    <li>Task deadlines</li>
                    <li>Meeting schedules</li>
                    <li>Communication tracking</li>
                    <li>Sales activity logs</li>
                    <li>Customer engagement notes</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Structured follow-up systems improve customer relationship consistency and sales organization.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">P</div>
                  <h3>Sales Pipeline Tracking</h3>
                  <p>Track sales opportunities with comprehensive pipeline management and forecasting.</p>
                  <ul>
                    <li>Leads</li>
                    <li>Opportunities</li>
                    <li>Deal stages</li>
                    <li>Potential revenue</li>
                    <li>Conversion progress</li>
                    <li>Customer lifecycle stages</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This improves visibility into sales performance and lead management.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI CRM AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI CRM Automation for Sales and Relationship Management</h2>
              <p className="intro">Skip the manual setup. The AI understands CRM instructions from natural language prompts.</p>
            </div>
            <div className="row-body">
              <p>Traditional CRM spreadsheets require manual setup and repetitive data management.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure CRM databases</li>
                <li>Generate customer tracking systems</li>
                <li>Organize sales pipelines</li>
                <li>Create follow-up workflows</li>
                <li>Build CRM dashboards</li>
                <li>Generate reporting summaries</li>
                <li>Apply spreadsheet formatting</li>
                <li>Automate customer management workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands CRM instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a sales CRM spreadsheet with lead tracking"</button>
                  <button className="chip">"Build a client relationship management dashboard"</button>
                  <button className="chip">"Generate a customer follow-up system"</button>
                  <button className="chip">"Create a sales pipeline tracker for my agency"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>CRM Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete CRM spreadsheet with 8 worksheets — each generated, formatted, and wired up automatically.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Customer Database</span>
                  <span className="spec-purpose">Stores customer information</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Lead Tracker</span>
                  <span className="spec-purpose">Monitors sales opportunities</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Sales Pipeline</span>
                  <span className="spec-purpose">Tracks deal progress</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Follow-Up Manager</span>
                  <span className="spec-purpose">Organizes reminders and tasks</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Communication Log</span>
                  <span className="spec-purpose">Stores customer interactions</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Sales Dashboard</span>
                  <span className="spec-purpose">Visualizes CRM performance</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Customer Notes Sheet</span>
                  <span className="spec-purpose">Tracks relationship history</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Revenue Forecast</span>
                  <span className="spec-purpose">Estimates sales growth</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CRM CATEGORIES INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">CRM categories</div>
              <h2>CRM Categories <span className="serif-accent">Included</span></h2>
              <p className="intro">Comprehensive customer relationship management categories organized for complete CRM workflows.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">CM</div>
                  <h3>Customer Management</h3>
                  <p>Track:</p>
                  <ul>
                    <li>Clients</li>
                    <li>Leads</li>
                    <li>Vendors</li>
                    <li>Prospects</li>
                    <li>Existing customers</li>
                    <li>Business relationships</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">ST</div>
                  <h3>Sales Tracking</h3>
                  <p>Monitor:</p>
                  <ul>
                    <li>Sales stages</li>
                    <li>Customer inquiries</li>
                    <li>Revenue opportunities</li>
                    <li>Conversion rates</li>
                    <li>Lead status</li>
                    <li>Follow-up schedules</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">RM</div>
                  <h3>Relationship Management</h3>
                  <p>Manage:</p>
                  <ul>
                    <li>Customer communication</li>
                    <li>Follow-up activities</li>
                    <li>Client engagement</li>
                    <li>Meeting notes</li>
                    <li>Relationship history</li>
                    <li>Customer priorities</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">LM</div>
                  <h3>Lead Management</h3>
                  <p>Organize:</p>
                  <ul>
                    <li>Lead sources</li>
                    <li>Qualification status</li>
                    <li>Conversion tracking</li>
                    <li>Pipeline stages</li>
                    <li>Lead scoring</li>
                    <li>Follow-up automation</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Under the hood</div>
              <h2>Built-In Excel Formulas and <span className="serif-accent">CRM</span> Automation</h2>
              <p className="intro">Every Formula Byte CRM template is wired up with intelligent sales tracking and automation functions.</p>
            </div>
            <div className="row-body">
              <div className="formula-grid">
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=SUMIF</span>(<span className="arg">range, criteria, sum_range</span>)</div>
                  <div className="formula-desc">Calculate total pipeline value by sales stage or category.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=COUNTIF</span>(<span className="arg">range, criteria</span>)</div>
                  <div className="formula-desc">Count leads, opportunities, or customers by stage or status.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=AVERAGEIF</span>(<span className="arg">range, criteria, average_range</span>)</div>
                  <div className="formula-desc">Calculate average deal size or conversion rates.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">Conditional formatting</span></div>
                  <div className="formula-desc">Highlight high-value opportunities, urgent follow-ups, or stalled deals.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">Follow-up reminders</span></div>
                  <div className="formula-desc">Automated alerts based on dates, deal stages, or customer activities.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">CRM reporting</span></div>
                  <div className="formula-desc">Dashboard automation for sales performance and customer insights.</div>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>These spreadsheet automations improve CRM organization and reduce manual management work.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>CRM Templates by <span className="serif-accent">Business</span> Type</h2>
              <p className="intro">Customize the CRM for any business type — same structure, different focus.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">SB</div>
                    <div>
                      <h4>Small Business CRM Spreadsheet</h4>
                      <div className="industry-tagline">STARTUP · RETAIL · SERVICE</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Customer records</li>
                    <li>Sales opportunities</li>
                    <li>Follow-up activities</li>
                    <li>Revenue growth</li>
                    <li>Client communication</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Ideal for startups and small businesses.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">ST</div>
                    <div>
                      <h4>Sales CRM Template</h4>
                      <div className="industry-tagline">B2B · SALES · TEAMS</div>
                    </div>
                  </div>
                  <p>Manage:</p>
                  <ul>
                    <li>Leads</li>
                    <li>Sales pipelines</li>
                    <li>Customer interactions</li>
                    <li>Conversion tracking</li>
                    <li>Deal management</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for sales teams and agencies.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">FC</div>
                    <div>
                      <h4>Freelancer Client Management Spreadsheet</h4>
                      <div className="industry-tagline">CONSULTANTS · FREELANCERS</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Client projects</li>
                    <li>Communication history</li>
                    <li>Payment follow-ups</li>
                    <li>Business relationships</li>
                    <li>Service inquiries</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Designed for consultants and freelancers.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">AC</div>
                    <div>
                      <h4>Agency CRM Dashboard</h4>
                      <div className="industry-tagline">MARKETING · CREATIVE · SERVICE</div>
                    </div>
                  </div>
                  <p>Monitor:</p>
                  <ul>
                    <li>Client accounts</li>
                    <li>Team communication</li>
                    <li>Project pipelines</li>
                    <li>Customer engagement</li>
                    <li>Sales performance</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for marketing agencies and service businesses.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CRM REPORTS AND SALES INSIGHTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>CRM Reports and Sales Insights</h2>
              <p className="intro">Every generated CRM system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte CRM spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Customer engagement reports</li>
                <li>Sales pipeline summaries</li>
                <li>Lead tracking reports</li>
                <li>Revenue forecasting dashboards</li>
                <li>Follow-up activity reports</li>
                <li>Conversion analysis</li>
                <li>Communication summaries</li>
                <li>Customer performance insights</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into customer relationships and sales performance.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel CRM Spreadsheet vs. <span className="serif-accent">Manual</span> Customer Tracking</h2>
              <p className="intro">Seven dimensions where AI-powered CRM spreadsheets outperform manual customer tracking.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual Customer Tracking</div>
                  <h3>Manual customer organization</h3>
                  <ul>
                    <li>Often scattered</li>
                    <li>Manual tracking</li>
                    <li>Limited visibility</li>
                    <li>Time-consuming</li>
                    <li>Difficult to track</li>
                    <li>Limited customization</li>
                    <li>Inconsistent records</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>AI-generated spreadsheets</h3>
                  <ul>
                    <li>Structured organization</li>
                    <li>Automated tracking</li>
                    <li>Dashboard-based</li>
                    <li>Fast setup</li>
                    <li>Organized management</li>
                    <li>High customization</li>
                    <li>Centralized records</li>
                  </ul>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify CRM management and customer organization.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">CRM</span> Templates</h2>
              <p className="intro">Faster setup, better organization, sharper sales tracking — every customer relationship already managed.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster CRM Setup</h3>
                  <p>Generate complete CRM systems instantly without manually building spreadsheets.</p>
                </div>
                <div className="benefit-card">
                  <h3>Better Customer Organization</h3>
                  <p>Structured customer databases improve relationship management and communication tracking.</p>
                </div>
                <div className="benefit-card">
                  <h3>Improved Follow-Up Management</h3>
                  <p>Automated reminders and tracking systems help businesses maintain consistent customer engagement.</p>
                </div>
                <div className="benefit-card">
                  <h3>Increased Sales Visibility</h3>
                  <p>CRM dashboards improve visibility into sales pipelines, opportunities, and customer interactions.</p>
                </div>
                <div className="benefit-card">
                  <h3>Smarter Relationship Management</h3>
                  <p>Organized CRM workflows help businesses strengthen customer relationships and improve retention.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing <span className="serif-accent">CRM</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated CRM into a real sales management tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Update Customer Information Regularly</h3>
                  <p>Consistent updates improve communication accuracy and customer management reliability.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Track Every Sales Interaction</h3>
                  <p>Maintaining communication history improves follow-up consistency and relationship visibility.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Review Sales Pipelines Frequently</h3>
                  <p>Regular CRM reviews help identify:</p>
                  <ul>
                    <li>Lead opportunities</li>
                    <li>Customer engagement trends</li>
                    <li>Sales bottlenecks</li>
                    <li>Follow-up priorities</li>
                    <li>Revenue growth potential</li>
                  </ul>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Organize Customers by Category</h3>
                  <p>Structured segmentation improves customer tracking and communication workflows.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most CRM templates are static spreadsheets with limited flexibility.</p>
            </div>
            <div className="row-body">
              <p>Most CRM templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated CRM systems tailored to your customer management workflow, sales process, and communication structure.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Customer databases</li>
                <li>Sales pipelines</li>
                <li>Lead tracking systems</li>
                <li>CRM dashboards</li>
                <li>Follow-up managers</li>
                <li>Revenue forecasting sheets</li>
                <li>Communication trackers</li>
                <li>AI-powered CRM workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually managing customer records, Formula Byte automates CRM spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This <span className="serif-accent">CRM</span> Spreadsheet?</h2>
              <p className="intro">This spreadsheet solution is ideal for businesses and professionals managing customer relationships.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>Sales teams</h4></div>
                <div className="audience-cell"><h4>Agencies</h4></div>
                <div className="audience-cell"><h4>Consultants</h4></div>
                <div className="audience-cell"><h4>Freelancers</h4></div>
                <div className="audience-cell"><h4>Startup founders</h4></div>
                <div className="audience-cell"><h4>Customer support teams</h4></div>
                <div className="audience-cell"><h4>Service providers</h4></div>
                <div className="audience-cell"><h4>Relationship managers</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple customer tracking or advanced CRM workflows, Formula Byte helps automate CRM spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating CRM templates with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet track customer interactions automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates CRM spreadsheets with communication tracking, sales pipelines, and follow-up systems.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include sales pipeline tracking?</summary>
                  <div className="faq-a">Yes. CRM templates can include lead stages, sales forecasting, and deal tracking dashboards.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize customer categories and workflows?</summary>
                  <div className="faq-a">Absolutely. Customer groups, sales stages, follow-up systems, and CRM layouts can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte CRM templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for small business CRM management?</summary>
                  <div className="faq-a">Yes. Small businesses commonly use CRM spreadsheets to organize customer communication, sales tracking, and relationship management.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other management templates you might need.</h2>
              <p className="intro">Same engine, different management workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/contact-list-template/" className="related-card">
                  <div className="glyph">C</div>
                  <h4>Contact List</h4>
                  <p>Organize contacts, track communication, and manage relationships.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/invoice-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Invoice Template</h4>
                  <p>Professional invoices with auto-numbering, taxes, and totals.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/sales-tracker-template/" className="related-card">
                  <div className="glyph">S</div>
                  <h4>Sales Tracker</h4>
                  <p>Monitor sales performance, targets, and revenue growth.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/calendar-template-2026/" className="related-card">
                  <div className="glyph">D</div>
                  <h4>Calendar Template</h4>
                  <p>Monthly planning, scheduling, and appointment tracking.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">CRM</span> Spreadsheet?</h2>
            <p>Stop managing customer data manually.</p>
            <p>Describe your CRM workflow, and Formula Byte will generate a professional AI-powered Excel CRM template with customer databases, sales tracking systems, follow-up workflows, CRM dashboards, and organized relationship management tools in seconds.</p>
            <p>Create smarter CRM spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}
