export default function ExpenseReportTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=finance">Finance</a>
            <span className="sep">/</span>
            <span className="current">Expense Report</span>
          </div>

          <div className="eyebrow">Finance template</div>
          <h1>AI Excel Expense Report Template for Expense Tracking and <span className="accent">Financial Reporting</span></h1>
          <p className="lede">
            Track business expenses, reimbursements, receipts, and spending categories with an AI-generated Excel expense report template designed for smarter financial organization. Formula Byte helps individuals and businesses automate expense tracking using intelligent spreadsheets with categorized reporting systems, expense summaries, approval workflows, and financial dashboards.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>7</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>12</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>15 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate expense report spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Employee reimbursements</span>
          <span className="use-case-pill"><span className="dot"></span>Business travel expenses</span>
          <span className="use-case-pill"><span className="dot"></span>Freelancers</span>
          <span className="use-case-pill"><span className="dot"></span>Operational spending</span>
          <span className="use-case-pill"><span className="dot"></span>Personal expense tracking</span>
          <span className="use-case-pill"><span className="dot"></span>Corporate finance teams</span>
          <span className="use-case-pill"><span className="dot"></span>Budget management</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Expense-Report-Tracker<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">G8</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=SUM</span>(<span className="num">G2:G7</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header">F</div>
            <div className="preview-col-header">G</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Date</div>
            <div className="preview-cell preview-header-cell">Category</div>
            <div className="preview-cell preview-header-cell">Description</div>
            <div className="preview-cell preview-header-cell">Vendor</div>
            <div className="preview-cell preview-header-cell">Payment Method</div>
            <div className="preview-cell preview-header-cell">Receipt #</div>
            <div className="preview-cell preview-header-cell">Amount</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell">01/15/26</div>
            <div className="preview-cell text">Travel</div>
            <div className="preview-cell text">Flight to NYC</div>
            <div className="preview-cell">Delta Airlines</div>
            <div className="preview-cell">Credit Card</div>
            <div className="preview-cell">R-1024</div>
            <div className="preview-cell num">$345.00</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell">01/16/26</div>
            <div className="preview-cell text selected">Meals</div>
            <div className="preview-cell text">Client dinner</div>
            <div className="preview-cell">Steakhouse</div>
            <div className="preview-cell">Credit Card</div>
            <div className="preview-cell">R-1025</div>
            <div className="preview-cell num">$128.50</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell">01/16/26</div>
            <div className="preview-cell text">Office Supplies</div>
            <div className="preview-cell text">Printer paper & ink</div>
            <div className="preview-cell">Office Depot</div>
            <div className="preview-cell">Company Card</div>
            <div className="preview-cell">R-1026</div>
            <div className="preview-cell num">$67.25</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell">01/17/26</div>
            <div className="preview-cell text">Software</div>
            <div className="preview-cell text">Adobe subscription</div>
            <div className="preview-cell">Adobe Inc.</div>
            <div className="preview-cell">Credit Card</div>
            <div className="preview-cell">R-1027</div>
            <div className="preview-cell num">$54.99</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell">01/18/26</div>
            <div className="preview-cell text">Transportation</div>
            <div className="preview-cell text">Uber to meeting</div>
            <div className="preview-cell">Uber</div>
            <div className="preview-cell">Credit Card</div>
            <div className="preview-cell">R-1028</div>
            <div className="preview-cell num">$24.50</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell">01/19/26</div>
            <div className="preview-cell text">Meals</div>
            <div className="preview-cell text">Team lunch</div>
            <div className="preview-cell">Local Cafe</div>
            <div className="preview-cell">Cash</div>
            <div className="preview-cell">R-1029</div>
            <div className="preview-cell num">$45.00</div>

            {/* Row 8 - Summary */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell preview-header-cell">MONTHLY TOTAL</div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell"></div>
            <div className="preview-cell preview-header-cell">$665.24</div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Total Expenses:</span>
              <span className="val">$665.24</span>
            </div>
            <div className="preview-status-item">
              <span>Reimbursable:</span>
              <span className="val">$543.49</span>
            </div>
            <div className="preview-status-item">
              <span>Pending:</span>
              <span className="val">0</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">Expenses</button>
              <button className="preview-tab">Categories</button>
              <button className="preview-tab">Receipts</button>
              <button className="preview-tab">Reimbursements</button>
              <button className="preview-tab">+3</button>
            </div>
          </div>
        </div>
      </div>

      {/* CREATE AN AI EXPENSE REPORT SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Expense Report Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the expense tracking spreadsheet you need, and Formula Byte automatically generates a professional Excel expense report template with:</p>
            </div>
            <div className="row-body">
              <ul className="bulleted">
                <li>Expense categorization</li>
                <li>Receipt tracking</li>
                <li>Reimbursement reporting</li>
                <li>Cost summaries</li>
                <li>Budget monitoring</li>
                <li>Expense approval workflows</li>
                <li>Financial dashboards</li>
                <li>Automated spreadsheet formulas</li>
                <li>Spending analysis systems</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually tracking expenses, Formula Byte creates AI-powered expense reporting systems tailored to your financial workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel Expense Report Template?</h2>
              <p className="intro">A structured spreadsheet used to organize, categorize, and monitor expenses incurred during a specific period.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel expense report template</strong> is a structured spreadsheet used to organize, categorize, and monitor expenses incurred during a specific period. It helps individuals and businesses maintain accurate spending records while improving budgeting and financial reporting.
              </p>
              <p>
                An expense report spreadsheet typically includes:
              </p>
              <ul className="bulleted">
                <li>Expense dates</li>
                <li>Spending categories</li>
                <li>Expense descriptions</li>
                <li>Payment methods</li>
                <li>Receipt references</li>
                <li>Expense totals</li>
                <li>Reimbursement tracking</li>
                <li>Budget summaries</li>
                <li>Financial reports</li>
              </ul>
              <p>Formula Byte generates AI-powered expense tracking spreadsheets designed for expense management and financial reporting workflows.</p>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How Expense Reporting Works</h2>
              <p className="intro">Expense reporting is the process of recording and organizing spending activity for budgeting, reimbursement, tax preparation, and financial analysis.</p>
            </div>
            <div className="row-body">
              <p>Expense reporting is the process of recording and organizing spending activity for budgeting, reimbursement, tax preparation, and financial analysis.</p>
              <p style={{marginTop: '18px'}}>A structured expense management system helps users:</p>
              <ul className="bulleted">
                <li>Monitor spending habits</li>
                <li>Organize expense records</li>
                <li>Improve budgeting visibility</li>
                <li>Track reimbursements</li>
                <li>Simplify tax preparation</li>
                <li>Analyze operational costs</li>
                <li>Maintain accurate financial documentation</li>
              </ul>
              <p style={{marginTop: '18px'}}>Most expense tracking systems include:</p>
              <ul className="bulleted">
                <li>Expense categories</li>
                <li>Cost summaries</li>
                <li>Receipt management</li>
                <li>Spending reports</li>
                <li>Budget tracking</li>
                <li>Reimbursement workflows</li>
                <li>Financial dashboards</li>
              </ul>
              <p style={{marginTop: '18px'}}>Formula Byte simplifies this process using AI-generated expense reporting spreadsheets and automated financial tracking systems.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY BUSINESSES NEED EXPENSE REPORTING */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Businesses Need Expense Reporting Systems</h2>
              <p className="intro">Managing expenses without a structured system often creates financial gaps and reporting issues.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without expense reporting</div>
                  <h3>Managing expenses without a structured system often creates:</h3>
                  <ul>
                    <li>Missing receipts</li>
                    <li>Unorganized spending records</li>
                    <li>Budget overruns</li>
                    <li>Reimbursement delays</li>
                    <li>Expense calculation errors</li>
                    <li>Poor financial visibility</li>
                    <li>Tax reporting difficulties</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With expense reporting</div>
                  <h3>A properly organized expense report helps businesses:</h3>
                  <ul>
                    <li>Improve financial organization</li>
                    <li>Monitor operational spending</li>
                    <li>Simplify reimbursement tracking</li>
                    <li>Prepare for tax reporting</li>
                    <li>Reduce accounting errors</li>
                    <li>Improve budget control</li>
                    <li>Analyze business expenses more effectively</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI <span className="serif-accent">Expense Report</span> Spreadsheet</h2>
              <p className="intro">Four pillars of expense management — automatic, organized, and built to support real financial tracking needs.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">E</div>
                  <h3>Expense Tracking and Categorization</h3>
                  <p>Track all business spending with automatic organization and structured category layouts.</p>
                  <ul>
                    <li>Travel expenses</li>
                    <li>Meals and entertainment</li>
                    <li>Office supplies</li>
                    <li>Transportation costs</li>
                    <li>Software subscriptions</li>
                    <li>Operational spending</li>
                    <li>Business purchases</li>
                    <li>Client-related expenses</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>The spreadsheet automatically organizes spending records into structured categories.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">R</div>
                  <h3>Receipt and Documentation Management</h3>
                  <p>Monitor all expense documentation with organized receipt tracking systems.</p>
                  <ul>
                    <li>Receipt references</li>
                    <li>Purchase documentation</li>
                    <li>Expense verification</li>
                    <li>Reimbursement records</li>
                    <li>Vendor information</li>
                    <li>Payment details</li>
                    <li>Receipt status tracking</li>
                    <li>Documentation compliance</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This improves financial transparency and reporting accuracy.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">B</div>
                  <h3>Budget and Spending Monitoring</h3>
                  <p>Formula Byte expense report spreadsheets can include comprehensive budget tracking systems.</p>
                  <ul>
                    <li>Budget tracking dashboards</li>
                    <li>Spending summaries</li>
                    <li>Expense comparisons</li>
                    <li>Department cost analysis</li>
                    <li>Financial overviews</li>
                    <li>Operational spending reports</li>
                    <li>Variance tracking</li>
                    <li>Budget alerts</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Structured reporting improves budgeting visibility and cost management.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">P</div>
                  <h3>Reimbursement Tracking</h3>
                  <p>Track employee reimbursements with comprehensive approval and payment workflows.</p>
                  <ul>
                    <li>Employee reimbursements</li>
                    <li>Approved expenses</li>
                    <li>Pending claims</li>
                    <li>Payment status</li>
                    <li>Expense approvals</li>
                    <li>Reimbursement history</li>
                    <li>Claim deadlines</li>
                    <li>Payment tracking</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This helps businesses maintain organized reimbursement workflows and financial accountability.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI EXPENSE REPORTING AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Expense Reporting Automation for Financial Management</h2>
              <p className="intro">Skip the manual setup. The AI understands expense reporting instructions from natural language prompts.</p>
            </div>
            <div className="row-body">
              <p>Traditional expense spreadsheets require manual formatting and repetitive data entry.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure expense tracking systems</li>
                <li>Generate reporting workflows</li>
                <li>Organize spending categories</li>
                <li>Create reimbursement dashboards</li>
                <li>Build budget summaries</li>
                <li>Generate financial reports</li>
                <li>Apply spreadsheet formatting</li>
                <li>Automate expense management workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands expense reporting instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a monthly business expense tracker"</button>
                  <button className="chip">"Build an employee reimbursement spreadsheet"</button>
                  <button className="chip">"Generate a travel expense reporting dashboard"</button>
                  <button className="chip">"Create a categorized spending analysis template"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Expense Report Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete expense reporting spreadsheet with 7 worksheets — each generated, formatted, and wired up automatically.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Expense Tracker</span>
                  <span className="spec-purpose">Records daily expenses</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Spending Categories</span>
                  <span className="spec-purpose">Organizes expense types</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Receipt Log</span>
                  <span className="spec-purpose">Tracks purchase documentation</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Reimbursement Sheet</span>
                  <span className="spec-purpose">Monitors expense claims</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Budget Dashboard</span>
                  <span className="spec-purpose">Visualizes spending activity</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Financial Summary</span>
                  <span className="spec-purpose">Generates expense reports</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Approval Workflow</span>
                  <span className="spec-purpose">Tracks reimbursement approvals</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* EXPENSE CATEGORIES INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Data included</div>
              <h2>Expense <span className="serif-accent">Categories</span> Included</h2>
              <p className="intro">Every expense category you need — pre-built, organized, and ready for instant spending tracking.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte expense report spreadsheets include comprehensive spending categories:</p>
              <ul className="bulleted">
                <li><strong>Business Expenses:</strong> Office supplies, marketing costs, software subscriptions, utilities, operational purchases, vendor payments</li>
                <li><strong>Travel and Transportation Expenses:</strong> Flights, hotel bookings, transportation, fuel costs, meal expenses, business travel spending</li>
                <li><strong>Employee Reimbursement Tracking:</strong> Staff expense claims, approved reimbursements, pending payments, expense approval history, department expenses</li>
                <li><strong>Operational Spending:</strong> Rent, utilities, insurance, maintenance, professional services, miscellaneous business costs</li>
                <li><strong>Client and Entertainment:</strong> Client meals, entertainment expenses, business gifts, event costs, relationship development</li>
                <li><strong>Marketing and Advertising:</strong> Advertising campaigns, social media ads, content creation, promotional materials, trade shows</li>
              </ul>
              <p style={{marginTop: '18px'}}>These categories provide a complete foundation for expense tracking and financial reporting.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Built-in automation</div>
              <h2>Built-In <span className="serif-accent">Expense Report</span> Formulas</h2>
              <p className="intro">No manual calculations. All formulas are wired, tested, and ready to use.</p>
            </div>
            <div className="row-body">
              <p>Every expense report spreadsheet includes built-in formulas for automatic financial calculations:</p>
              <ul className="bulleted">
                <li><strong>Total expenses:</strong> =SUM(Amount Column)</li>
                <li><strong>Category totals:</strong> =SUMIF(Category, "Travel", Amount)</li>
                <li><strong>Budget variance:</strong> =Total Expenses - Budget Amount</li>
                <li><strong>Reimbursable amount:</strong> =SUMIF(Policy, "Compliant", Amount)</li>
                <li><strong>Monthly average:</strong> =AVERAGE(Monthly Totals)</li>
                <li><strong>Receipt completion:</strong> =COUNTA(Receipt Numbers) / COUNTA(Expenses) × 100%</li>
                <li><strong>Pending reimbursements:</strong> =COUNTIF(Status, "Pending")</li>
                <li><strong>Expense by employee:</strong> =SUMIF(Employee Column, "Name", Amount)</li>
              </ul>
              <p style={{marginTop: '18px'}}>These formulas automate complex expense calculations, reducing manual effort and improving financial accuracy.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Expense Report Templates by <span className="serif-accent">Business</span> Type</h2>
              <p className="intro">Customize the expense report for any business type — same structure, different focus.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">SB</div>
                    <div>
                      <h4>Small Business Expense Report</h4>
                      <div className="industry-tagline">BUSINESS · FINANCE · OPS</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Operational spending</li>
                    <li>Vendor expenses</li>
                    <li>Business purchases</li>
                    <li>Budget monitoring</li>
                    <li>Financial summaries</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Ideal for small businesses and operational finance teams.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">ER</div>
                    <div>
                      <h4>Employee Reimbursement Spreadsheet</h4>
                      <div className="industry-tagline">HR · PAYROLL · STAFF</div>
                    </div>
                  </div>
                  <p>Manage:</p>
                  <ul>
                    <li>Staff expense claims</li>
                    <li>Approval workflows</li>
                    <li>Expense receipts</li>
                    <li>Payment tracking</li>
                    <li>Department reimbursements</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for HR and finance departments.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">TT</div>
                    <div>
                      <h4>Travel Expense Tracking Template</h4>
                      <div className="industry-tagline">TRAVEL · TRANSPORT · TRIPS</div>
                    </div>
                  </div>
                  <p>Monitor:</p>
                  <ul>
                    <li>Transportation costs</li>
                    <li>Hotel expenses</li>
                    <li>Meals</li>
                    <li>Travel reimbursements</li>
                    <li>Business trip spending</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Designed for business travel management.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">FM</div>
                    <div>
                      <h4>Freelancer Expense Management Spreadsheet</h4>
                      <div className="industry-tagline">FREELANCE · CONSULT · PRO</div>
                    </div>
                  </div>
                  <p>Organize:</p>
                  <ul>
                    <li>Project expenses</li>
                    <li>Subscription costs</li>
                    <li>Tax-deductible spending</li>
                    <li>Client-related purchases</li>
                    <li>Operational budgeting</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for freelancers and consultants.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINANCIAL REPORTS AND SPENDING INSIGHTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Financial Reports and Spending Insights</h2>
              <p className="intro">Every generated expense system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte expense report spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Expense summaries</li>
                <li>Spending analysis reports</li>
                <li>Budget tracking dashboards</li>
                <li>Reimbursement reports</li>
                <li>Operational cost analysis</li>
                <li>Department spending reports</li>
                <li>Expense trend insights</li>
                <li>Financial reporting summaries</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into spending patterns and support better financial decision-making.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Expense Report Spreadsheet vs. <span className="serif-accent">Manual</span> Tracking</h2>
              <p className="intro">Seven dimensions where AI-powered expense tracking outperforms manual expense reporting.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual Expense Tracking</div>
                  <h3>Manual financial organization</h3>
                  <ul>
                    <li>Often inconsistent</li>
                    <li>Manual calculations</li>
                    <li>Limited visibility</li>
                    <li>Difficult to track</li>
                    <li>Time-consuming</li>
                    <li>Less efficient</li>
                    <li>Basic tracking</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>AI-generated spreadsheets</h3>
                  <ul>
                    <li>Structured organization</li>
                    <li>Included automation</li>
                    <li>Dashboard-based</li>
                    <li>High visibility</li>
                    <li>Fast setup</li>
                    <li>Centralized management</li>
                    <li>Comprehensive reporting</li>
                  </ul>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify expense reporting and financial organization.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">Expense Report</span> Templates</h2>
              <p className="intro">Faster setup, accurate tracking, better budgets — every expense already organized.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster Expense Reporting</h3>
                  <p>Generate complete expense management systems instantly without manually formatting spreadsheets.</p>
                </div>
                <div className="benefit-card">
                  <h3>Better Financial Organization</h3>
                  <p>Structured spending categories improve budgeting visibility and expense tracking accuracy.</p>
                </div>
                <div className="benefit-card">
                  <h3>Reduced Reporting Errors</h3>
                  <p>Automated formulas reduce calculation mistakes and reimbursement inconsistencies.</p>
                </div>
                <div className="benefit-card">
                  <h3>Easier Tax Preparation</h3>
                  <p>Organized expense records simplify tax reporting and financial documentation.</p>
                </div>
                <div className="benefit-card">
                  <h3>Improved Budget Management</h3>
                  <p>Expense dashboards help businesses monitor spending trends and operational costs more effectively.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing <span className="serif-accent">Expense Report</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated expense report into a real financial management tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Record Expenses Consistently</h3>
                  <p>Update expense records regularly to improve financial accuracy and expense visibility.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Organize by Category</h3>
                  <p>Use structured categories to improve spending analysis and reporting quality.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Keep Receipt Documentation</h3>
                  <p>Maintain receipts for all purchases to improve financial verification and reimbursement tracking.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Review Spending Reports</h3>
                  <p>Regular reviews help identify overspending patterns, budget issues, and cost-saving opportunities.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most expense report templates are static spreadsheets with limited flexibility.</p>
            </div>
            <div className="row-body">
              <p>Most expense report templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated expense management systems tailored to your budgeting workflow, reimbursement process, and financial reporting requirements.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Expense trackers</li>
                <li>Budget dashboards</li>
                <li>Reimbursement systems</li>
                <li>Spending analysis reports</li>
                <li>Financial summaries</li>
                <li>Receipt management sheets</li>
                <li>Expense approval workflows</li>
                <li>AI-powered reporting systems</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing expenses, Formula Byte automates expense reporting spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This Expense <span className="serif-accent">Report</span> Spreadsheet?</h2>
              <p className="intro">This spreadsheet solution is ideal for businesses and professionals managing expense tracking.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>Finance teams</h4></div>
                <div className="audience-cell"><h4>HR departments</h4></div>
                <div className="audience-cell"><h4>Consultants</h4></div>
                <div className="audience-cell"><h4>Freelancers</h4></div>
                <div className="audience-cell"><h4>Operational managers</h4></div>
                <div className="audience-cell"><h4>Employees</h4></div>
                <div className="audience-cell"><h4>Accountants</h4></div>
                <div className="audience-cell"><h4>Business travelers</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple expense tracking or advanced financial reporting, Formula Byte helps automate expense report spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating expense report templates with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet calculate expense totals automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates expense report spreadsheets with automated calculations, budget tracking, and financial summaries.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include reimbursement tracking?</summary>
                  <div className="faq-a">Yes. Expense report templates can include approval workflows, reimbursement monitoring, and payment tracking systems.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize expense categories?</summary>
                  <div className="faq-a">Absolutely. Spending categories, reporting layouts, reimbursement systems, and dashboards can all be customized to your needs.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte expense report templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for business expense management?</summary>
                  <div className="faq-a">Yes. Businesses commonly use expense report spreadsheets for budgeting, reimbursements, operational spending, and financial reporting.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other finance templates you might need.</h2>
              <p className="intro">Same engine, different finance workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/balance-sheet-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Balance Sheet</h4>
                  <p>Track business financial health and assets.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/business-budget-template/" className="related-card">
                  <div className="glyph">G</div>
                  <h4>Business Budget</h4>
                  <p>Manage company finances and budget planning.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/amortization-schedule-template/" className="related-card">
                  <div className="glyph">A</div>
                  <h4>Amortization Schedule</h4>
                  <p>Track loan payments and amortization.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/calendar-template-2026/" className="related-card">
                  <div className="glyph">C</div>
                  <h4>Calendar Template</h4>
                  <p>Monthly planning, scheduling, and appointments.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI Expense <span className="accent">Report</span> Spreadsheet?</h2>
            <p>Stop tracking expenses manually.</p>
            <p>Describe your expense reporting workflow, and Formula Byte will generate a professional AI-powered Excel expense report template with spending categories, reimbursement systems, budget dashboards, financial summaries, and organized reporting workflows in seconds.</p>
            <p>Create smarter expense report spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}
