import React from 'react';

export default function FamilyTreeTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=personal">Personal</a>
            <span className="sep">/</span>
            <span className="current">Family Tree</span>
          </div>

          <div className="eyebrow">Personal template</div>
          <h1>AI Excel Family Tree Template for Ancestry Tracking and <span className="accent">Genealogy</span></h1>
          <p className="lede">
            Track family relationships, lineage charts, ancestral records, birth and marriage data, and family history with an AI-generated Excel family tree template designed for smarter genealogy management. Formula Byte helps individuals and families automate family tree organization using intelligent spreadsheets with relationship tracking systems, generational mapping tools, historical record management, and customizable family charts.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>7</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>12</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>15 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate family tree spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Genealogy research</span>
          <span className="use-case-pill"><span className="dot"></span>Family history tracking</span>
          <span className="use-case-pill"><span className="dot"></span>Ancestry documentation</span>
          <span className="use-case-pill"><span className="dot"></span>Lineage mapping</span>
          <span className="use-case-pill"><span className="dot"></span>Relationship charts</span>
          <span className="use-case-pill"><span className="dot"></span>Family reunions</span>
          <span className="use-case-pill"><span className="dot"></span>Historical records</span>
          <span className="use-case-pill"><span className="dot"></span>Heritage documentation</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Family-Tree-Tracker<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">F7</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=IF</span>(<span className="num">E7</span><span className="op">=</span><span className="str">"Male"</span>, <span className="str">"♦"</span>, <span className="str">"♀"</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header">F</div>
            <div className="preview-col-header">G</div>
            <div className="preview-col-header preview-hide-mobile">H</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Name</div>
            <div className="preview-cell preview-header-cell">Birth Date</div>
            <div className="preview-cell preview-header-cell">Gender</div>
            <div className="preview-cell preview-header-cell">Father</div>
            <div className="preview-cell preview-header-cell">Mother</div>
            <div className="preview-cell preview-header-cell">Generation</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Children</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">John Martinez Sr.</div>
            <div className="preview-cell">1952-04-15</div>
            <div className="preview-cell">Male</div>
            <div className="preview-cell">—</div>
            <div className="preview-cell">—</div>
            <div className="preview-cell">1</div>
            <div className="preview-cell num preview-hide-mobile">3</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">Maria Martinez</div>
            <div className="preview-cell">1954-08-22</div>
            <div className="preview-cell selected">Female</div>
            <div className="preview-cell">—</div>
            <div className="preview-cell">—</div>
            <div className="preview-cell">1</div>
            <div className="preview-cell num preview-hide-mobile">3</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">John Martinez Jr.</div>
            <div className="preview-cell">1978-03-10</div>
            <div className="preview-cell">Male</div>
            <div className="preview-cell">John Martinez Sr.</div>
            <div className="preview-cell">Maria Martinez</div>
            <div className="preview-cell">2</div>
            <div className="preview-cell num preview-hide-mobile">2</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">Sarah Chen-Martinez</div>
            <div className="preview-cell">1980-07-18</div>
            <div className="preview-cell">Female</div>
            <div className="preview-cell">Robert Chen</div>
            <div className="preview-cell">Linda Chen</div>
            <div className="preview-cell">2</div>
            <div className="preview-cell num preview-hide-mobile">2</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Michael Martinez</div>
            <div className="preview-cell">1985-11-30</div>
            <div className="preview-cell">Male</div>
            <div className="preview-cell">John Martinez Sr.</div>
            <div className="preview-cell">Maria Martinez</div>
            <div className="preview-cell">2</div>
            <div className="preview-cell num preview-hide-mobile">1</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">Emma Martinez</div>
            <div className="preview-cell">2005-09-12</div>
            <div className="preview-cell">Female</div>
            <div className="preview-cell">John Martinez Jr.</div>
            <div className="preview-cell">Sarah Chen-Martinez</div>
            <div className="preview-cell">3</div>
            <div className="preview-cell num preview-hide-mobile">0</div>

            {/* Row 8 */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text">Lucas Martinez</div>
            <div className="preview-cell">2008-05-25</div>
            <div className="preview-cell">Male</div>
            <div className="preview-cell">John Martinez Jr.</div>
            <div className="preview-cell">Sarah Chen-Martinez</div>
            <div className="preview-cell">3</div>
            <div className="preview-cell num preview-hide-mobile">0</div>

            {/* Empty rows */}
            {Array.from({length: 4}).map((_, i) => (
              <React.Fragment key={`empty-${i}`}>
                <div className="preview-row-num">{9 + i}</div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell preview-hide-mobile"></div>
              </React.Fragment>
            ))}

            {/* Status bar */}
            <div className="preview-status">
              <div className="preview-status-item">
                <span>Family members:</span>
                <span className="val">8</span>
              </div>
              <div className="preview-status-item">
                <span>Generations:</span>
                <span className="val">3</span>
              </div>
              <div className="preview-status-spacer"></div>
              <div className="preview-status-tabs">
                <button className="preview-tab active">Family Tree</button>
                <button className="preview-tab">Lineage</button>
                <button className="preview-tab">Records</button>
                <button className="preview-tab">Charts</button>
                <button className="preview-tab">+3</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* CREATE AN AI FAMILY TREE SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Family Tree Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the family tree spreadsheet you need, and Formula Byte automatically generates a professional Excel genealogy system with:</p>
            </div>
            <div className="row-body">
              <ul className="bulleted">
                <li>Family relationship tracking</li>
                <li>Generational mapping</li>
                <li>Birth and marriage records</li>
                <li>Ancestral documentation</li>
                <li>Lineage charts</li>
                <li>Family history logs</li>
                <li>Customizable family charts</li>
                <li>Automated spreadsheet formulas</li>
                <li>Genealogy research tools</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually building family trees, Formula Byte creates AI-powered genealogy management systems tailored to your family history needs.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel Family Tree Template?</h2>
              <p className="intro">A structured spreadsheet used to organize family relationships, track ancestry, and document genealogy.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel family tree template</strong> is a structured spreadsheet used to organize family relationships, track ancestral lineage, document genealogy, and manage family history records.
              </p>
              <p>
                A family tree spreadsheet typically includes:
              </p>
              <ul className="bulleted">
                <li>Family member records</li>
                <li>Birth and death dates</li>
                <li>Marriage information</li>
                <li>Parent-child relationships</li>
                <li>Generational data</li>
                <li>Ancestral lineage</li>
                <li>Family photos</li>
                <li>Historical documents</li>
                <li>Relationship charts</li>
              </ul>
              <p>Formula Byte generates AI-powered family tree spreadsheets designed for genealogy research, family history documentation, and ancestry tracking.</p>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How Family Tree Tracking Works</h2>
              <p className="intro">Family tree tracking is the process of organizing family relationships and documenting ancestral lineage.</p>
            </div>
            <div className="row-body">
              <p>Family tree tracking is the process of organizing family relationships, documenting birth and marriage records, mapping generational connections, and preserving family history.</p>
              <p style={{marginTop: '18px'}}>A structured family tree system helps individuals and families:</p>
              <ul className="bulleted">
                <li>Track family lineage</li>
                <li>Document ancestry</li>
                <li>Preserve family history</li>
                <li>Research genealogy</li>
                <li>Organize family records</li>
                <li>Create relationship charts</li>
                <li>Share family heritage</li>
              </ul>
              <p style={{marginTop: '18px'}}>Most family tree systems include:</p>
              <ul className="bulleted">
                <li>Family member databases</li>
                <li>Relationship mapping</li>
                <li>Generational charts</li>
                <li>Historical records</li>
                <li>Photo galleries</li>
                <li>Document storage</li>
                <li>Research logs</li>
              </ul>
              <p style={{marginTop: '18px'}}>Formula Byte simplifies this process with AI-generated family tree spreadsheets and automated genealogy management systems.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY PEOPLE USE FAMILY TREE TRACKING */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why People Use Family Tree Tracking</h2>
              <p className="intro">Managing family history without a structured system often creates lost information and disconnected records.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without family tree tracking</div>
                  <h3>Managing family history without a structured system often creates:</h3>
                  <ul>
                    <li>Lost ancestral information</li>
                    <li>Disconnected family records</li>
                    <li>Incomplete lineage data</li>
                    <li>Forgotten family stories</li>
                    <li>Missing birth and marriage dates</li>
                    <li>Unclear relationships</li>
                    <li>Scattered documents</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With family tree tracking</div>
                  <h3>A properly organized family tree spreadsheet helps:</h3>
                  <ul>
                    <li>Preserve family heritage</li>
                    <li>Track ancestral lineage</li>
                    <li>Document relationships</li>
                    <li>Store historical records</li>
                    <li>Research genealogy effectively</li>
                    <li>Share family history</li>
                    <li>Create meaningful charts</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI <span className="serif-accent">Family Tree</span> Spreadsheet</h2>
              <p className="intro">Four pillars of genealogy management — automatic, organized, and built to support real family history needs.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">F</div>
                  <h3>Family Relationship Tracking</h3>
                  <p>Organize all family members with automatic relationship mapping and structured lineage layouts.</p>
                  <ul>
                    <li>Parent-child links</li>
                    <li>Spouse records</li>
                    <li>Sibling connections</li>
                    <li>Generational tags</li>
                    <li>Birth/death dates</li>
                    <li>Marriage records</li>
                    <li>Family photos</li>
                    <li>Contact information</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>The spreadsheet automatically organizes family members into structured relationship layouts.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">G</div>
                  <h3>Generational Mapping</h3>
                  <p>Monitor all ancestral generations with organized generational tracking systems.</p>
                  <ul>
                    <li>Generation numbers</li>
                    <li>Ancestral depth</li>
                    <li>Lineage paths</li>
                    <li>Family branches</li>
                    <li>Descendant trees</li>
                    <li>Ancestor charts</li>
                    <li>Heritage tracking</li>
                    <li>Ethnicity records</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This helps families maintain accurate ancestral records and lineage documentation.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">R</div>
                  <h3>Birth/Marriage/Historical Records</h3>
                  <p>Formula Byte family tree spreadsheets can include comprehensive historical record tracking systems.</p>
                  <ul>
                    <li>Birth certificates</li>
                    <li>Marriage licenses</li>
                    <li>Death records</li>
                    <li>Census data</li>
                    <li>Immigration papers</li>
                    <li>Military service</li>
                    <li>Education history</li>
                    <li>Employment records</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Structured record systems improve genealogy research and family history preservation.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">C</div>
                  <h3>Customizable Family Charts</h3>
                  <p>Create custom family charts with comprehensive visualization and reporting tools.</p>
                  <ul>
                    <li>Tree diagrams</li>
                    <li>Relationship charts</li>
                    <li>Timeline views</li>
                    <li>Photo galleries</li>
                    <li>Family summaries</li>
                    <li>Ancestry reports</li>
                    <li>Descendant lists</li>
                    <li>Heritage documentation</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This improves visualization of family connections and ancestry presentation.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI FAMILY TREE AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Family Tree Automation for Genealogy Management</h2>
              <p className="intro">Skip the manual setup. The AI understands family tree instructions from natural language prompts.</p>
            </div>
            <div className="row-body">
              <p>Traditional family tree spreadsheets require manual data entry and repetitive relationship mapping.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure family databases</li>
                <li>Generate relationship mapping systems</li>
                <li>Organize genealogy records</li>
                <li>Create family tree workflows</li>
                <li>Build lineage charts</li>
                <li>Generate ancestry reports</li>
                <li>Apply spreadsheet formatting</li>
                <li>Automate family history tasks</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands family tree instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a family tree spreadsheet with relationship tracking"</button>
                  <button className="chip">"Build a genealogy research dashboard"</button>
                  <button className="chip">"Generate an ancestral lineage system"</button>
                  <button className="chip">"Create a family history chart for my reunion"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Family Tree Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete family tree spreadsheet with 7 worksheets — each generated, formatted, and wired up automatically.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Family Tree</span>
                  <span className="spec-purpose">Main relationship database</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Lineage Chart</span>
                  <span className="spec-purpose">Displays generational ancestry</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Records</span>
                  <span className="spec-purpose">Stores birth/marriage/death data</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Photos</span>
                  <span className="spec-purpose">Manages family photo gallery</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Research Log</span>
                  <span className="spec-purpose">Tracks genealogy research</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Documents</span>
                  <span className="spec-purpose">Links historical documents</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Reports</span>
                  <span className="spec-purpose">Summarizes family statistics</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FAMILY TREE CATEGORIES INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Data included</div>
              <h2>Family Tree <span className="serif-accent">Categories</span> Included</h2>
              <p className="intro">Every family tree category you need — pre-built, organized, and ready for instant genealogy tracking.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte family tree spreadsheets include comprehensive genealogy management categories:</p>
              <ul className="bulleted">
                <li><strong>Family member information:</strong> Names, nicknames, dates, locations, contact details</li>
                <li><strong>Birth and death data:</strong> Birth dates, death dates, locations, causes, certificates</li>
                <li><strong>Marriage records:</strong> Spouse names, marriage dates, locations, divorce records</li>
                <li><strong>Relationship mapping:</strong> Parent-child links, sibling connections, ancestral lineage</li>
                <li><strong>Generational data:</strong> Generation numbers, family branches, descendant trees</li>
                <li><strong>Historical documents:</strong> Birth certificates, marriage licenses, census records, immigration papers</li>
                <li><strong>Photo galleries:</strong> Family photos, scanned documents, historical images</li>
                <li><strong>Research logs:</strong> Source citations, research notes, verification status, to-do lists</li>
              </ul>
              <p style={{marginTop: '18px'}}>These categories provide a complete foundation for family tree organization and genealogy research.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Built-in automation</div>
              <h2>Built-In <span className="serif-accent">Family Tree</span> Formulas</h2>
              <p className="intro">No manual calculations. All formulas are wired, tested, and ready to use.</p>
            </div>
            <div className="row-body">
              <p>Every family tree spreadsheet includes built-in formulas for automatic genealogy calculations:</p>
              <ul className="bulleted">
                <li><strong>Age calculation:</strong> =YEAR(TODAY()) - YEAR(Birth Date)</li>
                <li><strong>Generation number:</strong> =IF(Parent="", 1, Parent's Generation + 1)</li>
                <li><strong>Gender symbol:</strong> =IF(Gender="Male", "♦", "♀")</li>
                <li><strong>Relationship type:</strong> =IF(Father=""&Mother="", "Root", "Child")</li>
                <li><strong>Children count:</strong> =COUNTIF(Parent Column, Current Name)</li>
                <li><strong>Ancestral depth:</strong> =MAX(Generation Numbers)</li>
                <li><strong>Birth year:</strong> =YEAR(Birth Date)</li>
                <li><strong>Alive status:</strong> =IF(Death Date="", "Living", "Deceased")</li>
              </ul>
              <p style={{marginTop: '18px'}}>These formulas automate complex genealogy calculations, reducing manual effort and improving accuracy.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Family Tree Templates by <span className="serif-accent">Use Case</span> Type</h2>
              <p className="intro">Customize the family tree for any purpose — same structure, different focus.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">GR</div>
                    <div>
                      <h4>Genealogy Research Spreadsheet</h4>
                      <div className="industry-tagline">ANCESTRY · LINEAGE · RESEARCH</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Ancestral documentation</li>
                    <li>Lineage verification</li>
                    <li>Source citations</li>
                    <li>Research progress</li>
                    <li>DNA test results</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Ideal for genealogists and family historians.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">FH</div>
                    <div>
                      <h4>Family History Chart</h4>
                      <div className="industry-tagline">HERITAGE · LEGACY · STORIES</div>
                    </div>
                  </div>
                  <p>Document:</p>
                  <ul>
                    <li>Family stories</li>
                    <li>Historical events</li>
                    <li>Biographical data</li>
                    <li>Photo collections</li>
                    <li>Timeline records</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for preserving family heritage and stories.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">FR</div>
                    <div>
                      <h4>Family Reunion Planner</h4>
                      <div className="industry-tagline">EVENTS · GATHERINGS · COORDINATION</div>
                    </div>
                  </div>
                  <p>Organize:</p>
                  <ul>
                    <li>Guest lists</li>
                    <li>Family branches</li>
                    <li>Contact information</li>
                    <li>Event logistics</li>
                    <li>Activity planning</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Designed for family reunion organizers.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">ED</div>
                    <div>
                      <h4>Ethnicity Documentation</h4>
                      <div className="industry-tagline">CULTURE · ORIGINS · IDENTITY</div>
                    </div>
                  </div>
                  <p>Record:</p>
                  <ul>
                    <li>Ethnic backgrounds</li>
                    <li>Geographic origins</li>
                    <li>Immigration history</li>
                    <li>Cultural traditions</li>
                    <li>Language heritage</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for ethnicity research and heritage tracking.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* GENEALOGY REPORTS AND INSIGHTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Genealogy Reports and Family History Insights</h2>
              <p className="intro">Every generated family tree system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte family tree spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Ancestral lineage reports</li>
                <li>Generational summaries</li>
                <li>Family statistics</li>
                <li>Relationship charts</li>
                <li>Photo galleries</li>
                <li>Research progress reports</li>
                <li>Heritage documentation</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports help families visualize ancestry, track genealogy research, and preserve family history.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Family Tree Spreadsheet vs. <span className="serif-accent">Manual</span> Research</h2>
              <p className="intro">Seven dimensions where AI-powered family tree spreadsheets outperform manual genealogy work.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual Research</div>
                  <h3>Manual family tree organization</h3>
                  <ul>
                    <li>Time-consuming data entry</li>
                    <li>Manual relationship mapping</li>
                    <li>Limited visualization</li>
                    <li>Prone to errors</li>
                    <li>Difficult to maintain</li>
                    <li>Limited reporting</li>
                    <li>Scattered records</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>AI-generated spreadsheets</h3>
                  <ul>
                    <li>Automated organization</li>
                    <li>Included relationship mapping</li>
                    <li>Chart-based visualization</li>
                    <li>High accuracy</li>
                    <li>Easy to maintain</li>
                    <li>Comprehensive reporting</li>
                    <li>Centralized records</li>
                  </ul>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify family tree organization and genealogy research.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">Family Tree</span> Templates</h2>
              <p className="intro">Faster setup, accurate records, better visualization — every relationship already mapped.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster Family Tree Setup</h3>
                  <p>Generate complete genealogy management systems instantly without manually formatting spreadsheets.</p>
                </div>
                <div className="benefit-card">
                  <h3>Accurate Relationship Mapping</h3>
                  <p>Pre-built formulas ensure precise relationship calculations, generational tracking, and lineage documentation.</p>
                </div>
                <div className="benefit-card">
                  <h3>Improved Family History Visibility</h3>
                  <p>Built-in charts provide instant visibility into ancestry, family connections, and generational depth.</p>
                </div>
                <div className="benefit-card">
                  <h3>Reduced Genealogy Errors</h3>
                  <p>Automated systems reduce manual data entry mistakes and relationship mapping inconsistencies.</p>
                </div>
                <div className="benefit-card">
                  <h3>Easier Research Organization</h3>
                  <p>Organized source citations, research logs, and document storage simplify genealogy research workflows.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing <span className="serif-accent">Family Tree</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated family tree into a real genealogy research tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Verify All Sources</h3>
                  <p>Always document sources for birth, marriage, and death records to ensure genealogy accuracy.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Update Records Regularly</h3>
                  <p>Add new family members, marriage records, and historical documents as information becomes available.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Backup Your Data</h3>
                  <p>Regular backups protect your family history research from data loss and technical issues.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Share with Family</h3>
                  <p>Collaborate with relatives to verify information and discover missing family connections.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most family tree templates are static spreadsheets with limited flexibility.</p>
            </div>
            <div className="row-body">
              <p>Most family tree templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated genealogy management systems tailored to your family history needs, research workflow, and ancestry documentation requirements.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Family relationship databases</li>
                <li>Generational mapping systems</li>
                <li>Historical record trackers</li>
                <li>Photo gallery worksheets</li>
                <li>Research log templates</li>
                <li>Document storage systems</li>
                <li>Ancestral chart generators</li>
                <li>AI-powered genealogy workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing family trees, Formula Byte automates genealogy spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This <span className="serif-accent">Family Tree</span> Spreadsheet?</h2>
              <p className="intro">This spreadsheet solution is ideal for individuals and families managing family history and genealogy.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Genealogy enthusiasts</h4></div>
                <div className="audience-cell"><h4>Family historians</h4></div>
                <div className="audience-cell"><h4>Family reunion planners</h4></div>
                <div className="audience-cell"><h4>Ancestry researchers</h4></div>
                <div className="audience-cell"><h4>Heritage seekers</h4></div>
                <div className="audience-cell"><h4>Family archivists</h4></div>
                <div className="audience-cell"><h4>Storytellers</h4></div>
                <div className="audience-cell"><h4>DNA test takers</h4></div>
                <div className="audience-cell"><h4>Adoptees</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple relationship tracking or advanced genealogy research, Formula Byte helps automate family tree spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating family tree templates with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet track family relationships automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates family tree spreadsheets with relationship tracking, generational mapping, and ancestry systems.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include photo storage?</summary>
                  <div className="faq-a">Yes. Family tree templates can include photo galleries, document storage, and historical image collections.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize family tree structures and charts?</summary>
                  <div className="faq-a">Absolutely. Tree layouts, relationship formats, chart styles, and genealogy workflows can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte family tree templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for genealogy research?</summary>
                  <div className="faq-a">Yes. Genealogy researchers commonly use family tree spreadsheets for ancestry tracking, lineage documentation, and family history preservation.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other personal templates you might need.</h2>
              <p className="intro">Same engine, different personal workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/daily-schedule-template/" className="related-card">
                  <div className="glyph">D</div>
                  <h4>Daily Schedule</h4>
                  <p>Organize tasks, appointments, and time blocks.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/calendar-template-2026/" className="related-card">
                  <div className="glyph">C</div>
                  <h4>Calendar Template</h4>
                  <p>Monthly planning, scheduling, and appointments.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/to-do-list-template/" className="related-card">
                  <div className="glyph">T</div>
                  <h4>To-Do List</h4>
                  <p>Track tasks, priorities, and completion status.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/budget-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Budget Template</h4>
                  <p>Personal finance tracking and expense management.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">Family Tree</span> Spreadsheet?</h2>
            <p>Stop losing family history.</p>
            <p>Describe your genealogy research needs, and Formula Byte will generate a professional AI-powered Excel family tree template with relationship tracking systems, generational mapping tools, historical record management, and organized family history workflows in seconds.</p>
            <p>Create smarter family tree spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}
