import React from 'react';

export default function IncomeStatementTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=business">Business</a>
            <span className="sep">/</span>
            <span className="current">Income Statement</span>
          </div>

          <div className="eyebrow">Business template</div>
          <h1>AI Excel Income Statement Template for Financial Reporting and <span className="accent">Profit Analysis</span></h1>
          <p className="lede">
            Track revenue, expenses, gross profit, and net income with an AI-generated Excel income statement template designed for smarter financial reporting and business analysis. Formula Byte helps businesses automate income statement creation using intelligent spreadsheets with built-in financial formulas, reporting dashboards, profitability tracking systems, and accounting workflows.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>7</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>14</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate income statement spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Startups</span>
          <span className="use-case-pill"><span className="dot"></span>Ecommerce brands</span>
          <span className="use-case-pill"><span className="dot"></span>Agencies</span>
          <span className="use-case-pill"><span className="dot"></span>Contractors</span>
          <span className="use-case-pill"><span className="dot"></span>Freelancers</span>
          <span className="use-case-pill"><span className="dot"></span>Financial reporting teams</span>
          <span className="use-case-pill"><span className="dot"></span>Profit analysis management</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Income-Statement-Report<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">C8</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=SUM</span>(<span className="num">C5</span><span className="op">:</span><span className="num">C7</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header">F</div>
            <div className="preview-col-header">G</div>
            <div className="preview-col-header preview-hide-mobile">H</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Line Item</div>
            <div className="preview-cell preview-header-cell">Jan</div>
            <div className="preview-cell preview-header-cell">Feb</div>
            <div className="preview-cell preview-header-cell">Mar</div>
            <div className="preview-cell preview-header-cell">Apr</div>
            <div className="preview-cell preview-header-cell">May</div>
            <div className="preview-cell preview-header-cell">Jun</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Total</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">Revenue</div>
            <div className="preview-cell num">$45,200</div>
            <div className="preview-cell num">$47,800</div>
            <div className="preview-cell num">$52,100</div>
            <div className="preview-cell num">$49,600</div>
            <div className="preview-cell num">$55,300</div>
            <div className="preview-cell num">$58,900</div>
            <div className="preview-cell num selected preview-hide-mobile">$308,900</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">COGS</div>
            <div className="preview-cell num">($18,080)</div>
            <div className="preview-cell num">($19,120)</div>
            <div className="preview-cell num">($20,840)</div>
            <div className="preview-cell num">($19,840)</div>
            <div className="preview-cell num">($22,120)</div>
            <div className="preview-cell num">($23,560)</div>
            <div className="preview-cell num preview-hide-mobile">($123,560)</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">Gross Profit</div>
            <div className="preview-cell num">$27,120</div>
            <div className="preview-cell num">$28,680</div>
            <div className="preview-cell num">$31,260</div>
            <div className="preview-cell num">$29,760</div>
            <div className="preview-cell num">$33,180</div>
            <div className="preview-cell num">$35,340</div>
            <div className="preview-cell num preview-hide-mobile">$185,340</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">Operating Expenses</div>
            <div className="preview-cell num">($12,500)</div>
            <div className="preview-cell num">($13,200)</div>
            <div className="preview-cell num">($14,100)</div>
            <div className="preview-cell num">($13,800)</div>
            <div className="preview-cell num">($15,200)</div>
            <div className="preview-cell num">($16,400)</div>
            <div className="preview-cell num preview-hide-mobile">($85,200)</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Operating Income</div>
            <div className="preview-cell num">$14,620</div>
            <div className="preview-cell num">$15,480</div>
            <div className="preview-cell num">$17,160</div>
            <div className="preview-cell num">$15,960</div>
            <div className="preview-cell num">$17,980</div>
            <div className="preview-cell num">$18,940</div>
            <div className="preview-cell num preview-hide-mobile">$100,140</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">Taxes</div>
            <div className="preview-cell num">($2,924)</div>
            <div className="preview-cell num">($3,096)</div>
            <div className="preview-cell num">($3,432)</div>
            <div className="preview-cell num">($3,192)</div>
            <div className="preview-cell num">($3,596)</div>
            <div className="preview-cell num">($3,788)</div>
            <div className="preview-cell num preview-hide-mobile">($20,028)</div>

            {/* Row 8 */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text">Net Income</div>
            <div className="preview-cell num">$11,696</div>
            <div className="preview-cell num">$12,384</div>
            <div className="preview-cell num">$13,728</div>
            <div className="preview-cell num">$12,768</div>
            <div className="preview-cell num">$14,384</div>
            <div className="preview-cell num">$15,152</div>
            <div className="preview-cell num preview-hide-mobile">$80,112</div>

            {/* Empty rows */}
            {Array.from({length: 4}).map((_, i) => (
              <React.Fragment key={`empty-${i}`}>
                <div className="preview-row-num">{9 + i}</div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell preview-hide-mobile"></div>
              </React.Fragment>
            ))}

            {/* Status bar */}
            <div className="preview-status">
              <div className="preview-status-item">
                <span>Total Revenue:</span>
                <span className="val">$308,900</span>
              </div>
              <div className="preview-status-item">
                <span>Net Income:</span>
                <span className="val">$80,112</span>
              </div>
              <div className="preview-status-item">
                <span>Profit Margin:</span>
                <span className="val">25.9%</span>
              </div>
              <div className="preview-status-spacer"></div>
              <div className="preview-status-tabs">
                <button className="preview-tab active">Income Statement</button>
                <button className="preview-tab">Revenue</button>
                <button className="preview-tab">Expenses</button>
                <button className="preview-tab">Dashboard</button>
                <button className="preview-tab">+3</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* CREATE AN AI INCOME STATEMENT SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Income Statement Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the financial reporting spreadsheet you need, and Formula Byte automatically generates a professional Excel income statement template with:</p>
            </div>
            <div className="row-body">
              <ul className="bulleted">
                <li>Revenue tracking</li>
                <li>Expense categorization</li>
                <li>Gross profit analysis</li>
                <li>Net income calculations</li>
                <li>Cost of goods sold tracking</li>
                <li>Operating expense summaries</li>
                <li>Financial dashboards</li>
                <li>Automated spreadsheet formulas</li>
                <li>Profitability reporting systems</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually building financial statements, Formula Byte creates AI-powered reporting systems tailored to your accounting workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel Income Statement Template?</h2>
              <p className="intro">A structured spreadsheet used to summarize business revenue, expenses, and profitability over a specific accounting period.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel income statement template</strong> is a structured spreadsheet used to summarize business revenue, expenses, and profitability over a specific accounting period. It helps businesses analyze financial performance while improving accounting organization and reporting visibility.
              </p>
              <p>
                An income statement spreadsheet typically includes:
              </p>
              <ul className="bulleted">
                <li>Revenue tracking</li>
                <li>Cost of goods sold (COGS)</li>
                <li>Gross profit calculations</li>
                <li>Operating expenses</li>
                <li>Operating income</li>
                <li>Tax expenses</li>
                <li>Net income summaries</li>
                <li>Financial reporting dashboards</li>
                <li>Profit analysis sections</li>
              </ul>
              <p>Formula Byte generates AI-powered income statement spreadsheets designed for financial reporting, accounting management, and profitability analysis.</p>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How Income Statements Work</h2>
              <p className="intro">An income statement measures business profitability by comparing revenue against expenses during a specific period.</p>
            </div>
            <div className="row-body">
              <p>An income statement measures business profitability by comparing revenue against expenses during a specific period.</p>
              <p style={{marginTop: '18px'}}>The basic income statement structure follows:</p>
              <ul className="bulleted">
                <li><strong>Net Income = Revenue - Expenses</strong></li>
              </ul>
              <p style={{marginTop: '18px'}}>This financial report helps businesses understand:</p>
              <ul className="bulleted">
                <li>Revenue performance</li>
                <li>Expense management</li>
                <li>Profitability trends</li>
                <li>Operational efficiency</li>
                <li>Financial stability</li>
              </ul>
              <p style={{marginTop: '18px'}}>Most income statements include:</p>
              <ul className="bulleted">
                <li>Revenue reporting</li>
                <li>Cost analysis</li>
                <li>Expense summaries</li>
                <li>Profit calculations</li>
                <li>Financial performance insights</li>
                <li>Operational reporting</li>
              </ul>
              <p style={{marginTop: '18px'}}>Formula Byte simplifies this process using AI-generated financial spreadsheets and automated accounting systems.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY BUSINESSES NEED INCOME STATEMENT REPORTING */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Businesses Need Income Statement Reporting</h2>
              <p className="intro">Managing finances without structured reporting often creates unclear profitability and poor financial visibility.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without income statement reporting</div>
                  <h3>Managing finances without structured reporting often creates:</h3>
                  <ul>
                    <li>Unclear profitability visibility</li>
                    <li>Expense tracking problems</li>
                    <li>Financial reporting errors</li>
                    <li>Poor budgeting decisions</li>
                    <li>Inaccurate accounting records</li>
                    <li>Difficulty analyzing revenue trends</li>
                    <li>Limited operational insights</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With income statement reporting</div>
                  <h3>A properly organized income statement helps businesses:</h3>
                  <ul>
                    <li>Monitor profitability</li>
                    <li>Analyze financial performance</li>
                    <li>Improve accounting accuracy</li>
                    <li>Organize revenue reporting</li>
                    <li>Track operational expenses</li>
                    <li>Support strategic planning</li>
                    <li>Improve financial decision-making</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI <span className="serif-accent">Income Statement</span> Spreadsheet</h2>
              <p className="intro">Four pillars of financial reporting — automatic, organized, and built to support real accounting needs.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">R</div>
                  <h3>Revenue Tracking</h3>
                  <p>Track all business income with automatic revenue categorization and structured financial reporting layouts.</p>
                  <ul>
                    <li>Product sales</li>
                    <li>Service revenue</li>
                    <li>Subscription income</li>
                    <li>Client payments</li>
                    <li>Business earnings</li>
                    <li>Operational income</li>
                    <li>Recurring revenue</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>The spreadsheet automatically organizes income categories into structured financial reporting layouts.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">E</div>
                  <h3>Expense Management</h3>
                  <p>Monitor all business spending with organized expense tracking systems.</p>
                  <ul>
                    <li>Payroll costs</li>
                    <li>Rent</li>
                    <li>Utilities</li>
                    <li>Marketing expenses</li>
                    <li>Operational costs</li>
                    <li>Software subscriptions</li>
                    <li>Vendor payments</li>
                    <li>Administrative expenses</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This improves expense visibility and financial organization.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">C</div>
                  <h3>Cost of Goods Sold (COGS) Tracking</h3>
                  <p>Formula Byte income statement spreadsheets can include comprehensive COGS tracking systems.</p>
                  <ul>
                    <li>Product costs</li>
                    <li>Inventory expenses</li>
                    <li>Production costs</li>
                    <li>Manufacturing expenses</li>
                    <li>Supplier costs</li>
                    <li>Service delivery expenses</li>
                    <li>Material costs</li>
                    <li>Direct labor expenses</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Structured COGS reporting improves gross profit analysis and operational visibility.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">P</div>
                  <h3>Gross Profit and Net Income Analysis</h3>
                  <p>Track business profitability with comprehensive profit analysis and reporting tools.</p>
                  <ul>
                    <li>Gross profit margins</li>
                    <li>Operating profit</li>
                    <li>Net income</li>
                    <li>Financial performance trends</li>
                    <li>Profitability growth</li>
                    <li>Revenue efficiency</li>
                    <li>Expense ratios</li>
                    <li>Profit comparisons</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This helps businesses improve financial planning and profitability analysis.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI FINANCIAL REPORTING AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Financial Reporting Automation for Income Statements</h2>
              <p className="intro">Skip the manual setup. The AI understands financial reporting instructions from natural language prompts.</p>
            </div>
            <div className="row-body">
              <p>Traditional income statement spreadsheets require manual formatting and repetitive accounting calculations.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure financial reports</li>
                <li>Generate accounting formulas</li>
                <li>Organize revenue categories</li>
                <li>Calculate profitability automatically</li>
                <li>Build reporting dashboards</li>
                <li>Create financial summaries</li>
                <li>Apply spreadsheet formatting</li>
                <li>Automate reporting workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands financial reporting instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a small business income statement template"</button>
                  <button className="chip">"Build a profit and loss reporting spreadsheet"</button>
                  <button className="chip">"Generate a startup revenue analysis dashboard"</button>
                  <button className="chip">"Create a monthly profitability tracking system"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Income Statement Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete income statement spreadsheet with 7 worksheets — each generated, formatted, and wired up automatically.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Revenue Tracker</span>
                  <span className="spec-purpose">Monitors business income</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Expense Ledger</span>
                  <span className="spec-purpose">Tracks operational spending</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">COGS Analysis Sheet</span>
                  <span className="spec-purpose">Calculates production costs</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Gross Profit Summary</span>
                  <span className="spec-purpose">Analyzes profitability</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Net Income Report</span>
                  <span className="spec-purpose">Calculates final business profit</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Financial Dashboard</span>
                  <span className="spec-purpose">Visualizes financial performance</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Monthly Reporting Sheet</span>
                  <span className="spec-purpose">Tracks accounting periods</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINANCIAL CATEGORIES INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Data included</div>
              <h2>Financial <span className="serif-accent">Categories</span> Included</h2>
              <p className="intro">Every financial reporting category you need — pre-built, organized, and ready for instant income statement tracking.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte income statement spreadsheets include comprehensive financial reporting categories:</p>
              <ul className="bulleted">
                <li><strong>Revenue reporting:</strong> Product sales, service income, client revenue, subscription earnings, operational income</li>
                <li><strong>Operating expenses:</strong> Payroll, utilities, office expenses, advertising costs, operational spending</li>
                <li><strong>Profitability analysis:</strong> Gross profit, operating income, net income, expense ratios, revenue growth</li>
              </ul>
              <p style={{marginTop: '18px'}}>These categories provide a complete foundation for income statement organization and financial reporting.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Built-in automation</div>
              <h2>Built-In <span className="serif-accent">Income Statement</span> Formulas</h2>
              <p className="intro">No manual calculations. All formulas are wired, tested, and ready to use.</p>
            </div>
            <div className="row-body">
              <p>Every income statement spreadsheet includes built-in formulas for automatic financial calculations:</p>
              <ul className="bulleted">
                <li><strong>Total revenue:</strong> =SUM(Revenue Range)</li>
                <li><strong>Gross profit:</strong> =Revenue - COGS</li>
                <li><strong>Operating income:</strong> =Gross Profit - Operating Expenses</li>
                <li><strong>Net income:</strong> =Operating Income - Taxes</li>
                <li><strong>Profit margin:</strong> = (Net Income / Revenue) × 100%</li>
                <li><strong>Expense ratio:</strong> = (Expenses / Revenue) × 100%</li>
                <li><strong>Revenue growth:</strong> = ((Current Month - Previous Month) / Previous Month) × 100%</li>
                <li><strong>YTD total:</strong> =SUM(Month Range)</li>
              </ul>
              <p style={{marginTop: '18px'}}>These formulas automate complex financial calculations, reducing manual effort and improving accuracy.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Income Statement Templates by <span className="serif-accent">Business</span> Type</h2>
              <p className="intro">Customize the income statement for any business — same structure, different focus.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">SB</div>
                    <div>
                      <h4>Small Business Income Statement</h4>
                      <div className="industry-tagline">BUSINESS · FINANCE · PROFIT</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Revenue growth</li>
                    <li>Operational expenses</li>
                    <li>Profitability</li>
                    <li>Financial performance</li>
                    <li>Business income trends</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Ideal for startups and growing businesses.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">EC</div>
                    <div>
                      <h4>Ecommerce Profit Reporting Spreadsheet</h4>
                      <div className="industry-tagline">ONLINE · SALES · COMMERCE</div>
                    </div>
                  </div>
                  <p>Manage:</p>
                  <ul>
                    <li>Product sales</li>
                    <li>Marketplace fees</li>
                    <li>Advertising costs</li>
                    <li>Inventory expenses</li>
                    <li>Profit margins</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for Shopify, Amazon, Etsy, and WooCommerce businesses.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">FR</div>
                    <div>
                      <h4>Freelancer Income Statement Template</h4>
                      <div className="industry-tagline">CONSULTING · CONTRACT · INDEPENDENT</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Client payments</li>
                    <li>Project revenue</li>
                    <li>Tax-deductible expenses</li>
                    <li>Operational costs</li>
                    <li>Monthly profitability</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Designed for consultants and independent professionals.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">SU</div>
                    <div>
                      <h4>Startup Financial Reporting Spreadsheet</h4>
                      <div className="industry-tagline">TECH · GROWTH · INVESTORS</div>
                    </div>
                  </div>
                  <p>Monitor:</p>
                  <ul>
                    <li>Revenue performance</li>
                    <li>Investor reporting</li>
                    <li>Operational expenses</li>
                    <li>Burn rate</li>
                    <li>Profitability growth</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for startup financial management and investor analysis.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINANCIAL REPORTS AND PROFITABILITY INSIGHTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Financial Reports and Profitability Insights</h2>
              <p className="intro">Every generated income statement system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte income statement spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Revenue summaries</li>
                <li>Expense analysis reports</li>
                <li>Gross profit dashboards</li>
                <li>Net income reports</li>
                <li>Profitability tracking summaries</li>
                <li>Operational cost reports</li>
                <li>Financial performance insights</li>
                <li>Accounting reporting dashboards</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into business profitability and operational performance.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Income Statement Spreadsheet vs. <span className="serif-accent">Manual</span> Financial Reporting</h2>
              <p className="intro">Seven dimensions where AI-powered income statements outperform manual financial work.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual Financial Reporting</div>
                  <h3>Manual financial organization</h3>
                  <ul>
                    <li>Manual profit calculations</li>
                    <li>Inconsistent revenue organization</li>
                    <li>Limited financial visibility</li>
                    <li>Error-prone reporting accuracy</li>
                    <li>Time-consuming spreadsheet setup</li>
                    <li>Manual accounting processes</li>
                    <li>Limited business customization</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>AI-generated spreadsheets</h3>
                  <ul>
                    <li>Automated profit calculations</li>
                    <li>Structured revenue organization</li>
                    <li>Dashboard-based financial visibility</li>
                    <li>High reporting accuracy</li>
                    <li>Fast spreadsheet setup</li>
                    <li>Automated accounting workflow</li>
                    <li>High business customization</li>
                  </ul>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify financial reporting and profitability analysis.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">Income Statement</span> Templates</h2>
              <p className="intro">Faster setup, accurate calculations, better visibility — every profit already analyzed.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster Financial Reporting</h3>
                  <p>Generate complete income statement systems instantly without manually creating spreadsheets.</p>
                </div>
                <div className="benefit-card">
                  <h3>Better Profitability Visibility</h3>
                  <p>Structured financial reports improve revenue and expense analysis.</p>
                </div>
                <div className="benefit-card">
                  <h3>Reduced Accounting Errors</h3>
                  <p>Automated formulas reduce financial calculation mistakes and reporting inconsistencies.</p>
                </div>
                <div className="benefit-card">
                  <h3>Improved Financial Planning</h3>
                  <p>Profitability dashboards help businesses make smarter budgeting and operational decisions.</p>
                </div>
                <div className="benefit-card">
                  <h3>Easier Business Analysis</h3>
                  <p>Financial reporting systems simplify operational analysis and strategic planning.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing <span className="serif-accent">Income Statement</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated income statement into a real financial reporting tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Update Financial Data Regularly</h3>
                  <p>Consistent updates improve reporting accuracy and financial visibility.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Organize Revenue and Expenses Properly</h3>
                  <p>Structured categories improve profitability analysis and reporting quality.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Review Financial Reports Monthly</h3>
                  <p>Regular reviews help identify profitability trends, expense growth, revenue opportunities, operational inefficiencies, and financial risks.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Maintain Accurate Accounting Records</h3>
                  <p>Consistent accounting practices improve financial reporting reliability and business transparency.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most income statement templates are static spreadsheets with limited flexibility.</p>
            </div>
            <div className="row-body">
              <p>Most income statement templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated financial reporting systems tailored to your accounting workflow, revenue structure, and profitability analysis requirements.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Income statements</li>
                <li>Profitability dashboards</li>
                <li>Revenue tracking systems</li>
                <li>Expense management sheets</li>
                <li>Gross profit reports</li>
                <li>Net income summaries</li>
                <li>Financial analysis dashboards</li>
                <li>AI-powered accounting workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually building financial reports, Formula Byte automates income statement spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This <span className="serif-accent">Income Statement</span> Spreadsheet?</h2>
              <p className="intro">This spreadsheet solution is ideal for businesses and professionals managing financial reporting and accounting.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>Accountants</h4></div>
                <div className="audience-cell"><h4>Startups</h4></div>
                <div className="audience-cell"><h4>Ecommerce brands</h4></div>
                <div className="audience-cell"><h4>Financial analysts</h4></div>
                <div className="audience-cell"><h4>Agencies</h4></div>
                <div className="audience-cell"><h4>Consultants</h4></div>
                <div className="audience-cell"><h4>Finance managers</h4></div>
                <div className="audience-cell"><h4>Business owners</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple profit tracking or advanced financial analysis, Formula Byte helps automate income statement spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating income statement templates with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet calculate profits automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates income statement spreadsheets with automated revenue tracking, expense calculations, and net income analysis.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include profitability dashboards?</summary>
                  <div className="faq-a">Yes. Income statement templates can include financial dashboards, gross profit summaries, and reporting visuals.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize financial categories and layouts?</summary>
                  <div className="faq-a">Absolutely. Revenue sections, expense categories, reporting periods, and accounting structures can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte income statement templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for small business financial reporting?</summary>
                  <div className="faq-a">Yes. Small businesses commonly use income statement spreadsheets for accounting, profitability analysis, budgeting, and financial reporting.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other business templates you might need.</h2>
              <p className="intro">Same engine, different business workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/expense-report-template/" className="related-card">
                  <div className="glyph">E</div>
                  <h4>Expense Report</h4>
                  <p>Track spending, reimbursements, and budgets.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/balance-sheet-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Balance Sheet</h4>
                  <p>Assets, liabilities, and equity reporting.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/business-budget-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Business Budget</h4>
                  <p>Company budgeting and expense planning.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/crm-template/" className="related-card">
                  <div className="glyph">C</div>
                  <h4>CRM Template</h4>
                  <p>Manage customers, sales, and relationships.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">Income Statement</span> Spreadsheet?</h2>
            <p>Stop creating financial reports manually.</p>
            <p>Describe your accounting workflow, and Formula Byte will generate a professional AI-powered Excel income statement template with profitability dashboards, revenue tracking systems, expense analysis tools, financial summaries, and organized accounting workflows in seconds.</p>
            <p>Create smarter financial reporting spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}
