import React from 'react';

export default function InventoryTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=business">Business</a>
            <span className="sep">/</span>
            <span className="current">Inventory</span>
          </div>

          <div className="eyebrow">Business template</div>
          <h1>AI Excel Inventory Template for Stock Tracking and <span className="accent">Inventory Management</span></h1>
          <p className="lede">
            Track stock levels, product details, supplier information, and reorder points with an AI-generated Excel inventory template designed for smarter inventory management and stock control. Formula Byte helps businesses automate inventory tracking using intelligent spreadsheets with inventory dashboards, product databases, stock monitoring systems, and reorder management workflows.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>16</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate inventory spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Ecommerce stores</span>
          <span className="use-case-pill"><span className="dot"></span>Retail shops</span>
          <span className="use-case-pill"><span className="dot"></span>Warehouses</span>
          <span className="use-case-pill"><span className="dot"></span>Manufacturers</span>
          <span className="use-case-pill"><span className="dot"></span>Distributors</span>
          <span className="use-case-pill"><span className="dot"></span>Supply chain teams</span>
          <span className="use-case-pill"><span className="dot"></span>Product inventory management</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Inventory-Tracker<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">I7</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=IF</span>(<span className="num">E7</span><span className="op">&lt;=</span><span className="num">F7</span>, <span className="str">"Reorder"</span>, <span className="str">"OK"</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header">F</div>
            <div className="preview-col-header">G</div>
            <div className="preview-col-header preview-hide-mobile">H</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Product Name</div>
            <div className="preview-cell preview-header-cell">SKU</div>
            <div className="preview-cell preview-header-cell">Category</div>
            <div className="preview-cell preview-header-cell">Supplier</div>
            <div className="preview-cell preview-header-cell">Stock Qty</div>
            <div className="preview-cell preview-header-cell">Reorder Pt</div>
            <div className="preview-cell preview-header-cell">Unit Cost</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Total Value</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">Wireless Mouse</div>
            <div className="preview-cell">WM-001</div>
            <div className="preview-cell">Electronics</div>
            <div className="preview-cell">TechSupply Co</div>
            <div className="preview-cell num">145</div>
            <div className="preview-cell num">50</div>
            <div className="preview-cell num">$8.50</div>
            <div className="preview-cell num preview-hide-mobile">$1,232.50</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">USB Keyboard</div>
            <div className="preview-cell">UK-002</div>
            <div className="preview-cell">Electronics</div>
            <div className="preview-cell">TechSupply Co</div>
            <div className="preview-cell num selected">42</div>
            <div className="preview-cell num">50</div>
            <div className="preview-cell num">$15.00</div>
            <div className="preview-cell num preview-hide-mobile">$630.00</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">Monitor Stand</div>
            <div className="preview-cell">MS-003</div>
            <div className="preview-cell">Accessories</div>
            <div className="preview-cell">OfficeDepot</div>
            <div className="preview-cell num">28</div>
            <div className="preview-cell num">25</div>
            <div className="preview-cell num">$22.00</div>
            <div className="preview-cell num preview-hide-mobile">$616.00</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">Webcam HD</div>
            <div className="preview-cell">WC-004</div>
            <div className="preview-cell">Electronics</div>
            <div className="preview-cell">MediaTech Inc</div>
            <div className="preview-cell num">67</div>
            <div className="preview-cell num">30</div>
            <div className="preview-cell num">$35.00</div>
            <div className="preview-cell num preview-hide-mobile">$2,345.00</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Desk Lamp</div>
            <div className="preview-cell">DL-005</div>
            <div className="preview-cell">Lighting</div>
            <div className="preview-cell">HomeGoods Plus</div>
            <div className="preview-cell num">93</div>
            <div className="preview-cell num">40</div>
            <div className="preview-cell num">$18.00</div>
            <div className="preview-cell num preview-hide-mobile">$1,674.00</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">Office Chair</div>
            <div className="preview-cell">OC-006</div>
            <div className="preview-cell">Furniture</div>
            <div className="preview-cell">FurnitureWorld</div>
            <div className="preview-cell num">15</div>
            <div className="preview-cell num">20</div>
            <div className="preview-cell num">$125.00</div>
            <div className="preview-cell num preview-hide-mobile">$1,875.00</div>

            {/* Row 8 */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text">Laptop Sleeve</div>
            <div className="preview-cell">LS-007</div>
            <div className="preview-cell">Accessories</div>
            <div className="preview-cell">CasePro</div>
            <div className="preview-cell num">112</div>
            <div className="preview-cell num">45</div>
            <div className="preview-cell num">$12.00</div>
            <div className="preview-cell num preview-hide-mobile">$1,344.00</div>

            {/* Empty rows */}
            {Array.from({length: 4}).map((_, i) => (
              <React.Fragment key={`empty-${i}`}>
                <div className="preview-row-num">{9 + i}</div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell preview-hide-mobile"></div>
              </React.Fragment>
            ))}

            {/* Status bar */}
            <div className="preview-status">
              <div className="preview-status-item">
                <span>Total Products:</span>
                <span className="val">7</span>
              </div>
              <div className="preview-status-item">
                <span>Low Stock:</span>
                <span className="val">2</span>
              </div>
              <div className="preview-status-item">
                <span>Total Value:</span>
                <span className="val">$9,716.50</span>
              </div>
              <div className="preview-status-spacer"></div>
              <div className="preview-status-tabs">
                <button className="preview-tab active">Inventory</button>
                <button className="preview-tab">Products</button>
                <button className="preview-tab">Suppliers</button>
                <button className="preview-tab">Dashboard</button>
                <button className="preview-tab">+4</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* CREATE AN AI INVENTORY SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Inventory Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the inventory spreadsheet you need, and Formula Byte automatically generates a professional Excel inventory template with:</p>
            </div>
            <div className="row-body">
              <ul className="bulleted">
                <li>Stock tracking systems</li>
                <li>Product management databases</li>
                <li>SKU organization</li>
                <li>Supplier tracking</li>
                <li>Reorder point monitoring</li>
                <li>Inventory valuation</li>
                <li>Inventory dashboards</li>
                <li>Automated spreadsheet formulas</li>
                <li>Stock movement reporting</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually managing inventory records, Formula Byte creates AI-powered inventory systems tailored to your operational workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel Inventory Template?</h2>
              <p className="intro">A structured spreadsheet used to organize and monitor stock levels, product details, supplier information, and inventory movement.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel inventory template</strong> is a structured spreadsheet used to organize and monitor stock levels, product details, supplier information, and inventory movement. It helps businesses maintain accurate inventory records while improving stock visibility and operational efficiency.
              </p>
              <p>
                An inventory spreadsheet typically includes:
              </p>
              <ul className="bulleted">
                <li>Product names</li>
                <li>SKU tracking</li>
                <li>Stock quantities</li>
                <li>Supplier information</li>
                <li>Reorder levels</li>
                <li>Cost prices</li>
                <li>Selling prices</li>
                <li>Inventory value calculations</li>
                <li>Stock movement reports</li>
              </ul>
              <p>Formula Byte generates AI-powered inventory spreadsheets designed for inventory control, stock tracking, and warehouse organization.</p>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How Inventory Management Works</h2>
              <p className="intro">Inventory management is the process of tracking, organizing, and controlling stock movement across purchasing, storage, and sales operations.</p>
            </div>
            <div className="row-body">
              <p>Inventory management is the process of tracking, organizing, and controlling stock movement across purchasing, storage, and sales operations.</p>
              <p style={{marginTop: '18px'}}>A structured inventory system helps businesses:</p>
              <ul className="bulleted">
                <li>Monitor stock levels</li>
                <li>Prevent stock shortages</li>
                <li>Reduce overstocking</li>
                <li>Improve warehouse organization</li>
                <li>Track supplier performance</li>
                <li>Manage product movement</li>
                <li>Optimize inventory operations</li>
              </ul>
              <p style={{marginTop: '18px'}}>Most inventory systems include:</p>
              <ul className="bulleted">
                <li>Stock tracking</li>
                <li>SKU management</li>
                <li>Supplier databases</li>
                <li>Reorder point monitoring</li>
                <li>Inventory valuation</li>
                <li>Product categorization</li>
                <li>Warehouse organization</li>
              </ul>
              <p style={{marginTop: '18px'}}>Formula Byte simplifies this process using AI-generated inventory spreadsheets and automated stock management systems.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY BUSINESSES NEED INVENTORY TRACKING SYSTEMS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Businesses Need Inventory Tracking Systems</h2>
              <p className="intro">Managing inventory without a structured system often creates stock shortages and operational inefficiencies.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without inventory tracking</div>
                  <h3>Managing inventory without a structured system often creates:</h3>
                  <ul>
                    <li>Stock shortages</li>
                    <li>Overstocking problems</li>
                    <li>Inventory calculation errors</li>
                    <li>Supplier tracking issues</li>
                    <li>Warehouse confusion</li>
                    <li>Lost product visibility</li>
                    <li>Operational inefficiencies</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With inventory tracking</div>
                  <h3>A properly organized inventory spreadsheet helps businesses:</h3>
                  <ul>
                    <li>Improve stock visibility</li>
                    <li>Track inventory movement</li>
                    <li>Organize supplier information</li>
                    <li>Maintain reorder accuracy</li>
                    <li>Reduce inventory waste</li>
                    <li>Improve purchasing decisions</li>
                    <li>Optimize operational workflows</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI <span className="serif-accent">Inventory</span> Spreadsheet</h2>
              <p className="intro">Four pillars of inventory management — automatic, organized, and built to support real stock tracking needs.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">S</div>
                  <h3>Stock Level Tracking</h3>
                  <p>Track all inventory quantities with automatic stock organization and structured inventory layouts.</p>
                  <ul>
                    <li>Product quantities</li>
                    <li>Available inventory</li>
                    <li>Incoming stock</li>
                    <li>Outgoing stock</li>
                    <li>Low stock alerts</li>
                    <li>Warehouse inventory</li>
                    <li>Product availability</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>The spreadsheet automatically organizes stock records into structured inventory layouts.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">P</div>
                  <h3>Product and SKU Management</h3>
                  <p>Monitor all product information with organized SKU tracking systems.</p>
                  <ul>
                    <li>Product names</li>
                    <li>SKU numbers</li>
                    <li>Product categories</li>
                    <li>Inventory descriptions</li>
                    <li>Product pricing</li>
                    <li>Barcode references</li>
                    <li>Product variations</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This improves inventory organization and product visibility.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">U</div>
                  <h3>Supplier Information Tracking</h3>
                  <p>Formula Byte inventory spreadsheets can include comprehensive supplier management systems.</p>
                  <ul>
                    <li>Supplier names</li>
                    <li>Contact information</li>
                    <li>Vendor records</li>
                    <li>Lead times</li>
                    <li>Purchase tracking</li>
                    <li>Supplier categories</li>
                    <li>Pricing agreements</li>
                    <li>Delivery schedules</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Structured supplier management improves inventory coordination and purchasing workflows.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">R</div>
                  <h3>Reorder Point Monitoring</h3>
                  <p>Track inventory thresholds with comprehensive reorder management and reporting tools.</p>
                  <ul>
                    <li>Minimum stock levels</li>
                    <li>Reorder alerts</li>
                    <li>Inventory thresholds</li>
                    <li>Purchase planning</li>
                    <li>Restocking schedules</li>
                    <li>Inventory forecasting</li>
                    <li>Stock availability</li>
                    <li>Reorder urgency</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This helps businesses maintain efficient stock availability and prevent shortages.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI INVENTORY MANAGEMENT AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Inventory Management Automation for Stock Tracking</h2>
              <p className="intro">Skip the manual setup. The AI understands inventory management instructions from natural language prompts.</p>
            </div>
            <div className="row-body">
              <p>Traditional inventory spreadsheets require manual formatting and repetitive stock updates.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure inventory databases</li>
                <li>Generate stock tracking systems</li>
                <li>Organize SKU management</li>
                <li>Create inventory dashboards</li>
                <li>Build reorder tracking systems</li>
                <li>Generate valuation summaries</li>
                <li>Apply spreadsheet formatting</li>
                <li>Automate inventory workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands inventory management instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a retail inventory tracking spreadsheet"</button>
                  <button className="chip">"Build a warehouse stock management dashboard"</button>
                  <button className="chip">"Generate an ecommerce inventory template"</button>
                  <button className="chip">"Create a supplier and reorder tracking system"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Inventory Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete inventory spreadsheet with 8 worksheets — each generated, formatted, and wired up automatically.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Inventory Tracker</span>
                  <span className="spec-purpose">Monitors stock levels</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Product Database</span>
                  <span className="spec-purpose">Organizes product records</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">SKU Management Sheet</span>
                  <span className="spec-purpose">Tracks product identifiers</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Supplier Directory</span>
                  <span className="spec-purpose">Stores vendor information</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Reorder Point Tracker</span>
                  <span className="spec-purpose">Monitors inventory thresholds</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Inventory Dashboard</span>
                  <span className="spec-purpose">Visualizes stock activity</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Stock Movement Report</span>
                  <span className="spec-purpose">Tracks inventory changes</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Inventory Valuation Sheet</span>
                  <span className="spec-purpose">Calculates inventory value</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* INVENTORY CATEGORIES INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Data included</div>
              <h2>Inventory <span className="serif-accent">Categories</span> Included</h2>
              <p className="intro">Every inventory tracking category you need — pre-built, organized, and ready for instant inventory management.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte inventory spreadsheets include comprehensive inventory management categories:</p>
              <ul className="bulleted">
                <li><strong>Product inventory tracking:</strong> Retail products, warehouse inventory, ecommerce stock, raw materials, finished goods, product variations</li>
                <li><strong>Supplier and purchasing management:</strong> Vendor information, purchase records, supplier lead times, product sourcing, restocking workflows</li>
                <li><strong>Warehouse and stock organization:</strong> Storage locations, inventory movement, product availability, warehouse organization, stock distribution</li>
              </ul>
              <p style={{marginTop: '18px'}}>These categories provide a complete foundation for inventory organization and stock tracking.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Built-in automation</div>
              <h2>Built-In <span className="serif-accent">Inventory</span> Formulas</h2>
              <p className="intro">No manual calculations. All formulas are wired, tested, and ready to use.</p>
            </div>
            <div className="row-body">
              <p>Every inventory spreadsheet includes built-in formulas for automatic stock calculations:</p>
              <ul className="bulleted">
                <li><strong>Total inventory value:</strong> =SUM(Stock Quantity × Unit Cost)</li>
                <li><strong>Low stock alert:</strong> =IF(Stock Qty ≤ Reorder Point, "Reorder", "OK")</li>
                <li><strong>Stock movement:</strong> =Previous Stock - Sales + New Purchases</li>
                <li><strong>Reorder urgency:</strong> =IF(Stock Qty &lt; Reorder Point × 0.5, "Urgent", "Normal")</li>
                <li><strong>Inventory turnover:</strong> = (Cost of Goods Sold / Average Inventory)</li>
                <li><strong>Days of stock remaining:</strong> = Current Stock / Daily Sales Rate</li>
                <li><strong>Total products:</strong> =COUNTA(Product Range)</li>
                <li><strong>Category summary:</strong> =SUMIF(Category, "Electronics", Value)</li>
              </ul>
              <p style={{marginTop: '18px'}}>These formulas automate complex inventory calculations, reducing manual effort and improving accuracy.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Inventory Templates by <span className="serif-accent">Business</span> Type</h2>
              <p className="intro">Customize the inventory template for any business — same structure, different focus.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">SB</div>
                    <div>
                      <h4>Small Business Inventory Spreadsheet</h4>
                      <div className="industry-tagline">BUSINESS · STOCK · RETAIL</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Product inventory</li>
                    <li>Supplier details</li>
                    <li>Stock movement</li>
                    <li>Inventory valuation</li>
                    <li>Reorder alerts</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Ideal for startups and growing businesses.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">EC</div>
                    <div>
                      <h4>Ecommerce Inventory Template</h4>
                      <div className="industry-tagline">ONLINE · STORE · SALES</div>
                    </div>
                  </div>
                  <p>Manage:</p>
                  <ul>
                    <li>Product listings</li>
                    <li>Marketplace stock</li>
                    <li>Inventory forecasting</li>
                    <li>Order fulfillment</li>
                    <li>Warehouse inventory</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for Shopify, Amazon, Etsy, and WooCommerce businesses.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">WH</div>
                    <div>
                      <h4>Warehouse Inventory Management Spreadsheet</h4>
                      <div className="industry-tagline">STORAGE · LOGISTICS · BULK</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Bulk inventory</li>
                    <li>Storage locations</li>
                    <li>Product movement</li>
                    <li>Supplier shipments</li>
                    <li>Operational inventory</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Designed for warehouses and distribution centers.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">RT</div>
                    <div>
                      <h4>Retail Stock Tracking Template</h4>
                      <div className="industry-tagline">RETAIL · STORE · SALES</div>
                    </div>
                  </div>
                  <p>Monitor:</p>
                  <ul>
                    <li>Store inventory</li>
                    <li>Product availability</li>
                    <li>Sales inventory movement</li>
                    <li>Reorder planning</li>
                    <li>Inventory performance</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for retail operations and product management.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* INVENTORY REPORTS AND STOCK INSIGHTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Inventory Reports and Stock Insights</h2>
              <p className="intro">Every generated inventory system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte inventory spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Stock summaries</li>
                <li>Inventory valuation reports</li>
                <li>Product movement dashboards</li>
                <li>Supplier analysis reports</li>
                <li>Reorder tracking summaries</li>
                <li>Inventory performance insights</li>
                <li>Warehouse stock reports</li>
                <li>Inventory forecasting dashboards</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into stock operations and inventory performance.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Inventory Spreadsheet vs. <span className="serif-accent">Manual</span> Inventory Tracking</h2>
              <p className="intro">Seven dimensions where AI-powered inventory spreadsheets outperform manual stock management.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual Inventory Tracking</div>
                  <h3>Manual inventory organization</h3>
                  <ul>
                    <li>Inconsistent stock organization</li>
                    <li>Limited inventory visibility</li>
                    <li>Manual reorder monitoring</li>
                    <li>Error-prone inventory accuracy</li>
                    <li>Time-consuming spreadsheet setup</li>
                    <li>Difficult supplier management</li>
                    <li>Limited inventory forecasting</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>AI-generated spreadsheets</h3>
                  <ul>
                    <li>Structured stock organization</li>
                    <li>Dashboard-based inventory visibility</li>
                    <li>Automated reorder monitoring</li>
                    <li>High inventory accuracy</li>
                    <li>Fast spreadsheet setup</li>
                    <li>Organized supplier management</li>
                    <li>Included inventory forecasting</li>
                  </ul>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify inventory management and stock control.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">Inventory</span> Templates</h2>
              <p className="intro">Faster setup, accurate tracking, better visibility — every stock already organized.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster Inventory Setup</h3>
                  <p>Generate complete inventory management systems instantly without manually building spreadsheets.</p>
                </div>
                <div className="benefit-card">
                  <h3>Better Stock Visibility</h3>
                  <p>Structured inventory layouts improve product tracking and operational visibility.</p>
                </div>
                <div className="benefit-card">
                  <h3>Reduced Inventory Errors</h3>
                  <p>Automated formulas reduce stock calculation mistakes and inventory inconsistencies.</p>
                </div>
                <div className="benefit-card">
                  <h3>Improved Purchasing Decisions</h3>
                  <p>Inventory dashboards help businesses monitor stock trends and reorder requirements more effectively.</p>
                </div>
                <div className="benefit-card">
                  <h3>Easier Warehouse Organization</h3>
                  <p>Centralized inventory systems improve storage management and operational efficiency.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing <span className="serif-accent">Inventory</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated inventory into a real stock management tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Update Inventory Records Regularly</h3>
                  <p>Consistent updates improve inventory accuracy and stock visibility.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Monitor Reorder Levels Closely</h3>
                  <p>Tracking reorder points helps prevent stock shortages and operational disruptions.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Organize Products by Category</h3>
                  <p>Structured product categorization improves inventory management and reporting quality.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Conduct Inventory Audits Frequently</h3>
                  <p>Regular inventory reviews help identify stock discrepancies, overstocking issues, product shortages, supplier delays, and inventory optimization opportunities.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most inventory templates are static spreadsheets with limited flexibility.</p>
            </div>
            <div className="row-body">
              <p>Most inventory templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated inventory management systems tailored to your stock workflow, warehouse organization, and supplier management requirements.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Stock tracking systems</li>
                <li>SKU management sheets</li>
                <li>Inventory dashboards</li>
                <li>Supplier databases</li>
                <li>Reorder monitoring systems</li>
                <li>Inventory valuation reports</li>
                <li>Warehouse tracking tools</li>
                <li>AI-powered inventory workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing stock records, Formula Byte automates inventory spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This <span className="serif-accent">Inventory</span> Spreadsheet?</h2>
              <p className="intro">This spreadsheet solution is ideal for businesses and professionals managing inventory and stock operations.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>Ecommerce brands</h4></div>
                <div className="audience-cell"><h4>Retail stores</h4></div>
                <div className="audience-cell"><h4>Warehouses</h4></div>
                <div className="audience-cell"><h4>Manufacturers</h4></div>
                <div className="audience-cell"><h4>Distributors</h4></div>
                <div className="audience-cell"><h4>Supply chain teams</h4></div>
                <div className="audience-cell"><h4>Inventory managers</h4></div>
                <div className="audience-cell"><h4>Operations teams</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple stock tracking or advanced inventory management, Formula Byte helps automate inventory spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating inventory templates with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet track inventory levels automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates inventory spreadsheets with automated stock tracking, reorder monitoring, and inventory calculations.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include supplier and SKU management?</summary>
                  <div className="faq-a">Yes. Inventory templates can include supplier databases, SKU tracking systems, and product categorization workflows.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize inventory categories and layouts?</summary>
                  <div className="faq-a">Absolutely. Product categories, warehouse sections, supplier records, and reporting structures can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte inventory templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for ecommerce and warehouse inventory management?</summary>
                  <div className="faq-a">Yes. Businesses commonly use inventory spreadsheets for stock tracking, warehouse organization, ecommerce inventory management, and supplier coordination.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other business templates you might need.</h2>
              <p className="intro">Same engine, different business workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/income-statement-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Income Statement</h4>
                  <p>Track revenue, expenses, and profit.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/expense-report-template/" className="related-card">
                  <div className="glyph">E</div>
                  <h4>Expense Report</h4>
                  <p>Track spending and reimbursements.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/balance-sheet-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Balance Sheet</h4>
                  <p>Assets, liabilities, and equity.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/purchase-order-template/" className="related-card">
                  <div className="glyph">P</div>
                  <h4>Purchase Order</h4>
                  <p>Manage supplier purchases and orders.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">Inventory</span> Spreadsheet?</h2>
            <p>Stop managing inventory manually.</p>
            <p>Describe your inventory workflow, and Formula Byte will generate a professional AI-powered Excel inventory template with stock tracking systems, SKU management tools, inventory dashboards, supplier databases, and organized warehouse workflows in seconds.</p>
            <p>Create smarter inventory management spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}
