import React from 'react';

export default function InvoiceTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=business">Business</a>
            <span className="sep">/</span>
            <span className="current">Invoice</span>
          </div>

          <div className="eyebrow">Business template</div>
          <h1>AI Excel Invoice Template for Billing and <span className="accent">Payment Management</span></h1>
          <p className="lede">
            Create professional invoices, organize customer information, track payments, and manage billing workflows with an AI-generated Excel invoice template designed for smarter financial operations. Formula Byte helps businesses automate invoicing using intelligent spreadsheets with payment tracking systems, invoice summaries, tax calculations, and customizable billing workflows.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>7</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>14</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate invoice spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Freelancers</span>
          <span className="use-case-pill"><span className="dot"></span>Agencies</span>
          <span className="use-case-pill"><span className="dot"></span>Ecommerce stores</span>
          <span className="use-case-pill"><span className="dot"></span>Consultants</span>
          <span className="use-case-pill"><span className="dot"></span>Contractors</span>
          <span className="use-case-pill"><span className="dot"></span>Service providers</span>
          <span className="use-case-pill"><span className="dot"></span>Financial operations teams</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Invoice-Template<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">G7</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=E7</span><span className="op">*</span><span className="num">F7</span>
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header">F</div>
            <div className="preview-col-header">G</div>
            <div className="preview-col-header preview-hide-mobile">H</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Item</div>
            <div className="preview-cell preview-header-cell">Description</div>
            <div className="preview-cell preview-header-cell">Qty</div>
            <div className="preview-cell preview-header-cell">Unit Price</div>
            <div className="preview-cell preview-header-cell">Tax Rate</div>
            <div className="preview-cell preview-header-cell">Total</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Status</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">Web Design Service</div>
            <div className="preview-cell">Homepage redesign project</div>
            <div className="preview-cell num">1</div>
            <div className="preview-cell num">$2,500.00</div>
            <div className="preview-cell num">8%</div>
            <div className="preview-cell num">$2,700.00</div>
            <div className="preview-cell preview-hide-mobile">Paid</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">SEO Consulting</div>
            <div className="preview-cell">Monthly SEO optimization</div>
            <div className="preview-cell num">1</div>
            <div className="preview-cell num">$800.00</div>
            <div className="preview-cell num">8%</div>
            <div className="preview-cell num selected">$864.00</div>
            <div className="preview-cell preview-hide-mobile">Pending</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">Content Writing</div>
            <div className="preview-cell">5 blog articles (1000 words each)</div>
            <div className="preview-cell num">5</div>
            <div className="preview-cell num">$150.00</div>
            <div className="preview-cell num">8%</div>
            <div className="preview-cell num">$810.00</div>
            <div className="preview-cell preview-hide-mobile">Paid</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">Logo Design</div>
            <div className="preview-cell">Brand identity package</div>
            <div className="preview-cell num">1</div>
            <div className="preview-cell num">$1,200.00</div>
            <div className="preview-cell num">8%</div>
            <div className="preview-cell num">$1,296.00</div>
            <div className="preview-cell preview-hide-mobile">Paid</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Hosting Setup</div>
            <div className="preview-cell">Server configuration and deployment</div>
            <div className="preview-cell num">1</div>
            <div className="preview-cell num">$350.00</div>
            <div className="preview-cell num">8%</div>
            <div className="preview-cell num">$378.00</div>
            <div className="preview-cell preview-hide-mobile">Paid</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">Monthly Support</div>
            <div className="preview-cell">3-month technical support package</div>
            <div className="preview-cell num">3</div>
            <div className="preview-cell num">$200.00</div>
            <div className="preview-cell num">8%</div>
            <div className="preview-cell num">$648.00</div>
            <div className="preview-cell preview-hide-mobile">Pending</div>

            {/* Row 8 */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text">Analytics Setup</div>
            <div className="preview-cell">Google Analytics configuration</div>
            <div className="preview-cell num">1</div>
            <div className="preview-cell num">$250.00</div>
            <div className="preview-cell num">8%</div>
            <div className="preview-cell num">$270.00</div>
            <div className="preview-cell preview-hide-mobile">Paid</div>

            {/* Empty rows */}
            {Array.from({length: 4}).map((_, i) => (
              <React.Fragment key={`empty-${i}`}>
                <div className="preview-row-num">{9 + i}</div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell preview-hide-mobile"></div>
              </React.Fragment>
            ))}

            {/* Status bar */}
            <div className="preview-status">
              <div className="preview-status-item">
                <span>Subtotal:</span>
                <span className="val">$5,450.00</span>
              </div>
              <div className="preview-status-item">
                <span>Tax (8%):</span>
                <span className="val">$436.00</span>
              </div>
              <div className="preview-status-item">
                <span>Total:</span>
                <span className="val">$6,966.00</span>
              </div>
              <div className="preview-status-spacer"></div>
              <div className="preview-status-tabs">
                <button className="preview-tab active">Invoice</button>
                <button className="preview-tab">Customers</button>
                <button className="preview-tab">Payments</button>
                <button className="preview-tab">Reports</button>
                <button className="preview-tab">+3</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* CREATE AN AI INVOICE SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Invoice Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the invoice spreadsheet you need, and Formula Byte automatically generates a professional Excel invoice template with:</p>
            </div>
            <div className="row-body">
              <ul className="bulleted">
                <li>Customer information management</li>
                <li>Invoice numbering systems</li>
                <li>Product and service billing</li>
                <li>Tax calculations</li>
                <li>Payment tracking</li>
                <li>Due date monitoring</li>
                <li>Invoice summaries</li>
                <li>Automated spreadsheet formulas</li>
                <li>Billing workflow organization</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually creating invoices, Formula Byte builds AI-powered invoicing systems tailored to your business workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel Invoice Template?</h2>
              <p className="intro">A structured spreadsheet used to create, organize, and track invoices for products or services.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel invoice template</strong> is a structured spreadsheet used to create, organize, and track invoices for products or services. It helps businesses maintain accurate billing records while improving payment management and financial organization.
              </p>
              <p>
                An invoice spreadsheet typically includes:
              </p>
              <ul className="bulleted">
                <li>Business information</li>
                <li>Customer details</li>
                <li>Invoice numbers</li>
                <li>Product or service descriptions</li>
                <li>Quantity tracking</li>
                <li>Unit pricing</li>
                <li>Tax calculations</li>
                <li>Payment terms</li>
                <li>Total amount summaries</li>
              </ul>
              <p>Formula Byte generates AI-powered invoice spreadsheets designed for billing management, payment tracking, and financial reporting workflows.</p>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How Invoice Management Works</h2>
              <p className="intro">Invoice management is the process of creating billing documents, tracking payments, organizing customer transactions, and maintaining financial records.</p>
            </div>
            <div className="row-body">
              <p>Invoice management is the process of creating billing documents, tracking payments, organizing customer transactions, and maintaining financial records.</p>
              <p style={{marginTop: '18px'}}>A structured invoicing system helps businesses:</p>
              <ul className="bulleted">
                <li>Generate professional invoices</li>
                <li>Track outstanding payments</li>
                <li>Organize customer billing</li>
                <li>Improve cash flow visibility</li>
                <li>Reduce payment delays</li>
                <li>Maintain accounting accuracy</li>
                <li>Simplify financial reporting</li>
              </ul>
              <p style={{marginTop: '18px'}}>Most invoicing systems include:</p>
              <ul className="bulleted">
                <li>Invoice creation</li>
                <li>Customer databases</li>
                <li>Payment tracking</li>
                <li>Tax reporting</li>
                <li>Billing summaries</li>
                <li>Due date monitoring</li>
                <li>Revenue tracking</li>
              </ul>
              <p style={{marginTop: '18px'}}>Formula Byte simplifies this process using AI-generated invoice spreadsheets and automated billing systems.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY BUSINESSES NEED INVOICE TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Businesses Need Invoice Templates</h2>
              <p className="intro">Managing invoices without a structured system often creates billing inconsistencies and payment tracking issues.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without invoice templates</div>
                  <h3>Managing invoices without a structured system often creates:</h3>
                  <ul>
                    <li>Billing inconsistencies</li>
                    <li>Missed payment tracking</li>
                    <li>Invoice calculation errors</li>
                    <li>Cash flow confusion</li>
                    <li>Delayed payments</li>
                    <li>Unorganized customer records</li>
                    <li>Financial reporting issues</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With invoice templates</div>
                  <h3>A properly organized invoice template helps businesses:</h3>
                  <ul>
                    <li>Improve billing efficiency</li>
                    <li>Track customer payments</li>
                    <li>Maintain professional invoicing</li>
                    <li>Organize transaction records</li>
                    <li>Simplify accounting workflows</li>
                    <li>Improve cash flow management</li>
                    <li>Reduce billing mistakes</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI <span className="serif-accent">Invoice</span> Spreadsheet</h2>
              <p className="intro">Four pillars of invoice management — automatic, organized, and built to support real billing needs.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">C</div>
                  <h3>Customer and Client Information Management</h3>
                  <p>Organize all customer billing details with automatic client categorization and structured invoice layouts.</p>
                  <ul>
                    <li>Customer names</li>
                    <li>Business details</li>
                    <li>Billing addresses</li>
                    <li>Email addresses</li>
                    <li>Phone numbers</li>
                    <li>Account references</li>
                    <li>Client records</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>The spreadsheet automatically organizes customer billing information into structured invoice layouts.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">P</div>
                  <h3>Product and Service Billing</h3>
                  <p>Monitor all billing items with organized product and service tracking systems.</p>
                  <ul>
                    <li>Product descriptions</li>
                    <li>Service details</li>
                    <li>Unit prices</li>
                    <li>Quantities</li>
                    <li>Discounts</li>
                    <li>Tax rates</li>
                    <li>Line item totals</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This improves billing visibility and transaction accuracy.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">I</div>
                  <h3>Invoice Number and Payment Tracking</h3>
                  <p>Formula Byte invoice spreadsheets can include comprehensive payment monitoring systems.</p>
                  <ul>
                    <li>Unique invoice numbering</li>
                    <li>Payment status tracking</li>
                    <li>Due date monitoring</li>
                    <li>Outstanding balance summaries</li>
                    <li>Paid and unpaid invoice logs</li>
                    <li>Billing history</li>
                    <li>Payment reminders</li>
                    <li>Client payment schedules</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Structured payment tracking improves cash flow visibility and invoice organization.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">T</div>
                  <h3>Tax and Total Calculations</h3>
                  <p>Track billing calculations with comprehensive tax management and financial reporting tools.</p>
                  <ul>
                    <li>Subtotals</li>
                    <li>Tax calculations</li>
                    <li>Discounts</li>
                    <li>Payment adjustments</li>
                    <li>Final invoice totals</li>
                    <li>Outstanding balances</li>
                    <li>Payment summaries</li>
                    <li>Revenue reports</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This helps businesses maintain accurate financial reporting and billing workflows.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI INVOICE AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Invoice Automation for Modern Businesses</h2>
              <p className="intro">Skip the manual setup. The AI understands invoicing instructions from natural language prompts.</p>
            </div>
            <div className="row-body">
              <p>Traditional invoice spreadsheets require manual formatting and repetitive calculations.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure invoice systems</li>
                <li>Generate billing layouts</li>
                <li>Organize customer databases</li>
                <li>Create payment tracking workflows</li>
                <li>Build financial dashboards</li>
                <li>Generate invoice summaries</li>
                <li>Apply spreadsheet formatting</li>
                <li>Automate billing calculations</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands invoicing instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a freelance invoice spreadsheet"</button>
                  <button className="chip">"Build a business billing dashboard"</button>
                  <button className="chip">"Generate a service invoice template"</button>
                  <button className="chip">"Create an invoice tracker with payment reminders"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Invoice Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete invoice spreadsheet with 7 worksheets — each generated, formatted, and wired up automatically.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Invoice Generator</span>
                  <span className="spec-purpose">Creates billing documents</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Customer Database</span>
                  <span className="spec-purpose">Stores client information</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Product and Service List</span>
                  <span className="spec-purpose">Organizes billing items</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Payment Tracker</span>
                  <span className="spec-purpose">Monitors payment status</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Invoice Summary Dashboard</span>
                  <span className="spec-purpose">Visualizes billing activity</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Tax Calculation Sheet</span>
                  <span className="spec-purpose">Tracks tax reporting</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Revenue Summary</span>
                  <span className="spec-purpose">Analyzes invoice income</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* INVOICE CATEGORIES INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Data included</div>
              <h2>Invoice <span className="serif-accent">Categories</span> Included</h2>
              <p className="intro">Every invoicing category you need — pre-built, organized, and ready for instant billing management.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte invoice spreadsheets include comprehensive billing management categories:</p>
              <ul className="bulleted">
                <li><strong>Product invoice management:</strong> Product sales, inventory billing, unit pricing, sales tax, order summaries, customer transactions</li>
                <li><strong>Service invoice tracking:</strong> Consulting invoices, freelance billing, agency retainers, project-based payments, hourly billing, service summaries</li>
                <li><strong>Payment and financial tracking:</strong> Invoice due dates, payment confirmations, outstanding balances, revenue summaries, client payment history</li>
              </ul>
              <p style={{marginTop: '18px'}}>These categories provide a complete foundation for invoice organization and billing management.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Built-in automation</div>
              <h2>Built-In <span className="serif-accent">Invoice</span> Formulas</h2>
              <p className="intro">No manual calculations. All formulas are wired, tested, and ready to use.</p>
            </div>
            <div className="row-body">
              <p>Every invoice spreadsheet includes built-in formulas for automatic billing calculations:</p>
              <ul className="bulleted">
                <li><strong>Line item total:</strong> =Quantity × Unit Price</li>
                <li><strong>Subtotal:</strong> =SUM(Line Item Totals)</li>
                <li><strong>Tax calculation:</strong> =Subtotal × Tax Rate</li>
                <li><strong>Discount amount:</strong> =Subtotal × Discount Percentage</li>
                <li><strong>Invoice total:</strong> =Subtotal + Tax - Discount</li>
                <li><strong>Balance due:</strong> =Invoice Total - Payment Received</li>
                <li><strong>Days overdue:</strong> =TODAY() - Due Date</li>
                <li><strong>Payment status:</strong> =IF(Balance Due = 0, "Paid", "Pending")</li>
              </ul>
              <p style={{marginTop: '18px'}}>These formulas automate complex billing calculations, reducing manual effort and improving accuracy.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Invoice Templates by <span className="serif-accent">Business</span> Type</h2>
              <p className="intro">Customize the invoice template for any business — same structure, different focus.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">SB</div>
                    <div>
                      <h4>Small Business Invoice Spreadsheet</h4>
                      <div className="industry-tagline">BUSINESS · BILLING · FINANCE</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Customer billing</li>
                    <li>Payment records</li>
                    <li>Product invoices</li>
                    <li>Financial summaries</li>
                    <li>Outstanding balances</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Ideal for startups and growing businesses.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">FR</div>
                    <div>
                      <h4>Freelancer Invoice Template</h4>
                      <div className="industry-tagline">CONSULTING · CONTRACT · INDEPENDENT</div>
                    </div>
                  </div>
                  <p>Manage:</p>
                  <ul>
                    <li>Client billing</li>
                    <li>Project payments</li>
                    <li>Service invoices</li>
                    <li>Payment due dates</li>
                    <li>Revenue tracking</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for freelancers and consultants.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">EC</div>
                    <div>
                      <h4>Ecommerce Billing Spreadsheet</h4>
                      <div className="industry-tagline">ONLINE · STORE · ORDERS</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Product orders</li>
                    <li>Customer payments</li>
                    <li>Tax calculations</li>
                    <li>Invoice records</li>
                    <li>Revenue summaries</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Designed for Shopify, WooCommerce, and online stores.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">AG</div>
                    <div>
                      <h4>Agency Invoice Dashboard</h4>
                      <div className="industry-tagline">AGENCY · SERVICE · RETAINER</div>
                    </div>
                  </div>
                  <p>Monitor:</p>
                  <ul>
                    <li>Client retainers</li>
                    <li>Service billing</li>
                    <li>Team invoicing</li>
                    <li>Revenue reports</li>
                    <li>Payment tracking</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for agencies and service-based businesses.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINANCIAL REPORTS AND BILLING INSIGHTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Financial Reports and Billing Insights</h2>
              <p className="intro">Every generated invoice system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte invoice spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Invoice summaries</li>
                <li>Revenue reports</li>
                <li>Payment tracking dashboards</li>
                <li>Outstanding balance reports</li>
                <li>Customer billing insights</li>
                <li>Tax reporting summaries</li>
                <li>Financial performance dashboards</li>
                <li>Billing workflow reports</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into invoicing operations and payment management.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Invoice Spreadsheet vs. <span className="serif-accent">Manual</span> Billing</h2>
              <p className="intro">Seven dimensions where AI-powered invoice spreadsheets outperform manual billing work.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual Billing</div>
                  <h3>Manual invoice organization</h3>
                  <ul>
                    <li>Manual invoice calculations</li>
                    <li>Difficult payment tracking</li>
                    <li>Error-prone billing accuracy</li>
                    <li>Inconsistent customer management</li>
                    <li>Time-consuming spreadsheet setup</li>
                    <li>Limited financial visibility</li>
                    <li>Limited workflow customization</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>AI-generated spreadsheets</h3>
                  <ul>
                    <li>Automated invoice calculations</li>
                    <li>Organized payment tracking</li>
                    <li>High billing accuracy</li>
                    <li>Structured customer management</li>
                    <li>Fast spreadsheet setup</li>
                    <li>Dashboard-based financial visibility</li>
                    <li>High workflow customization</li>
                  </ul>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify invoicing and billing management.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">Invoice</span> Templates</h2>
              <p className="intro">Faster creation, accurate billing, better tracking — every invoice already organized.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster Invoice Creation</h3>
                  <p>Generate complete invoicing systems instantly without manually building spreadsheets.</p>
                </div>
                <div className="benefit-card">
                  <h3>Better Billing Organization</h3>
                  <p>Structured invoice layouts improve payment visibility and customer management.</p>
                </div>
                <div className="benefit-card">
                  <h3>Reduced Billing Errors</h3>
                  <p>Automated calculations reduce invoice mistakes and payment inconsistencies.</p>
                </div>
                <div className="benefit-card">
                  <h3>Improved Cash Flow Management</h3>
                  <p>Invoice dashboards help businesses monitor payments and outstanding balances more effectively.</p>
                </div>
                <div className="benefit-card">
                  <h3>Easier Financial Reporting</h3>
                  <p>Centralized billing systems simplify accounting workflows and revenue analysis.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing <span className="serif-accent">Invoice</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated invoice into a real billing management tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Send Invoices Promptly</h3>
                  <p>Timely invoicing improves payment collection and cash flow consistency.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Include Clear Payment Terms</h3>
                  <p>Structured payment instructions reduce customer confusion and payment delays.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Track Outstanding Balances Regularly</h3>
                  <p>Monitoring unpaid invoices improves financial visibility and collection management.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Maintain Organized Customer Records</h3>
                  <p>Accurate customer information improves billing consistency and financial reporting quality.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most invoice templates are static spreadsheets with limited flexibility.</p>
            </div>
            <div className="row-body">
              <p>Most invoice templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated billing systems tailored to your invoicing workflow, customer management needs, and financial reporting structure.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Professional invoice systems</li>
                <li>Payment tracking dashboards</li>
                <li>Customer billing databases</li>
                <li>Revenue reporting sheets</li>
                <li>Tax calculation systems</li>
                <li>Outstanding balance trackers</li>
                <li>Billing workflow dashboards</li>
                <li>AI-powered invoicing workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing billing records, Formula Byte automates invoice spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This <span className="serif-accent">Invoice</span> Spreadsheet?</h2>
              <p className="intro">This spreadsheet solution is ideal for businesses and professionals managing billing and payment workflows.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>Freelancers</h4></div>
                <div className="audience-cell"><h4>Agencies</h4></div>
                <div className="audience-cell"><h4>Consultants</h4></div>
                <div className="audience-cell"><h4>Ecommerce stores</h4></div>
                <div className="audience-cell"><h4>Contractors</h4></div>
                <div className="audience-cell"><h4>Financial teams</h4></div>
                <div className="audience-cell"><h4>Service providers</h4></div>
                <div className="audience-cell"><h4>Business owners</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple billing or advanced payment tracking, Formula Byte helps automate invoice spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating invoice templates with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet calculate invoice totals automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates invoice spreadsheets with automated totals, tax calculations, and payment tracking systems.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include payment tracking?</summary>
                  <div className="faq-a">Yes. Invoice templates can include due dates, outstanding balance tracking, and payment status workflows.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize invoice layouts and billing categories?</summary>
                  <div className="faq-a">Absolutely. Invoice sections, tax structures, customer fields, and payment systems can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte invoice templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for freelancers and small businesses?</summary>
                  <div className="faq-a">Yes. Businesses and freelancers commonly use invoice spreadsheets for billing, payment tracking, revenue reporting, and financial management.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other business templates you might need.</h2>
              <p className="intro">Same engine, different business workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/expense-report-template/" className="related-card">
                  <div className="glyph">E</div>
                  <h4>Expense Report</h4>
                  <p>Track spending and reimbursements.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/income-statement-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Income Statement</h4>
                  <p>Revenue, expenses, and profit tracking.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/inventory-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Inventory</h4>
                  <p>Stock tracking and SKU management.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/balance-sheet-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Balance Sheet</h4>
                  <p>Assets, liabilities, and equity.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">Invoice</span> Spreadsheet?</h2>
            <p>Stop creating invoices manually.</p>
            <p>Describe your billing workflow, and Formula Byte will generate a professional AI-powered Excel invoice template with payment tracking systems, customer billing databases, tax calculation tools, invoice dashboards, and organized financial workflows in seconds.</p>
            <p>Create smarter invoicing spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}
