import React from 'react';

export default function ProfitAndLossTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=business">Business</a>
            <span className="sep">/</span>
            <span className="current">Profit and Loss</span>
          </div>

          <div className="eyebrow">Business template</div>
          <h1>AI Excel Profit and Loss Template for Business Financial <span className="accent">Reporting</span></h1>
          <p className="lede">
            Track revenue, expenses, gross profit, and net income with an AI-generated Excel profit and loss template designed for smarter business financial management. Formula Byte helps businesses automate profit and loss reporting using intelligent spreadsheets with financial dashboards, expense tracking systems, profitability analysis tools, and accounting workflows.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>7</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>14</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate profit and loss spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Startups</span>
          <span className="use-case-pill"><span className="dot"></span>Ecommerce brands</span>
          <span className="use-case-pill"><span className="dot"></span>Agencies</span>
          <span className="use-case-pill"><span className="dot"></span>Freelancers</span>
          <span className="use-case-pill"><span className="dot"></span>Contractors</span>
          <span className="use-case-pill"><span className="dot"></span>Financial reporting teams</span>
          <span className="use-case-pill"><span className="dot"></span>Business performance analysis</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Profit-and-Loss-Statement<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">F9</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=SUM</span>(<span className="num">F2</span><span className="op">:</span><span className="num">F8</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header">F</div>
            <div className="preview-col-header preview-hide-mobile">G</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Revenue Line Item</div>
            <div className="preview-cell preview-header-cell">Jan</div>
            <div className="preview-cell preview-header-cell">Feb</div>
            <div className="preview-cell preview-header-cell">Mar</div>
            <div className="preview-cell preview-header-cell">Apr</div>
            <div className="preview-cell preview-header-cell">May</div>
            <div className="preview-cell preview-header-cell">Jun</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">YTD</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">Product Sales</div>
            <div className="preview-cell num">$45,000</div>
            <div className="preview-cell num">$48,200</div>
            <div className="preview-cell num">$52,100</div>
            <div className="preview-cell num">$49,600</div>
            <div className="preview-cell num">$55,300</div>
            <div className="preview-cell num">$58,900</div>
            <div className="preview-cell num preview-hide-mobile">$309,100</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">Service Revenue</div>
            <div className="preview-cell num">$15,000</div>
            <div className="preview-cell num">$16,800</div>
            <div className="preview-cell num">$18,200</div>
            <div className="preview-cell num">$17,500</div>
            <div className="preview-cell num">$19,200</div>
            <div className="preview-cell num">$21,000</div>
            <div className="preview-cell num selected preview-hide-mobile">$107,700</div>

            {/* Row 4 */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">Total Revenue</div>
            <div className="preview-cell num">$60,000</div>
            <div className="preview-cell num">$65,000</div>
            <div className="preview-cell num">$70,300</div>
            <div className="preview-cell num">$67,100</div>
            <div className="preview-cell num">$74,500</div>
            <div className="preview-cell num">$79,900</div>
            <div className="preview-cell num preview-hide-mobile">$416,800</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">COGS</div>
            <div className="preview-cell num">($18,000)</div>
            <div className="preview-cell num">($19,500)</div>
            <div className="preview-cell num">($21,060)</div>
            <div className="preview-cell num">($20,160)</div>
            <div className="preview-cell num">($22,320)</div>
            <div className="preview-cell num">($23,760)</div>
            <div className="preview-cell num preview-hide-mobile">($124,800)</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Gross Profit</div>
            <div className="preview-cell num">$42,000</div>
            <div className="preview-cell num">$45,500</div>
            <div className="preview-cell num">$49,240</div>
            <div className="preview-cell num">$46,940</div>
            <div className="preview-cell num">$52,180</div>
            <div className="preview-cell num">$56,140</div>
            <div className="preview-cell num preview-hide-mobile">$292,000</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">Operating Expenses</div>
            <div className="preview-cell num">($25,000)</div>
            <div className="preview-cell num">($27,500)</div>
            <div className="preview-cell num">($29,700)</div>
            <div className="preview-cell num">($28,600)</div>
            <div className="preview-cell num">($31,400)</div>
            <div className="preview-cell num">($33,600)</div>
            <div className="preview-cell num preview-hide-mobile">($175,800)</div>

            {/* Row 8 */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text">Operating Income</div>
            <div className="preview-cell num">$17,000</div>
            <div className="preview-cell num">$18,000</div>
            <div className="preview-cell num">$19,540</div>
            <div className="preview-cell num">$18,340</div>
            <div className="preview-cell num">$20,780</div>
            <div className="preview-cell num">$22,540</div>
            <div className="preview-cell num preview-hide-mobile">$116,200</div>

            {/* Empty rows */}
            {Array.from({length: 4}).map((_, i) => (
              <React.Fragment key={`empty-${i}`}>
                <div className="preview-row-num">{9 + i}</div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell"></div>
                <div className="preview-cell preview-hide-mobile"></div>
              </React.Fragment>
            ))}

            {/* Status bar */}
            <div className="preview-status">
              <div className="preview-status-item">
                <span>Total Revenue:</span>
                <span className="val">$416,800</span>
              </div>
              <div className="preview-status-item">
                <span>Net Profit:</span>
                <span className="val">$96,200</span>
              </div>
              <div className="preview-status-item">
                <span>Profit Margin:</span>
                <span className="val">23.1%</span>
              </div>
              <div className="preview-status-spacer"></div>
              <div className="preview-status-tabs">
                <button className="preview-tab active">P&amp;L</button>
                <button className="preview-tab">Revenue</button>
                <button className="preview-tab">Expenses</button>
                <button className="preview-tab">Budget</button>
                <button className="preview-tab">+3</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* CREATE AN AI PROFIT AND LOSS SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Profit and Loss Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the financial reporting spreadsheet you need, and Formula Byte automatically generates a professional Excel profit and loss template with:</p>
            </div>
            <div className="row-body">
              <ul className="bulleted">
                <li>Revenue tracking</li>
                <li>Expense categorization</li>
                <li>Gross profit analysis</li>
                <li>Net profit calculations</li>
                <li>Cost tracking systems</li>
                <li>Financial dashboards</li>
                <li>Budget monitoring</li>
                <li>Automated spreadsheet formulas</li>
                <li>Profitability reporting workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually building financial statements, Formula Byte creates AI-powered financial reporting systems tailored to your accounting workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel Profit and Loss Template?</h2>
              <p className="intro">A structured spreadsheet used to summarize business revenue, expenses, and profitability over a specific reporting period.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel profit and loss template</strong> is a structured spreadsheet used to summarize business revenue, expenses, and profitability over a specific reporting period. It helps businesses evaluate financial performance while improving accounting organization and operational visibility.
              </p>
              <p>
                A profit and loss spreadsheet typically includes:
              </p>
              <ul className="bulleted">
                <li>Revenue summaries</li>
                <li>Cost of goods sold (COGS)</li>
                <li>Gross profit calculations</li>
                <li>Operating expenses</li>
                <li>Net income tracking</li>
                <li>Financial dashboards</li>
                <li>Expense analysis</li>
                <li>Profitability reports</li>
                <li>Financial performance summaries</li>
              </ul>
              <p>Formula Byte generates AI-powered financial spreadsheets designed for profit analysis, accounting organization, and business reporting workflows.</p>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How Profit and Loss Reporting Works</h2>
              <p className="intro">A profit and loss statement measures business performance by comparing revenue against expenses during a specific period.</p>
            </div>
            <div className="row-body">
              <p>A profit and loss statement measures business performance by comparing revenue against expenses during a specific period.</p>
              <p style={{marginTop: '18px'}}>The basic profit calculation follows:</p>
              <ul className="bulleted">
                <li><strong>Net Profit = Revenue - Expenses</strong></li>
              </ul>
              <p style={{marginTop: '18px'}}>A structured P&amp;L system helps businesses:</p>
              <ul className="bulleted">
                <li>Analyze profitability</li>
                <li>Track operational performance</li>
                <li>Monitor business expenses</li>
                <li>Improve budgeting decisions</li>
                <li>Evaluate revenue growth</li>
                <li>Support financial forecasting</li>
                <li>Improve accounting visibility</li>
              </ul>
              <p style={{marginTop: '18px'}}>Most profit and loss systems include:</p>
              <ul className="bulleted">
                <li>Revenue tracking</li>
                <li>Expense management</li>
                <li>Profit calculations</li>
                <li>Financial summaries</li>
                <li>Operational analysis</li>
                <li>Budget reporting</li>
                <li>Performance dashboards</li>
              </ul>
              <p style={{marginTop: '18px'}}>Formula Byte simplifies this process using AI-generated financial spreadsheets and automated accounting systems.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY BUSINESSES NEED PROFIT AND LOSS REPORTING */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Businesses Need Profit and Loss Reporting</h2>
              <p className="intro">Managing finances without structured reporting often creates unclear profitability and poor financial analysis.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without P&L reporting</div>
                  <h3>Managing finances without structured reporting often creates:</h3>
                  <ul>
                    <li>Unclear profitability visibility</li>
                    <li>Expense tracking issues</li>
                    <li>Budget inconsistencies</li>
                    <li>Poor financial analysis</li>
                    <li>Revenue forecasting problems</li>
                    <li>Accounting errors</li>
                    <li>Limited operational insights</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With P&L reporting</div>
                  <h3>A properly organized profit and loss spreadsheet helps businesses:</h3>
                  <ul>
                    <li>Monitor financial health</li>
                    <li>Analyze revenue performance</li>
                    <li>Track operational expenses</li>
                    <li>Improve financial planning</li>
                    <li>Support investment decisions</li>
                    <li>Organize accounting workflows</li>
                    <li>Improve business profitability</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI <span className="serif-accent">Profit and Loss</span> Spreadsheet</h2>
              <p className="intro">Four pillars of financial reporting — automatic, organized, and built to support real accounting needs.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">R</div>
                  <h3>Revenue Tracking</h3>
                  <p>Track all business income with automatic revenue categorization and structured financial reporting layouts.</p>
                  <ul>
                    <li>Product sales</li>
                    <li>Service income</li>
                    <li>Subscription revenue</li>
                    <li>Client payments</li>
                    <li>Ecommerce earnings</li>
                    <li>Operational income</li>
                    <li>Business growth trends</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>The spreadsheet automatically organizes revenue categories into structured financial reporting layouts.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">E</div>
                  <h3>Expense Management</h3>
                  <p>Monitor all business spending with organized cost management systems.</p>
                  <ul>
                    <li>Payroll costs</li>
                    <li>Marketing expenses</li>
                    <li>Rent and utilities</li>
                    <li>Software subscriptions</li>
                    <li>Operational spending</li>
                    <li>Vendor payments</li>
                    <li>Administrative costs</li>
                    <li>Business expenses</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This improves financial visibility and cost management.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">P</div>
                  <h3>Gross Profit and Net Profit Analysis</h3>
                  <p>Formula Byte profit and loss spreadsheets can include comprehensive profitability tracking systems.</p>
                  <ul>
                    <li>Gross profit calculations</li>
                    <li>Net income tracking</li>
                    <li>Expense ratio analysis</li>
                    <li>Profit margin summaries</li>
                    <li>Financial trend monitoring</li>
                    <li>Operational performance dashboards</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Structured profitability reporting improves financial planning and business analysis.</p>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">B</div>
                  <h3>Budget and Financial Forecasting</h3>
                  <p>Track financial planning with comprehensive budget management and forecasting tools.</p>
                  <ul>
                    <li>Revenue forecasts</li>
                    <li>Expense projections</li>
                    <li>Operational budgets</li>
                    <li>Financial growth trends</li>
                    <li>Monthly profitability</li>
                    <li>Financial planning targets</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This helps businesses improve long-term financial strategy and budgeting accuracy.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI FINANCIAL REPORTING AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Financial Reporting Automation for Profit Analysis</h2>
              <p className="intro">Skip the manual setup. The AI understands financial reporting instructions from natural language prompts.</p>
            </div>
            <div className="row-body">
              <p>Traditional P&L spreadsheets require manual formatting and repetitive accounting calculations.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure financial statements</li>
                <li>Generate accounting formulas</li>
                <li>Organize expense categories</li>
                <li>Create profitability dashboards</li>
                <li>Build financial summaries</li>
                <li>Generate budget reports</li>
                <li>Apply spreadsheet formatting</li>
                <li>Automate financial workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands financial reporting instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a monthly profit and loss spreadsheet"</button>
                  <button className="chip">"Build a small business financial reporting dashboard"</button>
                  <button className="chip">"Generate an ecommerce profit tracking system"</button>
                  <button className="chip">"Create a revenue and expense analysis template"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Profit and Loss Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete profit and loss spreadsheet with 7 worksheets — each generated, formatted, and wired up automatically.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Revenue Tracker</span>
                  <span className="spec-purpose">Monitors business income</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Expense Ledger</span>
                  <span className="spec-purpose">Tracks operational spending</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Gross Profit Summary</span>
                  <span className="spec-purpose">Calculates profitability</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Net Income Dashboard</span>
                  <span className="spec-purpose">Monitors final business profit</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Budget Forecast Sheet</span>
                  <span className="spec-purpose">Projects future financial performance</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Financial Dashboard</span>
                  <span className="spec-purpose">Visualizes business metrics</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Monthly P&L Summary</span>
                  <span className="spec-purpose">Organizes reporting periods</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINANCIAL CATEGORIES INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Data included</div>
              <h2>Financial <span className="serif-accent">Categories</span> Included</h2>
              <p className="intro">Every financial reporting category you need — pre-built, organized, and ready for instant profit management.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte profit and loss spreadsheets include comprehensive business finance categories:</p>
              <ul className="bulleted">
                <li><strong>Revenue and sales tracking:</strong> Product revenue, service income, ecommerce sales, recurring subscriptions, business earnings</li>
                <li><strong>Operational expense management:</strong> Payroll, utilities, marketing costs, operational expenses, vendor payments, administrative spending</li>
                <li><strong>Profitability and financial analysis:</strong> Gross profit, net income, profit margins, expense ratios, revenue growth trends</li>
              </ul>
              <p style={{marginTop: '18px'}}>These categories provide a complete foundation for profit organization and financial reporting.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Built-in automation</div>
              <h2>Built-In <span className="serif-accent">Profit and Loss</span> Formulas</h2>
              <p className="intro">No manual calculations. All formulas are wired, tested, and ready to use.</p>
            </div>
            <div className="row-body">
              <p>Every profit and loss spreadsheet includes built-in formulas for automatic financial calculations:</p>
              <ul className="bulleted">
                <li><strong>Total revenue:</strong> =SUM(Revenue Range)</li>
                <li><strong>Gross profit:</strong> =Revenue - COGS</li>
                <li><strong>Operating income:</strong> =Gross Profit - Operating Expenses</li>
                <li><strong>Net profit:</strong> =Operating Income - Taxes - Interest</li>
                <li><strong>Profit margin:</strong> = (Net Profit / Revenue) × 100%</li>
                <li><strong>Expense ratio:</strong> = (Expenses / Revenue) × 100%</li>
                <li><strong>YTD total:</strong> =SUM(Month Range)</li>
                <li><strong>Revenue growth:</strong> = ((Current Month - Previous Month) / Previous Month) × 100%</li>
              </ul>
              <p style={{marginTop: '18px'}}>These formulas automate complex financial calculations, reducing manual effort and improving accuracy.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Profit and Loss Templates by <span className="serif-accent">Business</span> Type</h2>
              <p className="intro">Customize the profit and loss template for any business — same structure, different focus.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">SB</div>
                    <div>
                      <h4>Small Business P&L Spreadsheet</h4>
                      <div className="industry-tagline">BUSINESS · FINANCE · GROWTH</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Revenue growth</li>
                    <li>Operational costs</li>
                    <li>Profitability</li>
                    <li>Financial performance</li>
                    <li>Budget summaries</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Ideal for startups and growing businesses.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">EC</div>
                    <div>
                      <h4>Ecommerce Profit Tracking Template</h4>
                      <div className="industry-tagline">ONLINE · SALES · COMMERCE</div>
                    </div>
                  </div>
                  <p>Manage:</p>
                  <ul>
                    <li>Marketplace revenue</li>
                    <li>Product costs</li>
                    <li>Advertising spend</li>
                    <li>Operational expenses</li>
                    <li>Profit margins</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for Shopify, Amazon, Etsy, and WooCommerce businesses.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">FR</div>
                    <div>
                      <h4>Freelancer Profit and Loss Spreadsheet</h4>
                      <div className="industry-tagline">FREELANCE · CONTRACT · INCOME</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Client payments</li>
                    <li>Project expenses</li>
                    <li>Tax-deductible costs</li>
                    <li>Operational spending</li>
                    <li>Monthly profitability</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Designed for freelancers and consultants.</p>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">ST</div>
                    <div>
                      <h4>Startup Financial Reporting Template</h4>
                      <div className="industry-tagline">STARTUP · GROWTH · METRICS</div>
                    </div>
                  </div>
                  <p>Monitor:</p>
                  <ul>
                    <li>Burn rate</li>
                    <li>Revenue growth</li>
                    <li>Investor reporting</li>
                    <li>Operational costs</li>
                    <li>Financial performance</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for startup financial planning and business analysis.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINANCIAL REPORTS AND PROFITABILITY INSIGHTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Financial Reports and Profitability Insights</h2>
              <p className="intro">Every generated profit and loss system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte profit and loss spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Profit summaries</li>
                <li>Expense analysis reports</li>
                <li>Revenue dashboards</li>
                <li>Budget forecasting reports</li>
                <li>Financial performance insights</li>
                <li>Operational spending summaries</li>
                <li>Business profitability dashboards</li>
                <li>Accounting reports</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into financial performance and operational efficiency.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Profit and Loss Spreadsheet vs. <span className="serif-accent">Manual</span> Financial Reporting</h2>
              <p className="intro">Seven dimensions where AI-powered profit spreadsheets outperform manual financial work.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual Financial Reporting</div>
                  <h3>Manual financial organization</h3>
                  <ul>
                    <li>Manual profit calculations</li>
                    <li>Often inconsistent expense tracking</li>
                    <li>Error-prone reporting accuracy</li>
                    <li>Limited financial visibility</li>
                    <li>Time-consuming spreadsheet setup</li>
                    <li>Limited budget forecasting</li>
                    <li>Difficult to manage operational analysis</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>AI-generated spreadsheets</h3>
                  <ul>
                    <li>Automated profit calculations</li>
                    <li>Organized expense tracking</li>
                    <li>High reporting accuracy</li>
                    <li>Dashboard-based financial visibility</li>
                    <li>Fast spreadsheet setup</li>
                    <li>Included budget forecasting</li>
                    <li>Structured operational analysis</li>
                  </ul>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify financial reporting and profitability analysis.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">Profit and Loss</span> Templates</h2>
              <p className="intro">Faster reporting, accurate calculations, better visibility — every profit already analyzed.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster Financial Reporting</h3>
                  <p>Generate complete P&L systems instantly without manually building spreadsheets.</p>
                </div>
                <div className="benefit-card">
                  <h3>Better Profitability Visibility</h3>
                  <p>Structured financial dashboards improve revenue and expense analysis.</p>
                </div>
                <div className="benefit-card">
                  <h3>Reduced Accounting Errors</h3>
                  <p>Automated formulas reduce financial calculation mistakes and reporting inconsistencies.</p>
                </div>
                <div className="benefit-card">
                  <h3>Improved Budgeting and Forecasting</h3>
                  <p>Financial reports help businesses analyze trends and improve planning decisions.</p>
                </div>
                <div className="benefit-card">
                  <h3>Easier Business Performance Analysis</h3>
                  <p>Centralized financial systems simplify operational analysis and profitability monitoring.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing <span className="serif-accent">Profit and Loss</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated P&L into a real financial reporting tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Update Financial Data Regularly</h3>
                  <p>Consistent updates improve reporting accuracy and financial visibility.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Categorize Revenue and Expenses Clearly</h3>
                  <p>Structured financial categories improve analysis quality and reporting consistency.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Review Profitability Reports Frequently</h3>
                  <p>Regular reviews help identify revenue growth trends, expense increases, budget inefficiencies, profitability opportunities, and financial risks.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Maintain Accurate Financial Records</h3>
                  <p>Consistent accounting practices improve financial reporting reliability and operational transparency.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most profit and loss templates are static spreadsheets with limited flexibility.</p>
            </div>
            <div className="row-body">
              <p>Most profit and loss templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated financial reporting systems tailored to your accounting workflow, business structure, and profitability analysis requirements.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>P&L statements</li>
                <li>Profitability dashboards</li>
                <li>Revenue tracking systems</li>
                <li>Expense analysis reports</li>
                <li>Budget forecasting tools</li>
                <li>Financial summaries</li>
                <li>Accounting dashboards</li>
                <li>AI-powered financial workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing financial records, Formula Byte automates profit and loss spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This <span className="serif-accent">Profit and Loss</span> Spreadsheet?</h2>
              <p className="intro">This spreadsheet solution is ideal for businesses and professionals managing financial reporting and accounting.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>Startups</h4></div>
                <div className="audience-cell"><h4>Ecommerce brands</h4></div>
                <div className="audience-cell"><h4>Financial analysts</h4></div>
                <div className="audience-cell"><h4>Accountants</h4></div>
                <div className="audience-cell"><h4>Consultants</h4></div>
                <div className="audience-cell"><h4>Agencies</h4></div>
                <div className="audience-cell"><h4>Business owners</h4></div>
                <div className="audience-cell"><h4>Finance managers</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple profit tracking or advanced financial analysis, Formula Byte helps automate profit and loss spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating profit and loss templates with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet calculate profits automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates profit and loss spreadsheets with automated revenue tracking, expense calculations, and profitability analysis.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include financial dashboards?</summary>
                  <div className="faq-a">Yes. Profit and loss templates can include financial summaries, profitability dashboards, and reporting visuals.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize financial categories and layouts?</summary>
                  <div className="faq-a">Absolutely. Revenue sections, expense categories, reporting periods, and financial dashboards can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte profit and loss templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for small business financial reporting?</summary>
                  <div className="faq-a">Yes. Businesses commonly use profit and loss spreadsheets for budgeting, accounting, profitability analysis, and financial management.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other business templates you might need.</h2>
              <p className="intro">Same engine, different business workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/income-statement-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Income Statement</h4>
                  <p>Revenue, expenses, and profit.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/expense-report-template/" className="related-card">
                  <div className="glyph">E</div>
                  <h4>Expense Report</h4>
                  <p>Track spending and reimbursements.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/balance-sheet-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Balance Sheet</h4>
                  <p>Assets, liabilities, and equity.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/invoice-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Invoice</h4>
                  <p>Billing and payment management.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">Profit and Loss</span> Spreadsheet?</h2>
            <p>Stop creating financial reports manually.</p>
            <p>Describe your financial workflow, and Formula Byte will generate a professional AI-powered Excel profit and loss template with profitability dashboards, expense tracking systems, revenue analysis tools, financial summaries, and organized accounting workflows in seconds.</p>
            <p>Create smarter financial reporting spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}
