import React from 'react';

export default function PurchaseOrderTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=business">Business</a>
            <span className="sep">/</span>
            <span className="current">Purchase Order</span>
          </div>

          <div className="eyebrow">Business template</div>
          <h1>AI Excel Purchase Order Template for Procurement and Vendor <span className="accent">Management</span></h1>
          <p className="lede">
            Organize vendor purchases, track order quantities, manage procurement workflows, and monitor delivery status with an AI-generated Excel purchase order template designed for smarter purchasing management. Formula Byte helps businesses automate procurement operations using intelligent spreadsheets with vendor tracking systems, order management dashboards, approval workflows, and inventory coordination tools.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>16</strong> built-in formulas</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>25 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate purchase order spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Ecommerce stores</span>
          <span className="use-case-pill"><span className="dot"></span>Retail operations</span>
          <span className="use-case-pill"><span className="dot"></span>Construction companies</span>
          <span className="use-case-pill"><span className="dot"></span>Manufacturing teams</span>
          <span className="use-case-pill"><span className="dot"></span>Procurement departments</span>
          <span className="use-case-pill"><span className="dot"></span>Warehouse operations</span>
          <span className="use-case-pill"><span className="dot"></span>Vendor management workflows</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Purchase-Order-Tracker<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">H9</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=SUM</span>(<span className="num">H2</span><span className="op">:</span><span className="num">H8</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header">F</div>
            <div className="preview-col-header">G</div>
            <div className="preview-col-header">H</div>

            {/* Row 1 - Headers */}
            <div className="preview-row-header">1</div>
            <div className="preview-cell preview-cell-header">Purchase Order</div>
            <div className="preview-cell preview-cell-header">Vendor</div>
            <div className="preview-cell preview-cell-header">Product</div>
            <div className="preview-cell preview-cell-header">SKU</div>
            <div className="preview-cell preview-cell-header">Quantity</div>
            <div className="preview-cell preview-cell-header">Unit Price</div>
            <div className="preview-cell preview-cell-header">Total</div>
            <div className="preview-cell preview-cell-header">Status</div>

            {/* Row 2 */}
            <div className="preview-row-header">2</div>
            <div className="preview-cell">PO-2024-001</div>
            <div className="preview-cell">Acme Supplies</div>
            <div className="preview-cell">Office Chairs</div>
            <div className="preview-cell">CHR-001</div>
            <div className="preview-cell preview-cell-num">50</div>
            <div className="preview-cell preview-cell-num">$125.00</div>
            <div className="preview-cell preview-cell-num preview-cell-formula">$6,250.00</div>
            <div className="preview-cell preview-cell-status">Approved</div>

            {/* Row 3 */}
            <div className="preview-row-header">3</div>
            <div className="preview-cell">PO-2024-002</div>
            <div className="preview-cell">Tech Distributors</div>
            <div className="preview-cell">Monitors 24"</div>
            <div className="preview-cell">MON-024</div>
            <div className="preview-cell preview-cell-num">30</div>
            <div className="preview-cell preview-cell-num">$299.00</div>
            <div className="preview-cell preview-cell-num preview-cell-formula">$8,970.00</div>
            <div className="preview-cell preview-cell-status">Pending</div>

            {/* Row 4 */}
            <div className="preview-row-header">4</div>
            <div className="preview-cell">PO-2024-003</div>
            <div className="preview-cell">Global Logistics</div>
            <div className="preview-cell">Packaging Materials</div>
            <div className="preview-cell">PKG-500</div>
            <div className="preview-cell preview-cell-num">500</div>
            <div className="preview-cell preview-cell-num">$2.50</div>
            <div className="preview-cell preview-cell-num preview-cell-formula">$1,250.00</div>
            <div className="preview-cell preview-cell-status">Shipped</div>

            {/* Row 5 */}
            <div className="preview-row-header">5</div>
            <div className="preview-cell">PO-2024-004</div>
            <div className="preview-cell">Office Depot Pro</div>
            <div className="preview-cell">Printer Paper</div>
            <div className="preview-cell">PPT-001</div>
            <div className="preview-cell preview-cell-num">200</div>
            <div className="preview-cell preview-cell-num">$8.99</div>
            <div className="preview-cell preview-cell-num preview-cell-formula">$1,798.00</div>
            <div className="preview-cell preview-cell-status">Delivered</div>

            {/* Row 6 */}
            <div className="preview-row-header">6</div>
            <div className="preview-cell">PO-2024-005</div>
            <div className="preview-cell">Industrial Supply Co</div>
            <div className="preview-cell">Safety Equipment</div>
            <div className="preview-cell">SAF-100</div>
            <div className="preview-cell preview-cell-num">100</div>
            <div className="preview-cell preview-cell-num">$45.00</div>
            <div className="preview-cell preview-cell-num preview-cell-formula">$4,500.00</div>
            <div className="preview-cell preview-cell-status">Approved</div>

            {/* Row 7 */}
            <div className="preview-row-header">7</div>
            <div className="preview-cell">PO-2024-006</div>
            <div className="preview-cell">Warehouse Plus</div>
            <div className="preview-cell">Shelving Units</div>
            <div className="preview-cell">SHE-250</div>
            <div className="preview-cell preview-cell-num">25</div>
            <div className="preview-cell preview-cell-num">$189.00</div>
            <div className="preview-cell preview-cell-num preview-cell-formula">$4,725.00</div>
            <div className="preview-cell preview-cell-status">Pending</div>

            {/* Row 8 */}
            <div className="preview-row-header">8</div>
            <div className="preview-cell">PO-2024-007</div>
            <div className="preview-cell">Tech Solutions Inc</div>
            <div className="preview-cell">Network Cables</div>
            <div className="preview-cell">NET-CAT6</div>
            <div className="preview-cell preview-cell-num">150</div>
            <div className="preview-cell preview-cell-num">$12.00</div>
            <div className="preview-cell preview-cell-num preview-cell-formula">$1,800.00</div>
            <div className="preview-cell preview-cell-status">Approved</div>

            {/* Row 9 - Total */}
            <div className="preview-row-header">9</div>
            <div className="preview-cell preview-cell-bold"></div>
            <div className="preview-cell preview-cell-bold"></div>
            <div className="preview-cell preview-cell-bold"></div>
            <div className="preview-cell preview-cell-bold"></div>
            <div className="preview-cell preview-cell-bold"></div>
            <div className="preview-cell preview-cell-bold"></div>
            <div className="preview-cell preview-cell-bold preview-cell-formula preview-cell-accent">$29,293.00</div>
            <div className="preview-cell preview-cell-bold"></div>
          </div>
        </div>
      </div>

      {/* CREATE AN AI PURCHASE ORDER SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Purchase Order Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the procurement spreadsheet you need, and Formula Byte automatically generates a professional Excel purchase order template with:</p>
            </div>
            <div className="row-body">
              <ul className="bulleted">
                <li>Vendor management systems</li>
                <li>Purchase order tracking</li>
                <li>Product quantity management</li>
                <li>Approval workflows</li>
                <li>Delivery monitoring</li>
                <li>Inventory coordination</li>
                <li>Procurement dashboards</li>
                <li>Automated spreadsheet formulas</li>
                <li>Purchasing workflow systems</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing procurement records, Formula Byte creates AI-powered purchase order systems tailored to your operational workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel Purchase Order Template?</h2>
              <p className="intro">A structured spreadsheet used to organize vendor purchases, track procurement activity, and manage inventory ordering workflows.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel purchase order template</strong> is a structured spreadsheet used to organize vendor purchases, track procurement activity, and manage inventory ordering workflows. It helps businesses maintain accurate purchasing records while improving supplier coordination and procurement visibility.
              </p>
              <p style={{marginTop: '18px'}}>
                A purchase order spreadsheet typically includes:
              </p>
              <ul className="bulleted">
                <li>Vendor information</li>
                <li>Purchase order numbers</li>
                <li>Product descriptions</li>
                <li>Item quantities</li>
                <li>Unit pricing</li>
                <li>Delivery dates</li>
                <li>Payment terms</li>
                <li>Approval status</li>
                <li>Procurement summaries</li>
              </ul>
              <p style={{marginTop: '18px'}}>Formula Byte generates AI-powered purchase order spreadsheets designed for procurement tracking, vendor management, and purchasing workflow organization.</p>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How Purchase Order Management Works</h2>
              <p className="intro">Purchase order management is the process of creating, tracking, and monitoring purchasing requests between businesses and suppliers.</p>
            </div>
            <div className="row-body">
              <p>Purchase order management is the process of creating, tracking, and monitoring purchasing requests between businesses and suppliers.</p>
              <p style={{marginTop: '18px'}}>A structured procurement system helps businesses:</p>
              <ul className="bulleted">
                <li>Organize purchasing workflows</li>
                <li>Track vendor orders</li>
                <li>Improve inventory planning</li>
                <li>Reduce procurement errors</li>
                <li>Monitor delivery schedules</li>
                <li>Improve supplier coordination</li>
                <li>Maintain accurate purchasing records</li>
              </ul>
              <p style={{marginTop: '18px'}}>Most purchase order systems include:</p>
              <ul className="bulleted">
                <li>Vendor databases</li>
                <li>Procurement tracking</li>
                <li>Inventory coordination</li>
                <li>Delivery monitoring</li>
                <li>Approval workflows</li>
                <li>Purchase summaries</li>
                <li>Financial reporting</li>
              </ul>
              <p style={{marginTop: '18px'}}>Formula Byte simplifies this process using AI-generated procurement spreadsheets and automated purchasing systems.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY BUSINESSES NEED PURCHASE ORDER SYSTEMS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Businesses Need Purchase Order Systems</h2>
              <p className="intro">Managing procurement without a structured system often leads to operational inefficiencies and poor vendor coordination.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without purchase order system</div>
                  <h3>Managing procurement without a structured system often creates:</h3>
                  <ul>
                    <li>Vendor communication issues</li>
                    <li>Inventory shortages</li>
                    <li>Purchasing errors</li>
                    <li>Delayed deliveries</li>
                    <li>Approval bottlenecks</li>
                    <li>Financial inconsistencies</li>
                    <li>Poor procurement visibility</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With purchase order system</div>
                  <h3>A properly organized purchase order spreadsheet helps businesses:</h3>
                  <ul>
                    <li>Improve procurement organization</li>
                    <li>Monitor purchasing activity</li>
                    <li>Coordinate supplier relationships</li>
                    <li>Track delivery schedules</li>
                    <li>Improve inventory planning</li>
                    <li>Reduce procurement mistakes</li>
                    <li>Increase operational efficiency</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI <span className="serif-accent">Purchase Order</span> Spreadsheet</h2>
              <p className="intro">Four pillars of procurement management — automatic, organized, and built to support real workflow needs.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">V</div>
                  <h3>Vendor and Supplier Management</h3>
                  <p>Track all vendor relationships with automatic supplier organization and structured procurement layouts.</p>
                  <ul>
                    <li>Supplier names</li>
                    <li>Vendor contact information</li>
                    <li>Procurement records</li>
                    <li>Vendor categories</li>
                    <li>Purchase histories</li>
                    <li>Supplier communication</li>
                    <li>Vendor performance</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>The spreadsheet automatically organizes vendor records into structured procurement layouts.</p>
                </div>

                <div className="feature-tile">
                  <div className="feature-tile-icon">P</div>
                  <h3>Product and Quantity Tracking</h3>
                  <p>Monitor all inventory purchases with organized quantity management systems.</p>
                  <ul>
                    <li>Product descriptions</li>
                    <li>SKU numbers</li>
                    <li>Order quantities</li>
                    <li>Unit prices</li>
                    <li>Inventory purchases</li>
                    <li>Procurement totals</li>
                    <li>Product categories</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This improves purchasing visibility and inventory coordination.</p>
                </div>

                <div className="feature-tile">
                  <div className="feature-tile-icon">D</div>
                  <h3>Delivery and Order Status Monitoring</h3>
                  <p>Formula Byte purchase order spreadsheets include comprehensive delivery tracking systems.</p>
                  <ul>
                    <li>Delivery schedules</li>
                    <li>Shipping tracking</li>
                    <li>Order status updates</li>
                    <li>Procurement timelines</li>
                    <li>Pending deliveries</li>
                    <li>Received inventory logs</li>
                    <li>Delivery dashboards</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Structured delivery tracking improves operational planning and inventory management.</p>
                </div>

                <div className="feature-tile">
                  <div className="feature-tile-icon">A</div>
                  <h3>Approval and Financial Tracking</h3>
                  <p>Track all purchase approvals with comprehensive workflow management and monitoring tools.</p>
                  <ul>
                    <li>Approval status</li>
                    <li>Purchase authorizations</li>
                    <li>Payment terms</li>
                    <li>Procurement budgets</li>
                    <li>Order summaries</li>
                    <li>Vendor invoices</li>
                    <li>Financial tracking</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>This helps businesses improve procurement accountability and financial organization.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI PROCUREMENT AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Procurement <span className="serif-accent">Automation</span> for Purchase Tracking</h2>
              <p className="intro">Skip the manual setup. The AI understands procurement instructions from natural language prompts.</p>
            </div>
            <div className="row-body">
              <p>Traditional purchase order spreadsheets require manual formatting and repetitive procurement updates.</p>
              <p style={{marginTop: '18px'}}>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure procurement systems</li>
                <li>Generate purchase tracking workflows</li>
                <li>Organize vendor databases</li>
                <li>Create approval dashboards</li>
                <li>Build inventory coordination systems</li>
                <li>Generate procurement summaries</li>
                <li>Apply spreadsheet formatting</li>
                <li>Automate purchasing workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands procurement instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a vendor purchase order spreadsheet"</button>
                  <button className="chip">"Build a procurement tracking dashboard"</button>
                  <button className="chip">"Generate an inventory purchasing template"</button>
                  <button className="chip">"Create a supplier management workflow"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Purchase Order Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete purchase order spreadsheet with 8 worksheets — each generated, formatted, and wired up automatically.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Purchase Order Tracker</span>
                  <span className="spec-purpose">Monitors procurement activity</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Vendor Database</span>
                  <span className="spec-purpose">Stores supplier information</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Product Inventory Sheet</span>
                  <span className="spec-purpose">Organizes purchased items</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Delivery Monitoring Dashboard</span>
                  <span className="spec-purpose">Tracks shipping and deliveries</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Approval Workflow Sheet</span>
                  <span className="spec-purpose">Manages procurement approvals</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Procurement Budget Tracker</span>
                  <span className="spec-purpose">Monitors purchasing costs</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Inventory Coordination Dashboard</span>
                  <span className="spec-purpose">Tracks stock replenishment</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Purchase Summary Report</span>
                  <span className="spec-purpose">Generates procurement insights</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* PROCUREMENT CATEGORIES INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Data included</div>
              <h2>Procurement <span className="serif-accent">Categories</span> Included</h2>
              <p className="intro">Every procurement category you need — pre-built, organized, and ready for instant workflow management.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte purchase order spreadsheets include comprehensive workflow management categories:</p>
              <ul className="bulleted">
                <li><strong>Vendor and supplier tracking:</strong> Supplier information, vendor records, procurement contacts, vendor performance, purchase histories</li>
                <li><strong>Inventory and product procurement:</strong> Product purchases, inventory replenishment, SKU management, stock ordering, warehouse coordination</li>
                <li><strong>Procurement workflow management:</strong> Purchase approvals, delivery schedules, procurement budgets, payment tracking, purchasing performance</li>
              </ul>
              <p style={{marginTop: '18px'}}>These categories provide a complete foundation for procurement organization and purchasing workflow tracking.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Built-in automation</div>
              <h2>Built-In <span className="serif-accent">Purchase Order</span> Formulas</h2>
              <p className="intro">No manual calculations. All formulas are wired, tested, and ready to use.</p>
            </div>
            <div className="row-body">
              <p>Every purchase order spreadsheet includes built-in formulas for automatic procurement calculations:</p>
              <ul className="bulleted">
                <li><strong>Line total:</strong> =Quantity × Unit Price</li>
                <li><strong>Order total:</strong> =SUM(Line Totals)</li>
                <li><strong>Quantity remaining:</strong> =Ordered Quantity - Received Quantity</li>
                <li><strong>Budget remaining:</strong> =Procurement Budget - Total Orders</li>
                <li><strong>Average unit price:</strong> =AVERAGE(Unit Price Range)</li>
                <li><strong>Approval status:</strong> =IF(Total &gt; Approval Limit, "Pending Approval", "Approved")</li>
                <li><strong>Delivery status:</strong> =IF(Received Date &lt;= Expected Date, "On Time", "Delayed")</li>
                <li><strong>Vendor performance:</strong> =COUNTIF(On-Time Deliveries, TRUE) / Total Orders × 100%</li>
              </ul>
              <p style={{marginTop: '18px'}}>These formulas automate complex procurement calculations, reducing manual effort and improving accuracy.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Purchase Order Templates by <span className="serif-accent">Business</span> Type</h2>
              <p className="intro">Customize the purchase order template for any business — same structure, different focus.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">SB</div>
                    <div>
                      <h4>Small Business Purchase Order Spreadsheet</h4>
                      <div className="industry-tagline">BUSINESS · PROCUREMENT · OPERATIONS</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Vendor purchases</li>
                    <li>Inventory orders</li>
                    <li>Procurement budgets</li>
                    <li>Delivery schedules</li>
                    <li>Supplier coordination</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Ideal for startups and operational teams.</p>
                </div>

                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">EC</div>
                    <div>
                      <h4>Ecommerce Procurement Template</h4>
                      <div className="industry-tagline">ECOMMERCE · SOURCING · INVENTORY</div>
                    </div>
                  </div>
                  <p>Manage:</p>
                  <ul>
                    <li>Product sourcing</li>
                    <li>Supplier orders</li>
                    <li>Inventory replenishment</li>
                    <li>Warehouse coordination</li>
                    <li>Procurement reporting</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for Shopify, WooCommerce, Amazon, and ecommerce operations.</p>
                </div>

                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">CN</div>
                    <div>
                      <h4>Construction Procurement Spreadsheet</h4>
                      <div className="industry-tagline">CONSTRUCTION · MATERIALS · SITES</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Material orders</li>
                    <li>Contractor suppliers</li>
                    <li>Delivery schedules</li>
                    <li>Procurement budgets</li>
                    <li>Site inventory</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Designed for construction and operational management.</p>
                </div>

                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">MF</div>
                    <div>
                      <h4>Manufacturing Purchase Order Dashboard</h4>
                      <div className="industry-tagline">MANUFACTURING · MATERIALS · PRODUCTION</div>
                    </div>
                  </div>
                  <p>Monitor:</p>
                  <ul>
                    <li>Raw material procurement</li>
                    <li>Supplier deliveries</li>
                    <li>Inventory planning</li>
                    <li>Procurement approvals</li>
                    <li>Operational purchasing</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for manufacturing and warehouse operations.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* PROCUREMENT REPORTS AND VENDOR INSIGHTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Procurement Reports and Vendor Insights</h2>
              <p className="intro">Every generated purchase order system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte purchase order spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Procurement summaries</li>
                <li>Vendor performance reports</li>
                <li>Delivery tracking dashboards</li>
                <li>Inventory purchasing insights</li>
                <li>Procurement budget reports</li>
                <li>Supplier analysis dashboards</li>
                <li>Purchasing workflow reports</li>
                <li>Operational procurement summaries</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into procurement operations and supplier management.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Purchase Order Spreadsheet vs. <span className="serif-accent">Manual</span> Procurement Tracking</h2>
              <p className="intro">Seven dimensions where AI-powered purchase order spreadsheets outperform manual workflow management.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual Procurement Tracking</div>
                  <h3>Manual vendor organization</h3>
                  <ul>
                    <li>Often inconsistent vendor records</li>
                    <li>Limited delivery monitoring</li>
                    <li>Manual procurement tracking</li>
                    <li>Difficult to manage inventory coordination</li>
                    <li>Time-consuming spreadsheet setup</li>
                    <li>Less efficient approval workflows</li>
                    <li>Basic procurement reporting</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>AI-generated spreadsheets</h3>
                  <ul>
                    <li>Structured vendor organization</li>
                    <li>Dashboard-based delivery monitoring</li>
                    <li>Automated procurement tracking</li>
                    <li>Organized inventory coordination</li>
                    <li>Fast spreadsheet setup</li>
                    <li>Centralized approval workflows</li>
                    <li>Automated procurement reporting</li>
                  </ul>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify procurement management and purchasing workflows.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">Purchase Order</span> Templates</h2>
              <p className="intro">Faster setup, accurate tracking, better visibility — every procurement workflow already organized.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster Procurement Setup</h3>
                  <p>Generate complete purchasing systems instantly without manually building spreadsheets.</p>
                </div>

                <div className="benefit-card">
                  <h3>Better Vendor Visibility</h3>
                  <p>Structured procurement dashboards improve supplier tracking and purchasing organization.</p>
                </div>

                <div className="benefit-card">
                  <h3>Reduced Procurement Errors</h3>
                  <p>Automated formulas reduce ordering mistakes and purchasing inconsistencies.</p>
                </div>

                <div className="benefit-card">
                  <h3>Improved Inventory Coordination</h3>
                  <p>Procurement systems help businesses monitor inventory replenishment and stock availability more effectively.</p>
                </div>

                <div className="benefit-card">
                  <h3>Easier Operational Management</h3>
                  <p>Centralized purchasing workflows improve procurement visibility and supplier coordination.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing <span className="serif-accent">Purchase Order</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated procurement tracker into a real workflow management tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Update Procurement Records Regularly</h3>
                  <p>Consistent updates improve purchasing visibility and inventory accuracy.</p>
                </div>

                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Maintain Accurate Vendor Information</h3>
                  <p>Structured supplier records improve communication and procurement reliability.</p>
                </div>

                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Monitor Delivery Schedules Closely</h3>
                  <p>Tracking deliveries helps reduce operational delays and inventory shortages.</p>
                </div>

                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Review Procurement Reports Frequently</h3>
                  <p>Regular reviews help identify vendor performance issues, inventory shortages, procurement bottlenecks, budget overruns, and purchasing optimization opportunities.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most purchase order templates are static spreadsheets with limited flexibility.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte creates AI-generated procurement systems tailored to your purchasing workflow, vendor structure, and inventory management requirements.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Procurement dashboards</li>
                <li>Vendor management systems</li>
                <li>Inventory purchasing trackers</li>
                <li>Delivery monitoring tools</li>
                <li>Approval workflow systems</li>
                <li>Procurement summaries</li>
                <li>Operational purchasing dashboards</li>
                <li>AI-powered procurement workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing purchase orders, Formula Byte automates procurement spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This <span className="serif-accent">Purchase Order</span> Spreadsheet?</h2>
              <p className="intro">This spreadsheet solution is ideal for businesses and professionals managing procurement workflows and vendor coordination.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>Procurement teams</h4></div>
                <div className="audience-cell"><h4>Ecommerce stores</h4></div>
                <div className="audience-cell"><h4>Warehouses</h4></div>
                <div className="audience-cell"><h4>Manufacturers</h4></div>
                <div className="audience-cell"><h4>Construction companies</h4></div>
                <div className="audience-cell"><h4>Operations managers</h4></div>
                <div className="audience-cell"><h4>Retail businesses</h4></div>
                <div className="audience-cell"><h4>Supply chain teams</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple purchasing workflows or advanced procurement management, Formula Byte helps automate purchase order spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating purchase order templates with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet track purchase order status automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates purchase order spreadsheets with procurement tracking, delivery monitoring, and vendor management systems.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include supplier and inventory management?</summary>
                  <div className="faq-a">Yes. Purchase order templates can include vendor databases, inventory coordination tools, and procurement dashboards.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize procurement categories and approval workflows?</summary>
                  <div className="faq-a">Absolutely. Vendor sections, approval systems, purchasing workflows, and reporting dashboards can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte purchase order templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for procurement and inventory management?</summary>
                  <div className="faq-a">Yes. Businesses commonly use purchase order spreadsheets for procurement tracking, supplier coordination, inventory replenishment, and purchasing workflows.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other business templates you might need.</h2>
              <p className="intro">Same engine, different business workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/inventory-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Inventory Template</h4>
                  <p>Track stock and warehouse operations.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/invoice-template/" className="related-card">
                  <div className="glyph">N</div>
                  <h4>Invoice Template</h4>
                  <p>Manage billing and payments.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/project-timeline-template/" className="related-card">
                  <div className="glyph">P</div>
                  <h4>Project Timeline Template</h4>
                  <p>Track project schedules and deadlines.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/balance-sheet-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Balance Sheet Template</h4>
                  <p>Track assets and liabilities.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">Purchase Order</span> Spreadsheet?</h2>
            <p>Stop managing procurement manually.</p>
            <p>Describe your purchasing workflow, and Formula Byte will generate a professional AI-powered Excel purchase order template with procurement dashboards, vendor management systems, inventory coordination tools, delivery tracking workflows, and operational reporting systems in seconds.</p>
            <p>Create smarter procurement spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
