export default function RACITemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=business">Business</a>
            <span className="sep">/</span>
            <span className="current">RACI Matrix</span>
          </div>

          <div className="eyebrow">Business template</div>
          <h1>AI Excel RACI Matrix Template for Role Assignment and Project <span className="accent">Responsibility Management</span></h1>
          <p className="lede">
            Organize team responsibilities, clarify project ownership, and improve workflow accountability with an AI-generated Excel RACI matrix template designed for smarter project coordination and operational management. Formula Byte helps businesses automate responsibility mapping using intelligent spreadsheets with role assignment systems, accountability dashboards, project ownership tracking, and workflow management tools.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>12</strong> formulas built in</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate RACI matrix spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Project management teams</span>
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Agencies</span>
          <span className="use-case-pill"><span className="dot"></span>IT departments</span>
          <span className="use-case-pill"><span className="dot"></span>Construction operations</span>
          <span className="use-case-pill"><span className="dot"></span>Marketing teams</span>
          <span className="use-case-pill"><span className="dot"></span>Product development workflows</span>
          <span className="use-case-pill"><span className="dot"></span>Cross-functional collaboration</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">RACI-Matrix<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">E5</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=IF</span>(<span className="num">D5</span>=<span className="str">"R"</span>,<span className="str">"Responsible"</span>,<span className="num">D5</span>=<span className="str">"A"</span>,<span className="str">"Accountable"</span>,<span className="str">""</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header preview-hide-mobile">F</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Task</div>
            <div className="preview-cell preview-header-cell">Project Manager</div>
            <div className="preview-cell preview-header-cell">Team Lead</div>
            <div className="preview-cell preview-header-cell">Developer</div>
            <div className="preview-cell preview-header-cell">Status</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Notes</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">Requirements Gathering</div>
            <div className="preview-cell selected">R</div>
            <div className="preview-cell">A</div>
            <div className="preview-cell">C</div>
            <div className="preview-cell text">In Progress</div>
            <div className="preview-cell preview-hide-mobile">Stakeholder input</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">Design Approval</div>
            <div className="preview-cell">A</div>
            <div className="preview-cell selected">R</div>
            <div className="preview-cell">C</div>
            <div className="preview-cell text">Pending</div>
            <div className="preview-cell preview-hide-mobile">UX review needed</div>

            {/* Row 4 — selected */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">Development</div>
            <div className="preview-cell">I</div>
            <div className="preview-cell">A</div>
            <div className="preview-cell selected">R</div>
            <div className="preview-cell text">Not Started</div>
            <div className="preview-cell preview-hide-mobile">Sprint planning</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">Testing</div>
            <div className="preview-cell">I</div>
            <div className="preview-cell">C</div>
            <div className="preview-cell selected">R</div>
            <div className="preview-cell text">Not Started</div>
            <div className="preview-cell preview-hide-mobile">QA assigned</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Deployment</div>
            <div className="preview-cell selected">A</div>
            <div className="preview-cell">C</div>
            <div className="preview-cell">I</div>
            <div className="preview-cell text">Not Started</div>
            <div className="preview-cell preview-hide-mobile">Production release</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">Documentation</div>
            <div className="preview-cell">I</div>
            <div className="preview-cell selected">R</div>
            <div className="preview-cell">C</div>
            <div className="preview-cell text">Not Started</div>
            <div className="preview-cell preview-hide-mobile">User guides</div>

            {/* Row 8 — sparkline */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell faded">…</div>
            <div className="preview-cell faded preview-hide-mobile">…</div>

            {/* Row 9 - legend */}
            <div className="preview-row-num">9</div>
            <div className="preview-cell preview-header-cell">RACI Legend</div>
            <div className="preview-cell text"><strong>R</strong> = Responsible</div>
            <div className="preview-cell text"><strong>A</strong> = Accountable</div>
            <div className="preview-cell text"><strong>C</strong> = Consulted</div>
            <div className="preview-cell text"><strong>I</strong> = Informed</div>
            <div className="preview-cell preview-hide-mobile"></div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Tasks:</span>
              <span className="val">7</span>
            </div>
            <div className="preview-status-item">
              <span>Team Members:</span>
              <span className="val">4</span>
            </div>
            <div className="preview-status-item">
              <span>Roles Defined:</span>
              <span className="val">100%</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">RACI Matrix</button>
              <button className="preview-tab">Task Tracker</button>
              <button className="preview-tab">Team</button>
              <button className="preview-tab">Dashboard</button>
              <button className="preview-tab">+4</button>
            </div>
          </div>
        </div>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel RACI Matrix Template?</h2>
              <p className="intro">A structured spreadsheet used to define and organize project responsibilities across tasks, workflows, and team members.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel RACI matrix template</strong> is a structured spreadsheet used to define and organize project responsibilities across tasks, workflows, and team members. It helps businesses improve accountability, clarify decision-making roles, and streamline project coordination.
              </p>
              <p>
                A RACI spreadsheet typically includes <strong>tasks</strong>, <strong>team members</strong>, and <strong>responsibility assignments</strong> (Responsible, Accountable, Consulted, Informed) for each intersection. The RACI framework makes role clarity immediate — so you can coordinate workflows, prevent duplication, and see exactly who owns what.
              </p>
              <ul className="bulleted">
                <li><strong>Project tasks and workflows</strong> organized systematically</li>
                <li><strong>Team members and stakeholders</strong> mapped to each task</li>
                <li><strong>Responsibility assignments</strong> (R/A/C/I) clearly defined</li>
                <li><strong>Accountability tracking</strong> visible across the project</li>
                <li><strong>Workflow coordination</strong> streamlined and documented</li>
              </ul>
            </div>
          </div>
        </section>
      </div>

      {/* WHY RACI MATRIX SYSTEMS ARE IMPORTANT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Businesses Need RACI Matrix Systems</h2>
              <p className="intro">Managing projects without structured role assignment often creates workflow confusion and accountability gaps.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without structured role assignment</div>
                  <h3>Managing projects without structured role assignment often creates:</h3>
                  <ul>
                    <li>Unclear responsibilities</li>
                    <li>Workflow confusion</li>
                    <li>Team communication problems</li>
                    <li>Approval delays</li>
                    <li>Task duplication</li>
                    <li>Accountability gaps</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With a structured RACI matrix</div>
                  <h3>A properly organized RACI matrix helps businesses:</h3>
                  <ul>
                    <li>Improve project coordination</li>
                    <li>Clarify decision-making</li>
                    <li>Organize team workflows</li>
                    <li>Increase accountability</li>
                    <li>Improve collaboration</li>
                    <li>Reduce operational bottlenecks</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>From project description to RACI matrix in seconds.</h2>
              <p className="intro">Describe your workflow, and Formula Byte generates the complete spreadsheet — responsibilities, dashboards, and coordination tools included.</p>
            </div>
            <div className="row-body">
              <div className="steps">
                <div className="step">
                  <div className="step-num">1</div>
                  <div>
                    <h3>Describe your project</h3>
                    <p>Tasks, team members, departments, workflows — in plain English or a quick form.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">2</div>
                  <div>
                    <h3>AI builds the RACI matrix</h3>
                    <p>Responsibility assignments, role definitions, and accountability structures are wired to your inputs. Every cell updates automatically as you refine your matrix.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">3</div>
                  <div>
                    <h3>Dashboards generate themselves</h3>
                    <p>Role distribution charts, workflow timelines, and accountability visualizations appear on a dedicated dashboard sheet.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">4</div>
                  <div>
                    <h3>Track workflow progress</h3>
                    <p>Monitor task completion, stakeholder involvement, and team coordination across all your RACI-defined workflows.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CREATE AN AI RACI MATRIX SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI RACI Matrix Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe your project responsibilities, and Formula Byte automatically generates a professional Excel RACI matrix.</p>
            </div>
            <div className="row-body">
              <p>Describe your project responsibilities, and Formula Byte automatically generates a professional Excel RACI matrix template with:</p>
              <ul className="bulleted">
                <li>Responsibility assignment systems</li>
                <li>Team role tracking</li>
                <li>Accountability dashboards</li>
                <li>Workflow coordination tools</li>
                <li>Task ownership management</li>
                <li>Project collaboration systems</li>
                <li>Automated spreadsheet formulas</li>
                <li>Operational reporting dashboards</li>
                <li>Cross-functional visibility tools</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing project responsibilities, Formula Byte creates AI-powered RACI management systems tailored to your operational workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>What every generated <span className="serif-accent">RACI</span> matrix ships with.</h2>
              <p className="intro">Four pillars of responsibility tracking — automatic, accurate, and built to support real project decisions.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">R</div>
                  <h3>Responsibility assignment tracking</h3>
                  <p>Every task row records roles, owners, and stakeholders — the full responsibility map in one view.</p>
                  <ul>
                    <li>Task assignments &amp; roles</li>
                    <li>RACI codes (R/A/C/I)</li>
                    <li>Team member mapping</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">A</div>
                  <h3>Accountability dashboards</h3>
                  <p>See who owns what outcomes. The accountable stakeholders and approval workflows are clearly visible.</p>
                  <ul>
                    <li>Accountable stakeholders</li>
                    <li>Approval workflows</li>
                    <li>Decision-making ownership</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">T</div>
                  <h3>Team coordination systems</h3>
                  <p>Cross-functional collaboration tracking, stakeholder coordination, and department visibility — updated in real time.</p>
                  <ul>
                    <li>Team collaboration workflows</li>
                    <li>Department coordination</li>
                    <li>Stakeholder involvement</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">W</div>
                  <h3>Workflow project coordination</h3>
                  <p>Track operational workflows, task dependencies, and project progress across all RACI-assigned activities.</p>
                  <ul>
                    <li>Operational workflows</li>
                    <li>Task dependencies</li>
                    <li>Project coordination tracking</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI RESPONSIBILITY MANAGEMENT AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Responsibility Management Automation</h2>
              <p className="intro">Skip the manual setup. The AI understands RACI-related spreadsheet prompts instantly.</p>
            </div>
            <div className="row-body">
              <p>Traditional RACI spreadsheets require manual formatting and repetitive responsibility mapping.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure RACI matrices</li>
                <li>Generate responsibility tracking systems</li>
                <li>Organize workflow ownership</li>
                <li>Create accountability dashboards</li>
                <li>Build collaboration workflows</li>
                <li>Generate operational summaries</li>
                <li>Apply spreadsheet formatting automatically</li>
                <li>Automate project coordination systems</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands operational instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a project responsibility assignment matrix"</button>
                  <button className="chip">"Build a RACI workflow management dashboard"</button>
                  <button className="chip">"Generate a team accountability spreadsheet"</button>
                  <button className="chip">"Create a cross-functional collaboration tracker"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Eight worksheets, <span className="serif-accent">one</span> generation.</h2>
              <p className="intro">A complete RACI workspace — every sheet linked, every formula wired, every dashboard ready on open.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                  <div className="spec-head-cell">Type</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">RACI Matrix Dashboard</span>
                  <span className="spec-purpose">Central matrix showing tasks, team members, and RACI assignments.</span>
                  <span className="spec-tag">Core</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Task Responsibility Tracker</span>
                  <span className="spec-purpose">Organizes project ownership and task-level responsibilities.</span>
                  <span className="spec-tag">Core</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Team Collaboration Sheet</span>
                  <span className="spec-purpose">Tracks operational coordination and cross-functional workflows.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Accountability Dashboard</span>
                  <span className="spec-purpose">Monitors decision-making roles and approval workflows.</span>
                  <span className="spec-tag">Dashboard</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Workflow Assignment Tracker</span>
                  <span className="spec-purpose">Organizes operational workflows and dependencies.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Department Coordination</span>
                  <span className="spec-purpose">Manages cross-functional visibility and stakeholder mapping.</span>
                  <span className="spec-tag">Scenario</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Stakeholder Reporting</span>
                  <span className="spec-purpose">Tracks project communication and reporting workflows.</span>
                  <span className="spec-tag">Dashboard</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Operational Summary</span>
                  <span className="spec-purpose">Generates workflow insights and responsibility summaries.</span>
                  <span className="spec-tag">Report</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Under the hood</div>
              <h2>The formulas that <span className="serif-accent">do</span> the work.</h2>
              <p className="intro">Every Formula Byte RACI template is wired up with intelligent automation functions — generated, linked, and tested automatically.</p>
            </div>
            <div className="row-body">
              <div className="formula-grid">
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=IF</span>(<span className="arg">cell="R"</span>, <span className="str">"Responsible"</span>, <span className="arg">...</span>)</div>
                  <div className="formula-desc">Converts <em>RACI codes</em> into descriptive role labels.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=COUNTIF</span>(<span className="arg">range, "R"</span>)</div>
                  <div className="formula-desc">Counts <em>Responsible</em> assignments per team member.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=SUMIF</span>(<span className="arg">criteria_range, criteria, sum_range</span>)</div>
                  <div className="formula-desc">Calculates <em>workload distribution</em> across the team.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=INDEX/MATCH</span>(<span className="arg">lookup_value, lookup_array</span>)</div>
                  <div className="formula-desc">Finds <em>stakeholder assignments</em> across the matrix.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=COUNTA</span>(<span className="arg">range</span>)</div>
                  <div className="formula-desc">Tracks <em>total tasks</em> and team member count.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=CONCATENATE</span>(<span className="arg">text1, text2, ...</span>)</div>
                  <div className="formula-desc">Builds <em>role descriptions</em> from RACI codes.</div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Four project types, <span className="serif-accent">one</span> template engine.</h2>
              <p className="intro">Customize the matrix for any kind of workflow — same engine, different defaults.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">P</div>
                    <div>
                      <h4>Project Management RACI</h4>
                      <div className="industry-tagline">AGILE · WATERFALL · HYBRID</div>
                    </div>
                  </div>
                  <p>Track task assignments, team responsibilities, and approval workflows. Ideal for project managers and operational teams.</p>
                  <ul>
                    <li>Task assignments</li>
                    <li>Team responsibilities</li>
                    <li>Approval workflows</li>
                    <li>Operational accountability</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">I</div>
                    <div>
                      <h4>IT and Software Development</h4>
                      <div className="industry-tagline">DEV · QA · DEVOPS</div>
                    </div>
                  </div>
                  <p>Manage development workflows, team coordination, and sprint responsibilities. Built for software and IT departments.</p>
                  <ul>
                    <li>Development workflows</li>
                    <li>Team coordination</li>
                    <li>Sprint responsibilities</li>
                    <li>Stakeholder approvals</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">M</div>
                    <div>
                      <h4>Marketing Team Responsibility</h4>
                      <div className="industry-tagline">CAMPAIGNS · CONTENT · DIGITAL</div>
                    </div>
                  </div>
                  <p>Track campaign ownership, team collaboration, and content workflows. Designed for agencies and marketing teams.</p>
                  <ul>
                    <li>Campaign ownership</li>
                    <li>Team collaboration</li>
                    <li>Content workflows</li>
                    <li>Approval structures</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">C</div>
                    <div>
                      <h4>Construction Project RACI</h4>
                      <div className="industry-tagline">SITE · CONTRACTORS · SAFETY</div>
                    </div>
                  </div>
                  <p>Monitor site responsibilities, contractor assignments, and operational workflows. Useful for construction and operational management.</p>
                  <ul>
                    <li>Site responsibilities</li>
                    <li>Contractor assignments</li>
                    <li>Operational workflows</li>
                    <li>Approval management</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* OPERATIONAL REPORTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Operational Reports and Workflow Insights</h2>
              <p className="intro">Every generated RACI system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte RACI spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Responsibility summaries</li>
                <li>Accountability dashboards</li>
                <li>Workflow coordination reports</li>
                <li>Team collaboration insights</li>
                <li>Operational visibility reports</li>
                <li>Stakeholder communication summaries</li>
                <li>Department workflow dashboards</li>
                <li>Operational reporting summaries</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into operational structure and team accountability.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel RACI Spreadsheet vs Manual Responsibility Tracking</h2>
              <p className="intro">Most RACI templates are static spreadsheets. Formula Byte generates a system built around your workflow.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual responsibility tracking</div>
                  <h3>Spreadsheets built by hand</h3>
                  <ul>
                    <li>Manual role entry for every task</li>
                    <li>Time-consuming responsibility mapping</li>
                    <li>Error-prone formulas you rewrite</li>
                    <li>Limited workflow visibility</li>
                    <li>Role assignment gaps are painful</li>
                    <li>Basic tracking, no dashboards</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>Generated, automated, accurate</h3>
                  <ul>
                    <li>Automated responsibility assignment</li>
                    <li>Instant role calculations</li>
                    <li>Accountability accuracy guaranteed</li>
                    <li>Workflow coordination included</li>
                    <li>Role analysis built in</li>
                    <li>Dashboards on every generation</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-generated <span className="serif-accent">RACI</span> matrix templates.</h2>
              <p className="intro">Faster setup, fewer errors, clearer project decisions — every role you'd want already defined.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster workflow organization</h3>
                  <p>Generate complete responsibility management systems instantly instead of manually building spreadsheets.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">90%</span>
                    <span className="benefit-stat-label">Less setup time</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Better accountability visibility</h3>
                  <p>Structured RACI dashboards improve role clarity and operational organization.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">100%</span>
                    <span className="benefit-stat-label">Role accuracy</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Reduced workflow confusion</h3>
                  <p>Automated responsibility mapping reduces communication issues and operational overlaps.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Unlimited</span>
                    <span className="benefit-stat-label">Scenario testing</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Improved team collaboration</h3>
                  <p>Centralized coordination systems help teams stay aligned on responsibilities and approvals.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Built-in</span>
                    <span className="benefit-stat-label">Collaboration tools</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Easier project coordination</h3>
                  <p>Workflow dashboards improve visibility into project ownership and operational performance.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Real-time</span>
                    <span className="benefit-stat-label">Progress tracking</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Export and share</h3>
                  <p>Download your completed RACI matrix as an Excel file or open directly in Google Sheets — works everywhere your team works.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">2</span>
                    <span className="benefit-stat-label">Platform options</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing RACI <span className="serif-accent">Matrix</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated RACI spreadsheet into a real workflow management tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Define Roles Clearly</h3>
                  <p>Clear responsibility assignment improves accountability and workflow organization.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Update Responsibility Assignments Regularly</h3>
                  <p>Consistent updates improve operational visibility and team coordination.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Avoid Overlapping Ownership</h3>
                  <p>Structured accountability reduces workflow confusion and operational bottlenecks.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Review Workflow Coordination Frequently</h3>
                  <p>Regular reviews help identify:</p>
                  <ul>
                    <li>Responsibility gaps</li>
                    <li>Communication issues</li>
                    <li>Approval bottlenecks</li>
                    <li>Workflow inefficiencies</li>
                  </ul>
                  <div className="capability-close">This helps borrowers make smarter financing decisions.</div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most RACI templates are static spreadsheets. Formula Byte generates a system built around your workflow.</p>
            </div>
            <div className="row-body">
              <p>Most RACI templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated responsibility management systems tailored to your workflow structure, operational process, and collaboration requirements.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Responsibility matrices</li>
                <li>Accountability dashboards</li>
                <li>Workflow assignment systems</li>
                <li>Collaboration trackers</li>
                <li>Department coordination sheets</li>
                <li>Stakeholder reporting tools</li>
                <li>Operational visibility dashboards</li>
                <li>AI-powered workflow systems</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing team responsibilities, Formula Byte automates RACI spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This RACI Matrix <span className="serif-accent">Spreadsheet</span>?</h2>
              <p className="intro">This spreadsheet solution is ideal for teams and organizations managing projects of any kind.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Project managers</h4></div>
                <div className="audience-cell"><h4>Agencies</h4></div>
                <div className="audience-cell"><h4>Operations teams</h4></div>
                <div className="audience-cell"><h4>IT departments</h4></div>
                <div className="audience-cell"><h4>Construction companies</h4></div>
                <div className="audience-cell"><h4>Marketing teams</h4></div>
                <div className="audience-cell"><h4>Product managers</h4></div>
                <div className="audience-cell"><h4>Consultants</h4></div>
                <div className="audience-cell"><h4>Business owners</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple responsibility tracking or advanced workflow coordination, Formula Byte helps automate RACI spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating RACI matrices with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet assign responsibilities automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates RACI spreadsheets with structured role assignments, accountability systems, and workflow coordination tools.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include accountability and approval tracking?</summary>
                  <div className="faq-a">Yes. RACI templates can include approval workflows, stakeholder coordination systems, and accountability dashboards.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize team roles and workflow structures?</summary>
                  <div className="faq-a">Absolutely. Tasks, departments, workflows, dashboards, and responsibility structures can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte RACI templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for project management and operational coordination?</summary>
                  <div className="faq-a">Yes. Businesses commonly use RACI spreadsheets for project management, team collaboration, workflow organization, and accountability tracking.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other business templates you might need.</h2>
              <p className="intro">Same engine, different business workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/purchase-order-template/" className="related-card">
                  <div className="glyph">P</div>
                  <h4>Purchase Order</h4>
                  <p>Manage vendor purchases, track orders, and streamline procurement workflows.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/invoice-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Invoice Template</h4>
                  <p>Professional invoices with auto-numbering, taxes, and totals.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/business-budget-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Business Budget</h4>
                  <p>Plan expenses, track budgets, and manage cash flow effectively.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/kpi-template/" className="related-card">
                  <div className="glyph">K</div>
                  <h4>KPI Dashboard</h4>
                  <p>Track key performance indicators and monitor business metrics.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">RACI Matrix</span> Spreadsheet?</h2>
            <p>Stop managing responsibilities manually.</p>
            <p>Describe your workflow, and Formula Byte will generate a professional AI-powered Excel RACI matrix template with accountability dashboards, role assignment systems, workflow coordination tools, stakeholder tracking systems, and operational reporting workflows in seconds.</p>
            <p>Create smarter workflow management spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>
 

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}