export default function TimeTrackingTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=business">Business</a>
            <span className="sep">/</span>
            <span className="current">Time Tracking</span>
          </div>

          <div className="eyebrow">Business template</div>
          <h1>AI Excel Time Tracking Template for Payroll, Projects, and Workforce <span className="accent">Reporting</span></h1>
          <p className="lede">
            Track employee hours, project activities, billable time, and payroll calculations with an AI-generated Excel time tracking template designed for smarter workforce management and operational reporting. Formula Byte helps businesses automate time tracking using intelligent spreadsheets with project dashboards, payroll summaries, attendance monitoring systems, and productivity reporting workflows.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>12</strong> formulas built in</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate time tracking spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Agencies</span>
          <span className="use-case-pill"><span className="dot"></span>Freelancers</span>
          <span className="use-case-pill"><span className="dot"></span>Contractors</span>
          <span className="use-case-pill"><span className="dot"></span>Remote teams</span>
          <span className="use-case-pill"><span className="dot"></span>HR departments</span>
          <span className="use-case-pill"><span className="dot"></span>Project managers</span>
          <span className="use-case-pill"><span className="dot"></span>Payroll operations</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Time-Tracking<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">D4</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=SUM</span>(<span className="num">B2:B8</span>) * <span className="num">24</span>
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header preview-hide-mobile">F</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Employee</div>
            <div className="preview-cell preview-header-cell">Mon</div>
            <div className="preview-cell preview-header-cell">Tue</div>
            <div className="preview-cell preview-header-cell">Wed</div>
            <div className="preview-cell preview-header-cell">Thu</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Fri</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">John Smith</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell">8.5</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell">9.0</div>
            <div className="preview-cell preview-hide-mobile">8.0</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">Sarah Johnson</div>
            <div className="preview-cell">7.5</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell preview-hide-mobile">7.0</div>

            {/* Row 4 — selected */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">Mike Davis</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell selected">9.5</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell preview-hide-mobile">8.0</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">Emily Chen</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell">8.0</div>
            <div className="preview-cell preview-hide-mobile">8.0</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Total Hours</div>
            <div className="preview-cell total">39.5</div>
            <div className="preview-cell total">40.5</div>
            <div className="preview-cell total">41.5</div>
            <div className="preview-cell total">41.0</div>
            <div className="preview-cell total preview-hide-mobile">39.0</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">Payroll ($24/hr)</div>
            <div className="preview-cell payroll">$948.00</div>
            <div className="preview-cell payroll">$972.00</div>
            <div className="preview-cell payroll">$996.00</div>
            <div className="preview-cell payroll">$984.00</div>
            <div className="preview-cell payroll preview-hide-mobile">$936.00</div>

            {/* Row 8 — sparkline */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell faded">…</div>
            <div className="preview-cell sparkline" style={{gridColumn: 'span 2'}}>
              <svg width="140" height="22" viewBox="0 0 140 22" preserveAspectRatio="none">
                <defs>
                  <linearGradient id="spark-grad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="#8171D0" stopOpacity="0.35"/>
                    <stop offset="100%" stopColor="#8171D0" stopOpacity="0"/>
                  </linearGradient>
                </defs>
                <path d="M0,3 L14,4 L28,5 L42,7 L56,9 L70,11 L84,13 L98,15 L112,17 L126,19 L140,21 L140,22 L0,22 Z" fill="url(#spark-grad)"/>
                <path d="M0,3 L14,4 L28,5 L42,7 L56,9 L70,11 L84,13 L98,15 L112,17 L126,19 L140,21" fill="none" stroke="#8171D0" strokeWidth="1.5"/>
              </svg>
            </div>
            <div className="preview-cell faded preview-hide-mobile">↓ falling</div>

            {/* Row 9 - last row */}
            <div className="preview-row-num">9</div>
            <div className="preview-cell text">Weekly Total</div>
            <div className="preview-cell total">41.5</div>
            <div className="preview-cell total">42.5</div>
            <div className="preview-cell total">43.5</div>
            <div className="preview-cell total">42.0</div>
            <div className="preview-cell total preview-hide-mobile">40.0</div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Employees:</span>
              <span className="val">15</span>
            </div>
            <div className="preview-status-item">
              <span>Total hours:</span>
              <span className="val">620</span>
            </div>
            <div className="preview-status-item">
              <span>Billable:</span>
              <span className="val">75%</span>
            </div>
            <div className="preview-status-item">
              <span>Total payroll:</span>
              <span className="val serif">$14,880</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">Summary</button>
              <button className="preview-tab">Employees</button>
              <button className="preview-tab">Projects</button>
              <button className="preview-tab">+5</button>
            </div>
          </div>
        </div>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What is an Excel Time Tracking Template?</h2>
              <p className="intro">A structured spreadsheet used to monitor employee work hours, project activities, billable time, payroll calculations, and productivity metrics.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel time tracking template</strong> is a workforce management tool that records employee hours and project-related activities within a structured reporting system. It helps businesses improve workforce visibility while simplifying payroll processing and operational reporting.
              </p>
              <p>
                Time tracking spreadsheets typically include <strong>employee names</strong>, <strong>project details</strong>, <strong>daily work hours</strong>, <strong>billable hour tracking</strong>, <strong>attendance records</strong>, <strong>hourly pay rates</strong>, <strong>payroll calculations</strong>, <strong>productivity reporting</strong>, and <strong>workforce dashboards</strong>.
              </p>
              <p>
                Formula Byte generates AI-powered time tracking spreadsheets designed for workforce organization, payroll management, and project reporting workflows.
              </p>
              <ul className="bulleted">
                <li><strong>Employee hour logging</strong> tracks daily work hours and attendance</li>
                <li><strong>Project-based time tracking</strong> monitors billable and non-billable activities</li>
                <li><strong>Payroll summaries</strong> calculate compensation automatically</li>
                <li><strong>Attendance monitoring</strong> improves workforce visibility</li>
                <li><strong>Productivity dashboards</strong> provide operational insights</li>
              </ul>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How Time Tracking Works</h2>
              <p className="intro">Time tracking records employee hours and project activities within a structured payroll calculation system.</p>
            </div>
            <div className="row-body">
              <p>
                The standard payroll calculation structure follows:
              </p>
              <p className="formula-text" style={{textAlign: 'center', margin: '12px 0', fontSize: '15px', fontWeight: '600'}}>
                Total Pay = Hours Worked × Hourly Rate
              </p>
              <p>
                A structured time tracking system helps businesses:
              </p>
              <ul className="bulleted">
                <li>Monitor employee productivity</li>
                <li>Track project hours</li>
                <li>Calculate payroll accurately</li>
                <li>Improve operational visibility</li>
                <li>Analyze workforce efficiency</li>
                <li>Organize attendance records</li>
                <li>Simplify project reporting</li>
              </ul>
              <p style={{marginTop: '12px'}}>
                Most time tracking systems include <strong>employee hour logging</strong>, <strong>payroll summaries</strong>, <strong>project tracking</strong>, <strong>attendance monitoring</strong>, <strong>productivity analysis</strong>, <strong>billable hour calculations</strong>, and <strong>workforce dashboards</strong>.
              </p>
              <p style={{marginTop: '12px'}}>
                Formula Byte simplifies this process using AI-generated workforce spreadsheets and automated reporting systems.
              </p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY BUSINESSES NEED TIME TRACKING */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Businesses Need Time Tracking Systems</h2>
              <p className="intro">Managing employee hours without structured tracking creates payroll inconsistencies and operational inefficiencies.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without time tracking</div>
                  <h3>Managing employee hours without structured tracking often creates:</h3>
                  <ul>
                    <li>Payroll inconsistencies</li>
                    <li>Inaccurate billing</li>
                    <li>Poor project visibility</li>
                    <li>Attendance tracking issues</li>
                    <li>Operational inefficiencies</li>
                    <li>Resource allocation problems</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With time tracking systems</div>
                  <h3>A properly organized time tracking spreadsheet helps businesses:</h3>
                  <ul>
                    <li>Improve payroll accuracy</li>
                    <li>Monitor workforce performance</li>
                    <li>Track project profitability</li>
                    <li>Organize attendance data</li>
                    <li>Improve operational planning</li>
                    <li>Increase employee accountability</li>
                    <li>Simplify business reporting</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>From workforce needs to complete time tracking in seconds.</h2>
              <p className="intro">Describe your workforce tracking requirements, and Formula Byte generates the complete spreadsheet — formulas, dashboards, and reporting workflows included.</p>
            </div>
            <div className="row-body">
              <div className="steps">
                <div className="step">
                  <div className="step-num">1</div>
                  <div>
                    <h3>Describe your workforce needs</h3>
                    <p>Employee count, projects, payroll requirements, attendance rules — in plain English or a quick form.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">2</div>
                  <div>
                    <h3>AI builds the time tracking system</h3>
                    <p>Hour calculations, payroll formulas, and project tracking are wired to your inputs. Every entry recalculates automatically as hours change.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">3</div>
                  <div>
                    <h3>Dashboards generate themselves</h3>
                    <p>Attendance charts, payroll summaries, and productivity trends appear on dedicated dashboard sheets.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">4</div>
                  <div>
                    <h3>Track billable hours</h3>
                    <p>Monitor project profitability, client billing, and resource allocation with automated time tracking and reporting.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CREATE AN AI TIME TRACKING SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Time Tracking Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the workforce tracking spreadsheet you need, and Formula Byte automatically generates a professional Excel time tracking template.</p>
            </div>
            <div className="row-body">
              <p>Describe the workforce tracking spreadsheet you need, and Formula Byte automatically generates a professional Excel time tracking template with:</p>
              <ul className="bulleted">
                <li>Employee hour tracking</li>
                <li>Project-based time logging</li>
                <li>Billable hour calculations</li>
                <li>Payroll summaries</li>
                <li>Attendance monitoring</li>
                <li>Productivity reporting</li>
                <li>Automated spreadsheet formulas</li>
                <li>Workforce dashboards</li>
                <li>Operational reporting systems</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually tracking employee hours and project tasks, Formula Byte creates AI-powered time management systems tailored to your workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI Time Tracking <span className="serif-accent">Spreadsheet</span></h2>
              <p className="intro">Four pillars of workforce tracking — automatic, accurate, and built to support real business decisions.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">👥</div>
                  <h3>Employee Hour and Attendance Tracking</h3>
                  <p>Track employee names, daily work hours, clock-in and clock-out times, attendance records, overtime hours, break periods, and shift schedules.</p>
                  <ul>
                    <li>Employee names</li>
                    <li>Daily work hours</li>
                    <li>Clock-in and clock-out times</li>
                    <li>Attendance records</li>
                    <li>Overtime hours</li>
                    <li>Break periods</li>
                    <li>Shift schedules</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">📊</div>
                  <h3>Project and Task Tracking</h3>
                  <p>Monitor project names, task descriptions, billable activities, non-billable work, project timelines, team assignments, and operational workflows.</p>
                  <ul>
                    <li>Project names</li>
                    <li>Task descriptions</li>
                    <li>Billable activities</li>
                    <li>Non-billable work</li>
                    <li>Project timelines</li>
                    <li>Team assignments</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">💰</div>
                  <h3>Payroll and Compensation Management</h3>
                  <p>Formula Byte time tracking spreadsheets can include hourly pay rates, payroll summaries, overtime calculations, compensation reports, employee payment tracking, and payroll forecasting dashboards.</p>
                  <ul>
                    <li>Hourly pay rates</li>
                    <li>Payroll summaries</li>
                    <li>Overtime calculations</li>
                    <li>Compensation reports</li>
                    <li>Employee payment tracking</li>
                    <li>Payroll forecasting dashboards</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">📈</div>
                  <h3>Productivity and Reporting Dashboards</h3>
                  <p>Track employee productivity, billable utilization, project efficiency, operational performance, team activity summaries, and time allocation trends.</p>
                  <ul>
                    <li>Employee productivity</li>
                    <li>Billable utilization</li>
                    <li>Project efficiency</li>
                    <li>Operational performance</li>
                    <li>Team activity summaries</li>
                    <li>Time allocation trends</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI WORKFORCE REPORTING AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Workforce Reporting Automation</h2>
              <p className="intro">Traditional time tracking spreadsheets require manual formatting and repetitive calculations.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure workforce systems</li>
                <li>Generate project tracking dashboards</li>
                <li>Organize payroll workflows</li>
                <li>Create attendance monitoring tools</li>
                <li>Build productivity reports</li>
                <li>Generate operational summaries</li>
                <li>Apply spreadsheet formatting automatically</li>
                <li>Automate time tracking workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands workforce management instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a project-based employee time tracker"</button>
                  <button className="chip">"Build a payroll and productivity dashboard"</button>
                  <button className="chip">"Generate a freelancer billable hours spreadsheet"</button>
                  <button className="chip">"Create a remote team attendance system"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Time Tracking Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete time tracking spreadsheet may include these worksheets.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-name">Employee Time Tracker</span>
                  <span className="spec-purpose">Monitors work hours and attendance</span>
                </div>
                <div className="spec-row">
                  <span className="spec-name">Project Activity Sheet</span>
                  <span className="spec-purpose">Tracks project tasks and billable time</span>
                </div>
                <div className="spec-row">
                  <span className="spec-name">Payroll Dashboard</span>
                  <span className="spec-purpose">Calculates employee compensation</span>
                </div>
                <div className="spec-row">
                  <span className="spec-name">Attendance Monitoring Tracker</span>
                  <span className="spec-purpose">Organizes workforce schedules</span>
                </div>
                <div className="spec-row">
                  <span className="spec-name">Productivity Reporting Dashboard</span>
                  <span className="spec-purpose">Measures operational performance</span>
                </div>
                <div className="spec-row">
                  <span className="spec-name">Billable Hours Summary</span>
                  <span className="spec-purpose">Tracks client billing time</span>
                </div>
                <div className="spec-row">
                  <span className="spec-name">Workforce Analytics Sheet</span>
                  <span className="spec-purpose">Visualizes workforce insights</span>
                </div>
                <div className="spec-row">
                  <span className="spec-name">Operational Reporting Dashboard</span>
                  <span className="spec-purpose">Generates business reports</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Under the hood</div>
              <h2>Built-In Excel Formulas and Time Tracking <span className="serif-accent">Automation</span></h2>
              <p className="intro">Formula Byte time tracking templates can include hour calculations, payroll formulas, overtime tracking systems, conditional formatting, productivity dashboards, attendance summaries, project tracking formulas, and workforce reporting automation.</p>
            </div>
            <div className="row-body">
              <p>These spreadsheet automations improve payroll accuracy and reduce manual workforce management work.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Time Tracking Templates by <span className="serif-accent">Use Case</span></h2>
              <p className="intro">Customize the time tracking for any kind of workforce — same engine, different defaults.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">S</div>
                    <div>
                      <h4>Small Business Time Tracking Spreadsheet</h4>
                      <div className="industry-tagline">STARTUPS · RETAIL · SERVICE</div>
                    </div>
                  </div>
                  <p>Track employee attendance, work hours, payroll summaries, project tasks, and workforce productivity. Ideal for startups and growing businesses.</p>
                  <ul>
                    <li>Employee attendance</li>
                    <li>Work hours</li>
                    <li>Payroll summaries</li>
                    <li>Project tasks</li>
                    <li>Workforce productivity</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">F</div>
                    <div>
                      <h4>Freelancer Billable Hours Template</h4>
                      <div className="industry-tagline">BILLABLE · PROJECTS · HOURLY</div>
                    </div>
                  </div>
                  <p>Manage client work hours, project billing, task tracking, revenue reporting, and productivity monitoring. Useful for freelancers and consultants.</p>
                  <ul>
                    <li>Client work hours</li>
                    <li>Project billing</li>
                    <li>Task tracking</li>
                    <li>Revenue reporting</li>
                    <li>Productivity monitoring</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">A</div>
                    <div>
                      <h4>Agency Workforce Tracking Dashboard</h4>
                      <div className="industry-tagline">TEAMS · CLIENTS · BILLABLE</div>
                    </div>
                  </div>
                  <p>Track team productivity, client projects, billable utilization, operational workflows, and payroll reporting. Designed for agencies and operational teams.</p>
                  <ul>
                    <li>Team productivity</li>
                    <li>Client projects</li>
                    <li>Billable utilization</li>
                    <li>Operational workflows</li>
                    <li>Payroll reporting</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">R</div>
                    <div>
                      <h4>Remote Team Time Tracking Spreadsheet</h4>
                      <div className="industry-tagline">REMOTE · HYBRID · DISTRIBUTED</div>
                    </div>
                  </div>
                  <p>Monitor remote attendance, project collaboration, task completion, workforce visibility, and productivity reporting. Useful for distributed teams and remote operations.</p>
                  <ul>
                    <li>Remote attendance</li>
                    <li>Project collaboration</li>
                    <li>Task completion</li>
                    <li>Workforce visibility</li>
                    <li>Productivity reporting</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* PAYROLL REPORTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Payroll Reports and Workforce <span className="serif-accent">Insights</span></h2>
              <p className="intro">Every generated time tracking system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte time tracking spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Payroll summaries</li>
                <li>Attendance reports</li>
                <li>Billable hour dashboards</li>
                <li>Workforce productivity reports</li>
                <li>Project efficiency insights</li>
                <li>Employee hour summaries</li>
                <li>Operational analytics dashboards</li>
                <li>Payroll analysis reports</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into workforce operations and business performance.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Time Tracking Spreadsheet vs Manual <span className="serif-accent">Workforce Tracking</span></h2>
              <p className="intro">Most time tracking methods are manual and error-prone. Formula Byte generates a system built around your workforce.</p>
            </div>
            <div className="row-body">
              <table className="compare-table">
                <thead>
                  <tr>
                    <th>Feature</th>
                    <th>AI Time Tracking Spreadsheet</th>
                    <th>Manual Tracking</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Payroll Calculations</td>
                    <td>Automated</td>
                    <td>Manual</td>
                  </tr>
                  <tr>
                    <td>Workforce Visibility</td>
                    <td>Dashboard-based</td>
                    <td>Limited</td>
                  </tr>
                  <tr>
                    <td>Project Tracking</td>
                    <td>Organized</td>
                    <td>Often inconsistent</td>
                  </tr>
                  <tr>
                    <td>Attendance Monitoring</td>
                    <td>Structured</td>
                    <td>Difficult to manage</td>
                  </tr>
                  <tr>
                    <td>Spreadsheet Setup</td>
                    <td>Fast</td>
                    <td>Time-consuming</td>
                  </tr>
                  <tr>
                    <td>Productivity Reporting</td>
                    <td>Automated</td>
                    <td>Basic tracking</td>
                  </tr>
                  <tr>
                    <td>Operational Insights</td>
                    <td>Included</td>
                    <td>Limited</td>
                  </tr>
                </tbody>
              </table>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify workforce management and operational reporting.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">Time Tracking</span> Templates</h2>
              <p className="intro">Faster setup, fewer errors, sharper workforce decisions — every hour tracked accurately.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster Workforce Organization</h3>
                  <p>Generate complete time tracking systems instantly without manually building spreadsheets.</p>
                </div>
                <div className="benefit-card">
                  <h3>Better Payroll Visibility</h3>
                  <p>Structured dashboards improve attendance tracking and payroll organization.</p>
                </div>
                <div className="benefit-card">
                  <h3>Reduced Reporting Errors</h3>
                  <p>Automated formulas reduce payroll mistakes and time tracking inconsistencies.</p>
                </div>
                <div className="benefit-card">
                  <h3>Improved Productivity Monitoring</h3>
                  <p>Workforce dashboards help businesses analyze operational performance and employee efficiency.</p>
                </div>
                <div className="benefit-card">
                  <h3>Easier Project Billing</h3>
                  <p>Project-based tracking systems simplify billable hour reporting and client invoicing.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing Time Tracking <span className="serif-accent">Spreadsheets</span></h2>
              <p className="intro">Four habits that turn a generated time tracking spreadsheet into a real workforce management tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Update Work Hours Daily</h3>
                  <p>Consistent updates improve payroll accuracy and operational visibility.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Track Billable and Non-Billable Time Separately</h3>
                  <p>Structured time categories improve project reporting and profitability analysis.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Monitor Productivity Trends Regularly</h3>
                  <p>Tracking workforce performance helps identify:</p>
                  <ul>
                    <li>Operational inefficiencies</li>
                    <li>Resource allocation issues</li>
                    <li>Payroll inconsistencies</li>
                    <li>Productivity bottlenecks</li>
                    <li>Workforce optimization opportunities</li>
                  </ul>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Maintain Accurate Attendance Records</h3>
                  <p>Reliable attendance tracking improves workforce coordination and payroll compliance.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most time tracking templates are static spreadsheets with limited flexibility.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte creates AI-generated workforce management systems tailored to your payroll workflow, project structure, and operational reporting requirements.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Employee time trackers</li>
                <li>Payroll dashboards</li>
                <li>Attendance monitoring systems</li>
                <li>Billable hour reports</li>
                <li>Productivity dashboards</li>
                <li>Workforce analytics tools</li>
                <li>Project reporting systems</li>
                <li>AI-powered operational workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing employee hours and payroll data, Formula Byte automates time tracking spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This Time Tracking <span className="serif-accent">Spreadsheet</span>?</h2>
              <p className="intro">This spreadsheet solution is ideal for businesses and teams managing employee hours and payroll of any kind.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>Agencies</h4></div>
                <div className="audience-cell"><h4>Freelancers</h4></div>
                <div className="audience-cell"><h4>Contractors</h4></div>
                <div className="audience-cell"><h4>HR departments</h4></div>
                <div className="audience-cell"><h4>Remote teams</h4></div>
                <div className="audience-cell"><h4>Payroll managers</h4></div>
                <div className="audience-cell"><h4>Operations teams</h4></div>
                <div className="audience-cell"><h4>Business owners</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple attendance tracking or advanced project-based workforce reporting, Formula Byte helps automate time tracking spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating time tracking spreadsheets with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet calculate payroll automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates time tracking spreadsheets with automated hour calculations, payroll summaries, and overtime tracking systems.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include project and billable hour tracking?</summary>
                  <div className="faq-a">Yes. Time tracking templates can include project reporting systems, billable hour dashboards, and workforce productivity tools.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize workforce categories and reporting layouts?</summary>
                  <div className="faq-a">Absolutely. Employee records, projects, payroll systems, attendance workflows, and dashboards can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte time tracking templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for payroll and operational reporting?</summary>
                  <div className="faq-a">Yes. Businesses commonly use time tracking spreadsheets for workforce management, payroll processing, attendance tracking, and project reporting.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other business templates you might need.</h2>
              <p className="intro">Same engine, different business workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/invoice-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Invoice Template</h4>
                  <p>Professional invoices with auto-numbering, taxes, and totals.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/business-budget-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Business Budget</h4>
                  <p>Plan expenses, track budgets, and manage cash flow effectively.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/kpi-template/" className="related-card">
                  <div className="glyph">K</div>
                  <h4>KPI Dashboard</h4>
                  <p>Track key performance indicators and monitor business metrics.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/purchase-order-template/" className="related-card">
                  <div className="glyph">P</div>
                  <h4>Purchase Order</h4>
                  <p>Manage vendor purchases, track orders, and streamline procurement workflows.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">Time Tracking</span> Spreadsheet?</h2>
            <p>Stop tracking work hours manually.</p>
            <p>Describe your workforce workflow, and Formula Byte will generate a professional AI-powered Excel time tracking template with payroll dashboards, project tracking systems, attendance monitoring tools, billable hour workflows, and operational reporting systems in seconds.</p>
            <p>Create smarter workforce management spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>


      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}