export default function TimeSheetTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=business">Business</a>
            <span className="sep">/</span>
            <span className="current">Time Sheet</span>
          </div>

          <div className="eyebrow">Business template</div>
          <h1>AI Excel Time Sheet Template for Employee Hours and Payroll <span className="accent">Tracking</span></h1>
          <p className="lede">
            Track employee work hours, overtime, tasks, and payroll calculations with an AI-generated Excel time sheet template designed for smarter workforce management and payroll processing. Formula Byte helps businesses automate time tracking using intelligent spreadsheets with attendance dashboards, employee hour calculations, overtime monitoring systems, and payroll reporting workflows.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>12</strong> formulas built in</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate time sheet spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Small businesses</span>
          <span className="use-case-pill"><span className="dot"></span>Agencies</span>
          <span className="use-case-pill"><span className="dot"></span>Construction teams</span>
          <span className="use-case-pill"><span className="dot"></span>Remote teams</span>
          <span className="use-case-pill"><span className="dot"></span>HR departments</span>
          <span className="use-case-pill"><span className="dot"></span>Payroll management</span>
          <span className="use-case-pill"><span className="dot"></span>Freelancers</span>
          <span className="use-case-pill"><span className="dot"></span>Shift-based operations</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">RACI-Matrix<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">E5</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=IF</span>(<span className="num">D5</span>=<span className="str">"R"</span>,<span className="str">"Responsible"</span>,<span className="num">D5</span>=<span className="str">"A"</span>,<span className="str">"Accountable"</span>,<span className="str">""</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header preview-hide-mobile">F</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Task</div>
            <div className="preview-cell preview-header-cell">Project Manager</div>
            <div className="preview-cell preview-header-cell">Team Lead</div>
            <div className="preview-cell preview-header-cell">Developer</div>
            <div className="preview-cell preview-header-cell">Status</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Notes</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">Requirements Gathering</div>
            <div className="preview-cell selected">R</div>
            <div className="preview-cell">A</div>
            <div className="preview-cell">C</div>
            <div className="preview-cell text">In Progress</div>
            <div className="preview-cell preview-hide-mobile">Stakeholder input</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">Design Approval</div>
            <div className="preview-cell">A</div>
            <div className="preview-cell selected">R</div>
            <div className="preview-cell">C</div>
            <div className="preview-cell text">Pending</div>
            <div className="preview-cell preview-hide-mobile">UX review needed</div>

            {/* Row 4 — selected */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">Development</div>
            <div className="preview-cell">I</div>
            <div className="preview-cell">A</div>
            <div className="preview-cell selected">R</div>
            <div className="preview-cell text">Not Started</div>
            <div className="preview-cell preview-hide-mobile">Sprint planning</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">Testing</div>
            <div className="preview-cell">I</div>
            <div className="preview-cell">C</div>
            <div className="preview-cell selected">R</div>
            <div className="preview-cell text">Not Started</div>
            <div className="preview-cell preview-hide-mobile">QA assigned</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">Deployment</div>
            <div className="preview-cell selected">A</div>
            <div className="preview-cell">C</div>
            <div className="preview-cell">I</div>
            <div className="preview-cell text">Not Started</div>
            <div className="preview-cell preview-hide-mobile">Production release</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">Documentation</div>
            <div className="preview-cell">I</div>
            <div className="preview-cell selected">R</div>
            <div className="preview-cell">C</div>
            <div className="preview-cell text">Not Started</div>
            <div className="preview-cell preview-hide-mobile">User guides</div>

            {/* Row 8 — sparkline */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell faded">…</div>
            <div className="preview-cell faded preview-hide-mobile">…</div>

            {/* Row 9 - legend */}
            <div className="preview-row-num">9</div>
            <div className="preview-cell preview-header-cell">RACI Legend</div>
            <div className="preview-cell text"><strong>R</strong> = Responsible</div>
            <div className="preview-cell text"><strong>A</strong> = Accountable</div>
            <div className="preview-cell text"><strong>C</strong> = Consulted</div>
            <div className="preview-cell text"><strong>I</strong> = Informed</div>
            <div className="preview-cell preview-hide-mobile"></div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Tasks:</span>
              <span className="val">7</span>
            </div>
            <div className="preview-status-item">
              <span>Team Members:</span>
              <span className="val">4</span>
            </div>
            <div className="preview-status-item">
              <span>Roles Defined:</span>
              <span className="val">100%</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">RACI Matrix</button>
              <button className="preview-tab">Task Tracker</button>
              <button className="preview-tab">Team</button>
              <button className="preview-tab">Dashboard</button>
              <button className="preview-tab">+4</button>
            </div>
          </div>
        </div>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel Time Sheet Template?</h2>
              <p className="intro">A structured spreadsheet used to track employee work hours, attendance, overtime, tasks, and payroll-related information.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel time sheet template</strong> is a structured spreadsheet used to track employee work hours, attendance, overtime, tasks, and payroll-related information. It helps businesses organize workforce records while improving payroll accuracy and operational visibility.
              </p>
              <p>
                A time sheet spreadsheet typically includes <strong>employee information</strong>, <strong>clock-in and clock-out times</strong>, <strong>daily work hours</strong>, <strong>overtime tracking</strong>, and <strong>payroll calculations</strong>. The structured format makes payroll processing immediate — so you can calculate wages, monitor attendance, and see exactly what you owe each employee.
              </p>
              <ul className="bulleted">
                <li><strong>Employee information</strong> organized systematically</li>
                <li><strong>Clock-in and clock-out times</strong> tracked daily</li>
                <li><strong>Daily work hours</strong> calculated automatically</li>
                <li><strong>Overtime tracking</strong> visible across pay periods</li>
                <li><strong>Payroll summaries</strong> generated automatically</li>
              </ul>
            </div>
          </div>
        </section>
      </div>

      {/* WHY TIME SHEET SYSTEMS ARE IMPORTANT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Businesses Need Time Sheet Systems</h2>
              <p className="intro">Managing employee hours without a structured system often creates payroll errors and workflow confusion.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without a structured system</div>
                  <h3>Managing employee hours without a structured system often creates:</h3>
                  <ul>
                    <li>Payroll calculation errors</li>
                    <li>Attendance inconsistencies</li>
                    <li>Overtime tracking issues</li>
                    <li>Workforce scheduling confusion</li>
                    <li>Poor operational visibility</li>
                    <li>Compliance risks</li>
                    <li>Delayed payroll processing</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With a structured time sheet system</div>
                  <h3>A properly organized time sheet spreadsheet helps businesses:</h3>
                  <ul>
                    <li>Improve payroll accuracy</li>
                    <li>Monitor employee attendance</li>
                    <li>Organize workforce schedules</li>
                    <li>Track overtime efficiently</li>
                    <li>Simplify payroll workflows</li>
                    <li>Improve operational planning</li>
                    <li>Increase workforce accountability</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>From workforce tracking to payroll calculations in seconds.</h2>
              <p className="intro">Describe your workforce workflow, and Formula Byte generates the complete spreadsheet — attendance, hours, overtime, and payroll included.</p>
            </div>
            <div className="row-body">
              <div className="steps">
                <div className="step">
                  <div className="step-num">1</div>
                  <div>
                    <h3>Describe your workforce</h3>
                    <p>Employees, shifts, pay rates, work schedule — in plain English or a quick form.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">2</div>
                  <div>
                    <h3>AI builds the time sheet</h3>
                    <p>Hour calculations, overtime formulas, and payroll structures are wired to your inputs. Every cell updates automatically as you log hours.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">3</div>
                  <div>
                    <h3>Dashboards generate themselves</h3>
                    <p>Attendance charts, overtime tracking, payroll summaries, and workforce visualizations appear on a dedicated dashboard sheet.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">4</div>
                  <div>
                    <h3>Calculate payroll instantly</h3>
                    <p>Monitor total hours, regular and overtime pay, tax withholdings, and net pay across all your employee records.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CREATE AN AI TIME SHEET SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Time Sheet Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the workforce tracking spreadsheet you need, and Formula Byte automatically generates a professional Excel time sheet.</p>
            </div>
            <div className="row-body">
              <p>Describe the workforce tracking spreadsheet you need, and Formula Byte automatically generates a professional Excel time sheet template with:</p>
              <ul className="bulleted">
                <li>Employee hour tracking</li>
                <li>Overtime calculations</li>
                <li>Attendance monitoring</li>
                <li>Payroll summaries</li>
                <li>Task management sections</li>
                <li>Shift scheduling systems</li>
                <li>Automated spreadsheet formulas</li>
                <li>Workforce dashboards</li>
                <li>Payroll reporting workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually calculating work hours and payroll data, Formula Byte creates AI-powered time tracking systems tailored to your operational workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>What every generated <span className="serif-accent">time sheet</span> ships with.</h2>
              <p className="intro">Four pillars of workforce tracking — automatic, accurate, and built to support real payroll decisions.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">👥</div>
                  <h3>Employee Attendance Tracking</h3>
                  <p>Every employee row records clock-in, clock-out, breaks, and attendance — the full workforce map in one view.</p>
                  <ul>
                    <li>Employee names &amp; IDs</li>
                    <li>Clock-in/clock-out times</li>
                    <li>Shift schedules</li>
                    <li>Absence tracking</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">⏱</div>
                  <h3>Work Hour and Overtime Calculations</h3>
                  <p>See total hours, regular time, and overtime at a glance. The payroll calculations are clearly visible.</p>
                  <ul>
                    <li>Daily work hours</li>
                    <li>Weekly totals</li>
                    <li>Overtime hours</li>
                    <li>Payroll hours</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">💰</div>
                  <h3>Payroll and Pay Rate Management</h3>
                  <p>Hourly rates, overtime multipliers, and wage tracking — updated in real time with every entry.</p>
                  <ul>
                    <li>Hourly pay rates</li>
                    <li>Overtime calculations</li>
                    <li>Payroll summaries</li>
                    <li>Compensation reports</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">📊</div>
                  <h3>Task and Productivity Tracking</h3>
                  <p>Monitor completed tasks, project assignments, and operational workflows across all employee activities.</p>
                  <ul>
                    <li>Completed tasks</li>
                    <li>Project assignments</li>
                    <li>Daily responsibilities</li>
                    <li>Team performance</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI WORKFORCE MANAGEMENT AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Workforce Management Automation</h2>
              <p className="intro">Skip the manual setup. The AI understands workforce management spreadsheet prompts instantly.</p>
            </div>
            <div className="row-body">
              <p>Traditional time sheet spreadsheets require manual formatting and repetitive payroll calculations.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure workforce tracking systems</li>
                <li>Generate payroll dashboards</li>
                <li>Organize attendance records</li>
                <li>Create overtime monitoring tools</li>
                <li>Build shift scheduling systems</li>
                <li>Generate payroll summaries</li>
                <li>Apply spreadsheet formatting automatically</li>
                <li>Automate workforce workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands workforce management instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a weekly employee time sheet"</button>
                  <button className="chip">"Build a payroll and attendance dashboard"</button>
                  <button className="chip">"Generate a contractor work hour tracker"</button>
                  <button className="chip">"Create a shift scheduling and overtime system"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Eight worksheets, <span className="serif-accent">one</span> generation.</h2>
              <p className="intro">A complete time sheet workspace — every sheet linked, every formula wired, every dashboard ready on open.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                  <div className="spec-head-cell">Type</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Employee Time Tracker</span>
                  <span className="spec-purpose">Monitors attendance and work hours for each employee.</span>
                  <span className="spec-tag">Core</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Payroll Dashboard</span>
                  <span className="spec-purpose">Calculates payroll summaries and total compensation.</span>
                  <span className="spec-tag">Core</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Overtime Monitoring Sheet</span>
                  <span className="spec-purpose">Tracks extra work hours and overtime pay calculations.</span>
                  <span className="spec-tag">Analysis</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Shift Scheduling Tracker</span>
                  <span className="spec-purpose">Organizes workforce schedules and shift assignments.</span>
                  <span className="spec-tag">Schedule</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Attendance Report</span>
                  <span className="spec-purpose">Tracks employee attendance and absence records.</span>
                  <span className="spec-tag">Report</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Task Management Sheet</span>
                  <span className="spec-purpose">Monitors completed work and project assignments.</span>
                  <span className="spec-tag">Productivity</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Workforce Summary Dashboard</span>
                  <span className="spec-purpose">Visualizes workforce metrics and attendance trends.</span>
                  <span className="spec-tag">Dashboard</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Payroll Reporting Sheet</span>
                  <span className="spec-purpose">Generates payroll insights and compensation summaries.</span>
                  <span className="spec-tag">Report</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN FORMULAS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Under the hood</div>
              <h2>The formulas that <span className="serif-accent">do</span> the work.</h2>
              <p className="intro">Every Formula Byte Time Sheet template is wired up with intelligent automation functions — generated, linked, and tested automatically.</p>
            </div>
            <div className="row-body">
              <div className="formula-grid">
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=SUM</span>(<span className="arg">start_time:end_time</span>)</div>
                  <div className="formula-desc">Calculates <em>total work hours</em> from clock-in and clock-out times.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=IF</span>(<span className="arg">hours&gt;40, hours-40, 0</span>)</div>
                  <div className="formula-desc">Computes <em>overtime hours</em> based on standard workweek thresholds.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=ROUND</span>(<span className="arg">rate*hours, 2</span>)</div>
                  <div className="formula-desc">Calculates <em>gross pay</em> with precise decimal rounding.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=COUNTIF</span>(<span className="arg">range, "Present"</span>)</div>
                  <div className="formula-desc">Tracks <em>attendance days</em> and employee presence.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=VLOOKUP</span>(<span className="arg">employee_id, rate_table, 2, FALSE</span>)</div>
                  <div className="formula-desc">Retrieves <em>hourly rates</em> from employee profile tables.</div>
                </div>
                <div className="formula-block">
                  <div className="formula-code"><span className="fn">=NETWORKDAYS</span>(<span className="arg">start_date, end_date</span>)</div>
                  <div className="formula-desc">Calculates <em>billable workdays</em> excluding weekends.</div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Four business types, <span className="serif-accent">one</span> template engine.</h2>
              <p className="intro">Customize the time sheet for any kind of workforce — same engine, different defaults.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">S</div>
                    <div>
                      <h4>Small Business Time Sheet Spreadsheet</h4>
                      <div className="industry-tagline">STARTUPS · RETAIL · SERVICE</div>
                    </div>
                  </div>
                  <p>Track employee attendance, work schedules, and payroll calculations. Ideal for startups and operational teams.</p>
                  <ul>
                    <li>Employee attendance</li>
                    <li>Work schedules</li>
                    <li>Payroll calculations</li>
                    <li>Overtime hours</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">C</div>
                    <div>
                      <h4>Contractor and Freelancer Time Tracker</h4>
                      <div className="industry-tagline">BILLABLE · PROJECTS · HOURLY</div>
                    </div>
                  </div>
                  <p>Manage billable hours, project tasks, and payment calculations. Useful for freelancers and contractors.</p>
                  <ul>
                    <li>Billable hours</li>
                    <li>Project tasks</li>
                    <li>Work schedules</li>
                    <li>Payment calculations</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">🏗</div>
                    <div>
                      <h4>Construction Workforce Time Sheet</h4>
                      <div className="industry-tagline">SITE · LABOR · SHIFTS</div>
                    </div>
                  </div>
                  <p>Monitor site attendance, shift scheduling, and labor hours. Designed for construction and operational management.</p>
                  <ul>
                    <li>Site attendance</li>
                    <li>Shift scheduling</li>
                    <li>Labor hours</li>
                    <li>Overtime tracking</li>
                  </ul>
                </div>
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">💻</div>
                    <div>
                      <h4>Remote Team Attendance Dashboard</h4>
                      <div className="industry-tagline">REMOTE · HYBRID · DISTRIBUTED</div>
                    </div>
                  </div>
                  <p>Track remote work schedules, productivity, and team attendance. Useful for distributed and remote teams.</p>
                  <ul>
                    <li>Remote work schedules</li>
                    <li>Productivity tracking</li>
                    <li>Task reporting</li>
                    <li>Team attendance</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* PAYROLL REPORTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Payroll Reports and Workforce Insights</h2>
              <p className="intro">Every generated time sheet system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte time sheet spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Payroll summaries</li>
                <li>Attendance reports</li>
                <li>Overtime dashboards</li>
                <li>Workforce productivity reports</li>
                <li>Employee hour summaries</li>
                <li>Scheduling insights</li>
                <li>Operational workforce dashboards</li>
                <li>Payroll analysis reports</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into workforce operations and payroll management.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Time Sheet Spreadsheet vs Manual Time Tracking</h2>
              <p className="intro">Most time tracking methods are manual and error-prone. Formula Byte generates a system built around your workforce.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual time tracking</div>
                  <h3>Spreadsheets built by hand</h3>
                  <ul>
                    <li>Manual hour entry for every employee</li>
                    <li>Time-consuming payroll calculations</li>
                    <li>Error-prone overtime formulas</li>
                    <li>Limited attendance visibility</li>
                    <li>Payroll discrepancies are common</li>
                    <li>Basic tracking, no dashboards</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>Generated, automated, accurate</h3>
                  <ul>
                    <li>Automated work hour calculations</li>
                    <li>Instant payroll summaries</li>
                    <li>Overtime accuracy guaranteed</li>
                    <li>Attendance tracking included</li>
                    <li>Scheduling insights built in</li>
                    <li>Dashboards on every generation</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-generated <span className="serif-accent">Time Sheet</span> templates.</h2>
              <p className="intro">Faster setup, fewer errors, smarter workforce decisions — every hour you'd want already tracked.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster workforce organization</h3>
                  <p>Generate complete time tracking systems instantly instead of manually building spreadsheets.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">90%</span>
                    <span className="benefit-stat-label">Less setup time</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Better payroll visibility</h3>
                  <p>Structured time sheet dashboards improve payroll clarity and financial accuracy.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">100%</span>
                    <span className="benefit-stat-label">Payroll accuracy</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Reduced payroll errors</h3>
                  <p>Automated hour calculations eliminates time-tracking mistakes and overtime discrepancies.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Zero</span>
                    <span className="benefit-stat-label">Calculation errors</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Improved workforce management</h3>
                  <p>Centralized attendance systems help teams stay aligned on schedules and availability.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Built-in</span>
                    <span className="benefit-stat-label">Scheduling tools</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Easier payroll processing</h3>
                  <p>Time sheet dashboards improve visibility into workforce attendance and labor costs.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">Real-time</span>
                    <span className="benefit-stat-label">Payroll insights</span>
                  </div>
                </div>
                <div className="benefit-card">
                  <h3>Export and share</h3>
                  <p>Download your completed time sheet as an Excel file or open directly in Google Sheets — works everywhere your team works.</p>
                  <div className="benefit-stat">
                    <span className="benefit-stat-num">2</span>
                    <span className="benefit-stat-label">Platform options</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing Time Sheet <span className="serif-accent">Tracking</span> Spreadsheets</h2>
              <p className="intro">Four habits that turn a generated time sheet spreadsheet into a real workforce management tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Track Hours Consistently</h3>
                  <p>Regular attendance tracking improves workforce visibility and payroll accuracy.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Update Employee Availability Regularly</h3>
                  <p>Consistent updates improve scheduling accuracy and team coordination.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Review Overtime Calculations</h3>
                  <p>Automated overtime monitoring reduces payroll discrepancies and labor costs.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Analyze Attendance Trends Frequently</h3>
                  <p>Regular reviews help identify:</p>
                  <ul>
                    <li>Attendance patterns</li>
                    <li>Scheduling gaps</li>
                    <li>Overtime trends</li>
                    <li>Productivity insights</li>
                  </ul>
                  <div className="capability-close">This helps businesses make smarter workforce decisions.</div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most time sheet templates are static spreadsheets. Formula Byte generates a system built around your workforce.</p>
            </div>
            <div className="row-body">
              <p>Most time sheet templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated workforce management systems tailored to your scheduling structure, payroll process, and attendance requirements.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Employee time trackers</li>
                <li>Payroll dashboards</li>
                <li>Shift scheduling systems</li>
                <li>Attendance trackers</li>
                <li>Overtime monitoring sheets</li>
                <li>Workforce reporting tools</li>
                <li>Productivity dashboards</li>
                <li>AI-powered time tracking systems</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing work hours, Formula Byte automates time sheet spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO IT'S FOR */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This Time Sheet <span className="serif-accent">Spreadsheet</span>?</h2>
              <p className="intro">This spreadsheet solution is ideal for businesses and teams managing employee hours and payroll of any kind.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Small businesses</h4></div>
                <div className="audience-cell"><h4>HR departments</h4></div>
                <div className="audience-cell"><h4>Payroll teams</h4></div>
                <div className="audience-cell"><h4>Construction companies</h4></div>
                <div className="audience-cell"><h4>Agencies</h4></div>
                <div className="audience-cell"><h4>Remote teams</h4></div>
                <div className="audience-cell"><h4>Freelancers</h4></div>
                <div className="audience-cell"><h4>Contractors</h4></div>
                <div className="audience-cell"><h4>Operations managers</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple hour tracking or advanced workforce management, Formula Byte helps automate time sheet spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating time sheet spreadsheets with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet calculate work hours automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates time sheet spreadsheets with automated hour calculations, payroll systems, and attendance tracking tools.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include overtime and payroll tracking?</summary>
                  <div className="faq-a">Yes. Time sheet templates can include overtime calculations, payroll dashboards, and wage reporting systems.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize employee schedules and shift structures?</summary>
                  <div className="faq-a">Absolutely. Employees, shifts, schedules, dashboards, and workforce structures can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte time sheet templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for payroll processing and workforce management?</summary>
                  <div className="faq-a">Yes. Businesses commonly use time sheet spreadsheets for payroll processing, employee scheduling, attendance tracking, and workforce management.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other business templates you might need.</h2>
              <p className="intro">Same engine, different business workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/purchase-order-template/" className="related-card">
                  <div className="glyph">P</div>
                  <h4>Purchase Order</h4>
                  <p>Manage vendor purchases, track orders, and streamline procurement workflows.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/invoice-template/" className="related-card">
                  <div className="glyph">I</div>
                  <h4>Invoice Template</h4>
                  <p>Professional invoices with auto-numbering, taxes, and totals.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/business-budget-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Business Budget</h4>
                  <p>Plan expenses, track budgets, and manage cash flow effectively.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/kpi-template/" className="related-card">
                  <div className="glyph">K</div>
                  <h4>KPI Dashboard</h4>
                  <p>Track key performance indicators and monitor business metrics.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI <span className="accent">Time Sheet</span> Spreadsheet?</h2>
            <p>Stop tracking work hours manually.</p>
            <p>Describe your workforce needs, and Formula Byte will generate a professional AI-powered Excel time sheet template with attendance dashboards, payroll calculation systems, scheduling management tools, overtime tracking systems, and workforce reporting workflows in seconds.</p>
            <p>Create smarter workforce management spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>
 

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}