export default function TravelItineraryTemplatePage() {
  return (
    <>
      {/* HERO */}
      <section className="hero">
        <div className="hero-inner">
          <div className="breadcrumb-line">
            <a href="/excel-templates/">Templates</a>
            <span className="sep">/</span>
            <a href="/excel-templates/?cat=personal">Personal</a>
            <span className="sep">/</span>
            <span className="current">Travel Itinerary</span>
          </div>

          <div className="eyebrow">Personal template</div>
          <h1>AI Excel Travel Itinerary Template for Trip Planning and Travel <span className="accent">Organization</span></h1>
          <p className="lede">
            Organize flights, accommodations, transportation, activities, budgets, and travel schedules with an AI-generated Excel travel itinerary template designed for smarter trip planning and travel management. Formula Byte helps travelers and businesses automate itinerary planning using intelligent spreadsheets with travel dashboards, schedule management systems, booking trackers, and expense monitoring workflows.
          </p>

          <div className="hero-specs">
            <span className="hero-spec-tag"><span className="dot"></span>Free</span>
            <span className="hero-spec"><strong>8</strong> worksheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec"><strong>10</strong> formulas built in</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">Excel <strong>&amp;</strong> Sheets</span>
            <span className="hero-spec-sep"></span>
            <span className="hero-spec">~ <strong>20 sec</strong> to generate</span>
          </div>

          <div className="hero-ctas">
            <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">
              Generate template
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12"></line>
                <polyline points="12 5 19 12 12 19"></polyline>
              </svg>
            </a>
            <a href="#preview" className="btn btn-outline btn-lg">View preview</a>
          </div>

          <div className="hero-tagline">
            <span className="hero-tagline-item">100% customizable</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">Works with Excel &amp; Google Sheets</span>
            <span className="hero-tagline-sep">•</span>
            <span className="hero-tagline-item">AI-generated in seconds</span>
          </div>
        </div>
      </section>

      {/* USE CASE PILLS */}
      <div className="use-case-grid">
        <div className="use-case-label">Generate travel itinerary spreadsheets for</div>
        <div className="use-case-pills">
          <span className="use-case-pill"><span className="dot"></span>Personal travel planning</span>
          <span className="use-case-pill"><span className="dot"></span>Business trips</span>
          <span className="use-case-pill"><span className="dot"></span>Family vacations</span>
          <span className="use-case-pill"><span className="dot"></span>Group travel coordination</span>
          <span className="use-case-pill"><span className="dot"></span>Corporate travel management</span>
          <span className="use-case-pill"><span className="dot"></span>Tour planning</span>
          <span className="use-case-pill"><span className="dot"></span>Event travel organization</span>
          <span className="use-case-pill"><span className="dot"></span>International travel schedules</span>
        </div>
      </div>

      {/* SPREADSHEET PREVIEW */}
      <div className="preview-wrap" id="preview">
        <div className="preview-window">
          {/* Window chrome */}
          <div className="preview-chrome">
            <div className="preview-dots"><span></span><span></span><span></span></div>
            <div className="preview-filename">Travel-Itinerary<span className="ext">.xlsx</span> · Generated by Formula Byte</div>
            <div className="preview-chrome-actions">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="1"></circle>
                <circle cx="19" cy="12" r="1"></circle>
                <circle cx="5" cy="12" r="1"></circle>
              </svg>
            </div>
          </div>

          {/* Formula bar */}
          <div className="preview-formula">
            <span className="preview-formula-label">D4</span>
            <span className="preview-formula-fx">ƒx</span>
            <span className="preview-formula-text">
              <span className="fn">=SUM</span>(<span className="num">Flight</span>:<span className="num">Hotel</span>+<span className="num">Activities</span>)
            </span>
          </div>

          {/* Grid */}
          <div className="preview-grid">
            {/* Column letters */}
            <div className="preview-col-header"></div>
            <div className="preview-col-header">A</div>
            <div className="preview-col-header">B</div>
            <div className="preview-col-header">C</div>
            <div className="preview-col-header">D</div>
            <div className="preview-col-header">E</div>
            <div className="preview-col-header preview-hide-mobile">F</div>

            {/* Row 1: headers */}
            <div className="preview-row-num">1</div>
            <div className="preview-cell preview-header-cell">Date</div>
            <div className="preview-cell preview-header-cell">Activity</div>
            <div className="preview-cell preview-header-cell">Location</div>
            <div className="preview-cell preview-header-cell">Cost</div>
            <div className="preview-cell preview-header-cell preview-hide-mobile">Status</div>

            {/* Row 2 */}
            <div className="preview-row-num">2</div>
            <div className="preview-cell text">June 15</div>
            <div className="preview-cell text">Flight AA1234</div>
            <div className="preview-cell text">JFK → LHR</div>
            <div className="preview-cell">$650.00</div>
            <div className="preview-cell confirmed preview-hide-mobile">Confirmed</div>

            {/* Row 3 */}
            <div className="preview-row-num">3</div>
            <div className="preview-cell text">June 15</div>
            <div className="preview-cell text">Hotel Check-in</div>
            <div className="preview-cell text">The Savoy</div>
            <div className="preview-cell">$280.00</div>
            <div className="preview-cell confirmed preview-hide-mobile">Confirmed</div>

            {/* Row 4 — selected */}
            <div className="preview-row-num">4</div>
            <div className="preview-cell text">June 16</div>
            <div className="preview-cell selected">British Museum Tour</div>
            <div className="preview-cell text">London</div>
            <div className="preview-cell selected">$45.00</div>
            <div className="preview-cell pending preview-hide-mobile">Pending</div>

            {/* Row 5 */}
            <div className="preview-row-num">5</div>
            <div className="preview-cell text">June 16</div>
            <div className="preview-cell text">Dinner Reservations</div>
            <div className="preview-cell text">Rules Restaurant</div>
            <div className="preview-cell">$120.00</div>
            <div className="preview-cell confirmed preview-hide-mobile">Confirmed</div>

            {/* Row 6 */}
            <div className="preview-row-num">6</div>
            <div className="preview-cell text">June 17</div>
            <div className="preview-cell text">Tower of London</div>
            <div className="preview-cell text">London</div>
            <div className="preview-cell">$35.00</div>
            <div className="preview-cell confirmed preview-hide-mobile">Confirmed</div>

            {/* Row 7 */}
            <div className="preview-row-num">7</div>
            <div className="preview-cell text">June 18</div>
            <div className="preview-cell text">West End Show</div>
            <div className="preview-cell text">London</div>
            <div className="preview-cell">$150.00</div>
            <div className="preview-cell confirmed preview-hide-mobile">Confirmed</div>

            {/* Row 8 — sparkline */}
            <div className="preview-row-num">8</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell text faded">…</div>
            <div className="preview-cell faded">…</div>
            <div className="preview-cell sparkline" style={{gridColumn: 'span 2'}}>
              <svg width="140" height="22" viewBox="0 0 140 22" preserveAspectRatio="none">
                <defs>
                  <linearGradient id="spark-grad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="#8171D0" stopOpacity="0.35"/>
                    <stop offset="100%" stopColor="#8171D0" stopOpacity="0"/>
                  </linearGradient>
                </defs>
                <path d="M0,18 L28,16 L56,14 L84,12 L112,10 L140,8 L140,22 L0,22 Z" fill="url(#spark-grad)"/>
                <path d="M0,18 L28,16 L56,14 L84,12 L112,10 L140,8" fill="none" stroke="#8171D0" strokeWidth="1.5"/>
              </svg>
            </div>
            <div className="preview-cell faded preview-hide-mobile">↓ spending</div>

            {/* Row 9 - last row */}
            <div className="preview-row-num">15</div>
            <div className="preview-cell text">June 22</div>
            <div className="preview-cell text">Flight BA4567</div>
            <div className="preview-cell text">LHR → JFK</div>
            <div className="preview-cell">$620.00</div>
            <div className="preview-cell confirmed preview-hide-mobile">Confirmed</div>
          </div>

          {/* Status bar */}
          <div className="preview-status">
            <div className="preview-status-item">
              <span>Trip length:</span>
              <span className="val">7 days</span>
            </div>
            <div className="preview-status-item">
              <span>Budget:</span>
              <span className="val">$3,500</span>
            </div>
            <div className="preview-status-item">
              <span>Activities:</span>
              <span className="val">12</span>
            </div>
            <div className="preview-status-item">
              <span>Total spent:</span>
              <span className="val serif">$2,340</span>
            </div>
            <div className="preview-status-spacer"></div>
            <div className="preview-status-tabs">
              <button className="preview-tab active">Dashboard</button>
              <button className="preview-tab">Itinerary</button>
              <button className="preview-tab">Budget</button>
              <button className="preview-tab">+5</button>
            </div>
          </div>
        </div>
      </div>

      {/* WHAT IS IT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The basics</div>
              <h2>What Is an Excel Travel Itinerary Template?</h2>
              <p className="intro">A structured spreadsheet used to organize trip schedules, bookings, transportation details, accommodations, activities, and travel budgets in one centralized system.</p>
            </div>
            <div className="row-body">
              <p>
                An <strong>Excel travel itinerary template</strong> is a comprehensive travel planning tool that organizes every aspect of your trip in one place. From flight details and hotel reservations to daily activities and budget tracking, everything you need is accessible and structured.
              </p>
              <p>
                A travel itinerary spreadsheet typically includes:
              </p>
              <ul className="bulleted">
                <li><strong>Flight information:</strong> Airline, flight numbers, departure times, and arrival schedules</li>
                <li><strong>Hotel reservations:</strong> Booking confirmations, check-in dates, and accommodation details</li>
                <li><strong>Transportation schedules:</strong> Trains, rental cars, airport transfers, and local transport</li>
                <li><strong>Daily travel activities:</strong> Tours, meetings, events, and sightseeing plans</li>
                <li><strong>Budget tracking:</strong> Travel spending, accommodation costs, and activity expenses</li>
                <li><strong>Travel contacts:</strong> Emergency numbers, booking references, and important contacts</li>
                <li><strong>Emergency information:</strong> Passport details, visa information, and travel documentation</li>
                <li><strong>Packing checklists:</strong> Travel preparation and essential items organization</li>
                <li><strong>Travel summaries:</strong> Trip overviews and travel coordination dashboards</li>
              </ul>
              <p>Formula Byte generates AI-powered travel spreadsheets designed for itinerary management, trip organization, and travel coordination workflows.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHY TRAVELERS NEED TRAVEL ITINERARY SYSTEMS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Why it matters</div>
              <h2>Why Travelers Need Travel Itinerary Systems</h2>
              <p className="intro">Managing travel without a structured system often creates confusion and stress.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Without a system</div>
                  <h3>Managing travel without a structured system often creates:</h3>
                  <ul>
                    <li>Missed reservations</li>
                    <li>Schedule confusion</li>
                    <li>Poor travel coordination</li>
                    <li>Budget tracking issues</li>
                    <li>Transportation delays</li>
                    <li>Disorganized travel records</li>
                    <li>Stressful trip planning</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">With an itinerary</div>
                  <h3>A properly organized travel itinerary spreadsheet helps travelers:</h3>
                  <ul>
                    <li>Improve trip organization</li>
                    <li>Track bookings effectively</li>
                    <li>Coordinate travel schedules</li>
                    <li>Monitor expenses</li>
                    <li>Simplify travel planning</li>
                    <li>Improve travel visibility</li>
                    <li>Reduce logistical issues</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* HOW IT WORKS */}
      <div className="section-wrap" id="how-it-works">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">How it works</div>
              <h2>How Travel Itinerary Planning Works.</h2>
              <p className="intro">Describe your travel needs, and Formula Byte generates the complete itinerary system — schedules, bookings, budgets, and dashboards included.</p>
            </div>
            <div className="row-body">
              <div className="steps">
                <div className="step">
                  <div className="step-num">1</div>
                  <div>
                    <h3>Describe your trip</h3>
                    <p>Travel dates, destinations, activities, budget, and transportation needs — in plain English or a quick form.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">2</div>
                  <div>
                    <h3>AI builds the itinerary</h3>
                    <p>Flight schedules, hotel reservations, activity planning, and budget tracking are organized automatically.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">3</div>
                  <div>
                    <h3>Dashboards generate themselves</h3>
                    <p>Travel schedules, booking dashboards, expense tracking, and trip summaries appear on dedicated sheets.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-num">4</div>
                  <div>
                    <h3>Track and adjust</h3>
                    <p>Update bookings, monitor expenses, and modify activities — your entire itinerary recalculates automatically.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* CREATE AN AI TRAVEL ITINERARY SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Generate</div>
              <h2>Create an AI Travel Itinerary Spreadsheet with Formula Byte</h2>
              <p className="intro">Describe the travel planning spreadsheet you need, and Formula Byte automatically generates a professional Excel travel itinerary template.</p>
            </div>
            <div className="row-body">
              <p>Describe the travel planning spreadsheet you need, and Formula Byte automatically generates a professional Excel travel itinerary template with:</p>
              <ul className="bulleted">
                <li>Flight tracking</li>
                <li>Hotel booking organization</li>
                <li>Transportation schedules</li>
                <li>Activity planning</li>
                <li>Budget monitoring</li>
                <li>Travel checklists</li>
                <li>Automated spreadsheet formulas</li>
                <li>Travel dashboards</li>
                <li>Trip coordination systems</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing travel details, Formula Byte creates AI-powered itinerary management systems tailored to your travel workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* CORE FEATURES */}
      <div className="section-wrap" id="features">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Core features</div>
              <h2>Core Features of Formula Byte's AI Travel Itinerary <span className="serif-accent">Spreadsheet</span>.</h2>
              <p className="intro">Four pillars of travel itinerary management — automatic, organized, and built to support stress-free trip planning.</p>
            </div>
            <div className="row-body">
              <div className="feature-quad">
                <div className="feature-tile">
                  <div className="feature-tile-icon">✈</div>
                  <h3>Flight and Transportation Tracking</h3>
                  <p>Track flight numbers, departure times, arrival schedules, airport information, train schedules, rental car bookings, and transportation details. The spreadsheet automatically organizes travel schedules into structured itinerary layouts.</p>
                  <ul>
                    <li>Flight numbers & times</li>
                    <li>Train schedules</li>
                    <li>Rental car bookings</li>
                    <li>Transportation details</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">🏨</div>
                  <h3>Accommodation and Reservation Management</h3>
                  <p>Monitor hotel bookings, check-in dates, check-out schedules, reservation numbers, accommodation addresses, contact information, and booking confirmations. This improves travel visibility and reservation organization.</p>
                  <ul>
                    <li>Hotel bookings</li>
                    <li>Check-in/out dates</li>
                    <li>Reservation numbers</li>
                    <li>Contact information</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">📅</div>
                  <h3>Activity and Daily Schedule Planning</h3>
                  <p>Formula Byte travel itinerary spreadsheets can include daily travel schedules, activity planning, event coordination, restaurant reservations, meeting schedules, tour bookings, and travel timelines. Structured scheduling improves trip organization and travel efficiency.</p>
                  <ul>
                    <li>Daily schedules</li>
                    <li>Activity planning</li>
                    <li>Event coordination</li>
                    <li>Tour bookings</li>
                  </ul>
                </div>
                <div className="feature-tile">
                  <div className="feature-tile-icon">💰</div>
                  <h3>Travel Budget and Expense Tracking</h3>
                  <p>Track transportation costs, hotel expenses, food budgets, activity expenses, shopping costs, currency exchange, and travel spending summaries. This helps travelers improve budgeting and expense management during trips.</p>
                  <ul>
                    <li>Transportation costs</li>
                    <li>Hotel expenses</li>
                    <li>Food budgets</li>
                    <li>Currency tracking</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* AI TRAVEL PLANNING AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">AI automation</div>
              <h2>AI Travel Planning Automation</h2>
              <p className="intro">Skip the manual formatting. The AI understands travel planning instructions from natural language prompts.</p>
            </div>
            <div className="row-body">
              <p>Traditional travel itinerary spreadsheets require manual formatting and repetitive organization.</p>
              <p>Formula Byte uses AI spreadsheet automation to:</p>
              <ul className="bulleted">
                <li>Structure travel schedules</li>
                <li>Generate booking dashboards</li>
                <li>Organize transportation tracking</li>
                <li>Create travel planning systems</li>
                <li>Build budget monitoring dashboards</li>
                <li>Generate trip summaries</li>
                <li>Apply spreadsheet formatting</li>
                <li>Automate itinerary workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>The AI understands travel planning instructions from natural language prompts.</p>

              <div className="example-prompts-block">
                <span className="list-sublabel">Example prompts</span>
                <div className="example-prompts-list">
                  <button className="chip">"Create a Europe travel itinerary spreadsheet"</button>
                  <button className="chip">"Build a business trip planning dashboard"</button>
                  <button className="chip">"Generate a family vacation organizer"</button>
                  <button className="chip">"Create a travel budget and booking tracker"</button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WORKSHEETS INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">What's inside</div>
              <h2>Travel Itinerary Worksheets <span className="serif-accent">Included</span></h2>
              <p className="intro">A complete travel itinerary spreadsheet with 8 worksheets — each generated, formatted, and wired up automatically.</p>
            </div>
            <div className="row-body">
              <div className="spec-table">
                <div className="spec-row spec-head">
                  <div className="spec-head-cell">#</div>
                  <div className="spec-head-cell">Worksheet</div>
                  <div className="spec-head-cell">Purpose</div>
                </div>
                <div className="spec-row">
                  <span className="spec-num">01</span>
                  <span className="spec-name">Travel Dashboard</span>
                  <span className="spec-purpose">Visualizes trip schedules and bookings</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">02</span>
                  <span className="spec-name">Flight Tracking Sheet</span>
                  <span className="spec-purpose">Monitors transportation schedules</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">03</span>
                  <span className="spec-name">Hotel Reservation Tracker</span>
                  <span className="spec-purpose">Organizes accommodations</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">04</span>
                  <span className="spec-name">Activity Planning Dashboard</span>
                  <span className="spec-purpose">Tracks daily trip activities</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">05</span>
                  <span className="spec-name">Travel Budget Sheet</span>
                  <span className="spec-purpose">Monitors travel expenses</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">06</span>
                  <span className="spec-name">Packing Checklist Tracker</span>
                  <span className="spec-purpose">Organizes travel preparation</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">07</span>
                  <span className="spec-name">Emergency Contact Sheet</span>
                  <span className="spec-purpose">Stores travel safety information</span>
                </div>
                <div className="spec-row">
                  <span className="spec-num">08</span>
                  <span className="spec-name">Trip Summary Dashboard</span>
                  <span className="spec-purpose">Generates travel insights</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* TRAVEL PLANNING CATEGORIES INCLUDED */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Data included</div>
              <h2>Travel Planning <span className="serif-accent">Categories</span> Included</h2>
              <p className="intro">Every travel planning category you need — pre-built, organized, and ready for instant trip management.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte travel itinerary spreadsheets include comprehensive workflow management categories:</p>
              <ul className="bulleted">
                <li><strong>Transportation and schedule management:</strong> Flights, train schedules, rental cars, airport transfers, transportation bookings, daily travel timelines</li>
                <li><strong>Accommodation and reservation tracking:</strong> Hotel reservations, Airbnb bookings, check-in schedules, booking confirmations, accommodation expenses</li>
                <li><strong>Budget and expense monitoring:</strong> Travel spending, accommodation costs, transportation expenses, food budgets, activity costs, currency tracking</li>
              </ul>
              <p style={{marginTop: '18px'}}>These categories provide a complete foundation for travel organization and trip planning workflow.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BUILT-IN EXCEL FORMULAS AND TRAVEL AUTOMATION */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Built-in automation</div>
              <h2>Built-In <span className="serif-accent">Travel Itinerary</span> Formulas</h2>
              <p className="intro">No manual calculations. All formulas are wired, tested, and ready to use.</p>
            </div>
            <div className="row-body">
              <p>Every travel itinerary spreadsheet includes built-in formulas for automatic travel calculations:</p>
              <ul className="bulleted">
                <li><strong>Trip duration:</strong> =Return Date - Departure Date</li>
                <li><strong>Total budget:</strong> =SUM(Flight + Hotel + Activities + Food)</li>
                <li><strong>Daily budget:</strong> =Total Budget / Trip Duration</li>
                <li><strong>Budget remaining:</strong> =Total Budget - SUM(Actual Spending)</li>
                <li><strong>Currency conversion:</strong> =Amount * Exchange Rate</li>
                <li><strong>Days until trip:</strong> =Departure Date - TODAY()</li>
                <li><strong>Booking status:</strong> =IF(Confirmation Number"", "Confirmed", "Pending")</li>
                <li><strong>Packing progress:</strong> =COUNTIF(Packed, "Yes") / Total Items * 100%</li>
              </ul>
              <p style={{marginTop: '18px'}}>These formulas automate complex travel calculations, reducing manual effort and improving planning accuracy.</p>
            </div>
          </div>
        </section>
      </div>

      {/* USE CASES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Use cases</div>
              <h2>Travel Itinerary Templates by <span className="serif-accent">Use Case</span></h2>
              <p className="intro">Customize the travel itinerary for any kind of trip — same structure, different focus.</p>
            </div>
            <div className="row-body">
              <div className="industry-grid">
                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">PV</div>
                    <div>
                      <h4>Personal Vacation Itinerary Spreadsheet</h4>
                      <div className="industry-tagline">PERSONAL · VACATION · LEISURE</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Flights</li>
                    <li>Hotels</li>
                    <li>Activities</li>
                    <li>Daily schedules</li>
                    <li>Travel expenses</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Ideal for personal travel and vacation planning.</p>
                </div>

                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">BT</div>
                    <div>
                      <h4>Business Travel Planning Template</h4>
                      <div className="industry-tagline">BUSINESS · CORPORATE · MEETINGS</div>
                    </div>
                  </div>
                  <p>Manage:</p>
                  <ul>
                    <li>Meeting schedules</li>
                    <li>Corporate travel</li>
                    <li>Hotel bookings</li>
                    <li>Expense tracking</li>
                    <li>Transportation planning</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for professionals and corporate travel workflows.</p>
                </div>

                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">FV</div>
                    <div>
                      <h4>Family Vacation Organizer</h4>
                      <div className="industry-tagline">FAMILY · GROUP · COORDINATION</div>
                    </div>
                  </div>
                  <p>Track:</p>
                  <ul>
                    <li>Family schedules</li>
                    <li>Accommodation planning</li>
                    <li>Group transportation</li>
                    <li>Travel budgets</li>
                    <li>Daily activities</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Designed for family travel coordination.</p>
                </div>

                <div className="industry-card">
                  <div className="industry-card-head">
                    <div className="industry-glyph">IT</div>
                    <div>
                      <h4>International Travel Dashboard</h4>
                      <div className="industry-tagline">INTERNATIONAL · GLOBAL · PASSPORTS</div>
                    </div>
                  </div>
                  <p>Monitor:</p>
                  <ul>
                    <li>Passport details</li>
                    <li>Visa information</li>
                    <li>International flights</li>
                    <li>Currency exchange</li>
                    <li>Travel documentation</li>
                  </ul>
                  <p style={{marginTop: '12px', fontSize: '14px', fontStyle: 'italic'}}>Useful for global travel and international trip planning.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* TRAVEL REPORTS AND PLANNING INSIGHTS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">Reporting</div>
              <h2>Travel Reports and Planning <span className="serif-accent">Insights</span></h2>
              <p className="intro">Every generated travel itinerary system produces dashboard-grade reports — no manual analysis required.</p>
            </div>
            <div className="row-body">
              <p>Formula Byte travel itinerary spreadsheets can generate:</p>
              <ul className="bulleted">
                <li>Travel summaries</li>
                <li>Expense reports</li>
                <li>Booking dashboards</li>
                <li>Transportation tracking insights</li>
                <li>Daily planning summaries</li>
                <li>Budget analysis reports</li>
                <li>Trip coordination dashboards</li>
                <li>Travel organization reports</li>
              </ul>
              <p style={{marginTop: '18px'}}>These reports improve visibility into travel operations and itinerary coordination.</p>
            </div>
          </div>
        </section>
      </div>

      {/* COMPARE */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Excel Travel Itinerary Spreadsheet vs. <span className="serif-accent">Manual</span> Trip Planning</h2>
              <p className="intro">Seven dimensions where AI-powered travel itinerary spreadsheets outperform manual task management.</p>
            </div>
            <div className="row-body">
              <div className="compare">
                <div className="compare-col">
                  <div className="compare-label">Manual Trip Planning</div>
                  <h3>Manual trip organization</h3>
                  <ul>
                    <li>Often inconsistent task records</li>
                    <li>Limited deadline monitoring</li>
                    <li>Manual productivity tracking</li>
                    <li>Difficult to manage workflow visibility</li>
                    <li>Time-consuming spreadsheet setup</li>
                    <li>Less efficient progress monitoring</li>
                    <li>Basic productivity reporting</li>
                  </ul>
                </div>
                <div className="compare-col">
                  <div className="compare-label">Formula Byte AI</div>
                  <h3>AI-generated spreadsheets</h3>
                  <ul>
                    <li>Structured task organization</li>
                    <li>Dashboard-based deadline monitoring</li>
                    <li>Automated productivity tracking</li>
                    <li>Organized workflow visibility</li>
                    <li>Fast spreadsheet setup</li>
                    <li>Centralized progress monitoring</li>
                    <li>Automated productivity reporting</li>
                  </ul>
                </div>
              </div>
              <p style={{marginTop: '18px'}}>AI-generated spreadsheets simplify travel planning and itinerary management.</p>
            </div>
          </div>
        </section>
      </div>

      {/* BENEFITS */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Why use it</div>
              <h2>Benefits of AI-Generated <span className="serif-accent">Travel Itinerary</span> Templates</h2>
              <p className="intro">Faster setup, fewer errors, smarter travel decisions — every trip organized automatically.</p>
            </div>
            <div className="row-body">
              <div className="benefit-grid">
                <div className="benefit-card">
                  <h3>Faster Trip Organization</h3>
                  <p>Generate complete travel planning systems instantly without manually building spreadsheets.</p>
                </div>
                <div className="benefit-card">
                  <h3>Better Travel Visibility</h3>
                  <p>Structured dashboards improve booking management and travel coordination.</p>
                </div>
                <div className="benefit-card">
                  <h3>Reduced Travel Confusion</h3>
                  <p>Automated organization reduces scheduling mistakes and booking inconsistencies.</p>
                </div>
                <div className="benefit-card">
                  <h3>Improved Budget Management</h3>
                  <p>Travel dashboards help users monitor spending and optimize travel expenses.</p>
                </div>
                <div className="benefit-card">
                  <h3>Easier Trip Coordination</h3>
                  <p>Centralized travel systems improve itinerary planning and operational organization.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* BEST PRACTICES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Best practices</div>
              <h2>Best Practices for Managing Travel Itinerary <span className="serif-accent">Spreadsheets</span></h2>
              <p className="intro">Four habits that turn a generated travel itinerary spreadsheet into a real trip planning tool.</p>
            </div>
            <div className="row-body">
              <div className="capability-grid">
                <div className="capability">
                  <span className="cap-num">01 / HABIT</span>
                  <h3>Update Travel Information Regularly</h3>
                  <p>Consistent updates improve itinerary accuracy and travel visibility.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">02 / HABIT</span>
                  <h3>Store Booking Confirmations Clearly</h3>
                  <p>Structured reservation tracking improves travel organization and reduces confusion.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">03 / HABIT</span>
                  <h3>Monitor Travel Budgets Closely</h3>
                  <p>Tracking expenses helps travelers manage costs and avoid budget overruns.</p>
                </div>
                <div className="capability">
                  <span className="cap-num">04 / HABIT</span>
                  <h3>Review Travel Schedules Frequently</h3>
                  <p>Regular reviews help identify schedule conflicts, transportation delays, missing reservations, budget issues, and travel coordination improvements.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* WHY FORMULA BYTE IS DIFFERENT */}
      <div className="section-wrap">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">The difference</div>
              <h2>Why Formula Byte <span className="serif-accent">Is Different</span></h2>
              <p className="intro">Most travel itinerary templates are static spreadsheets. Formula Byte generates a system built around your trip.</p>
            </div>
            <div className="row-body">
              <p>Most travel itinerary templates are static spreadsheets with limited flexibility.</p>
              <p>Formula Byte creates AI-generated travel management systems tailored to your travel schedule, trip structure, and itinerary planning requirements.</p>
              <p style={{marginTop: '18px'}}>You can generate:</p>
              <ul className="bulleted">
                <li>Travel dashboards</li>
                <li>Booking management systems</li>
                <li>Transportation trackers</li>
                <li>Budget monitoring tools</li>
                <li>Activity planning dashboards</li>
                <li>Reservation management sheets</li>
                <li>Trip coordination reports</li>
                <li>AI-powered itinerary workflows</li>
              </ul>
              <p style={{marginTop: '18px'}}>Instead of manually organizing travel plans, Formula Byte automates travel itinerary spreadsheet creation using AI.</p>
            </div>
          </div>
        </section>
      </div>

      {/* WHO SHOULD USE THIS TRAVEL ITINERARY SPREADSHEET */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Who it's for</div>
              <h2>Who Should Use This Travel Itinerary <span className="serif-accent">Spreadsheet</span>?</h2>
              <p className="intro">This spreadsheet solution is ideal for travelers and businesses managing trips of any kind.</p>
            </div>
            <div className="row-body">
              <div className="audience-grid">
                <div className="audience-cell"><h4>Travelers</h4></div>
                <div className="audience-cell"><h4>Families</h4></div>
                <div className="audience-cell"><h4>Business professionals</h4></div>
                <div className="audience-cell"><h4>Travel planners</h4></div>
                <div className="audience-cell"><h4>Tour coordinators</h4></div>
                <div className="audience-cell"><h4>Remote workers</h4></div>
                <div className="audience-cell"><h4>Event organizers</h4></div>
                <div className="audience-cell"><h4>Corporate teams</h4></div>
                <div className="audience-cell"><h4>Frequent travelers</h4></div>
              </div>
              <div className="audience-footer">Whether you need simple vacation planning or advanced travel coordination, Formula Byte helps automate travel itinerary spreadsheet creation with AI.</div>
            </div>
          </div>
        </section>
      </div>

      {/* FAQ */}
      <div className="section-wrap" id="faq">
        <section className="card">
          <div className="row">
            <div className="row-header">
              <div className="eyebrow">FAQ</div>
              <h2>Frequently Asked Questions</h2>
              <p className="intro">Common questions about generating travel itinerary spreadsheets with Formula Byte.</p>
            </div>
            <div className="row-body">
              <div className="faq-list">
                <details className="faq-item" open>
                  <summary className="faq-q">Can this spreadsheet organize travel bookings automatically?</summary>
                  <div className="faq-a">Yes. Formula Byte generates travel itinerary spreadsheets with booking management, transportation tracking, and travel planning systems.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does the template include travel budgeting and scheduling?</summary>
                  <div className="faq-a">Yes. Travel itinerary templates can include budget dashboards, transportation schedules, hotel tracking, and daily activity planning systems.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Can I customize travel categories and itinerary layouts?</summary>
                  <div className="faq-a">Absolutely. Flights, accommodations, schedules, dashboards, budgets, and travel workflows can all be customized.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Does this spreadsheet work in Google Sheets?</summary>
                  <div className="faq-a">Yes. Formula Byte travel itinerary templates work with both Microsoft Excel and Google Sheets.</div>
                </details>
                <details className="faq-item">
                  <summary className="faq-q">Is this suitable for personal and business travel planning?</summary>
                  <div className="faq-a">Yes. Travelers commonly use itinerary spreadsheets for vacation planning, corporate travel, budgeting, transportation management, and trip coordination.</div>
                </details>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* RELATED TEMPLATES */}
      <div className="section-wrap">
        <section className="card">
          <div className="row-stacked">
            <div className="row-header">
              <div className="eyebrow">Related templates</div>
              <h2>Other personal templates you might need.</h2>
              <p className="intro">Same engine, different personal workflows.</p>
            </div>
            <div className="row-body">
              <div className="related-grid">
                <a href="/excel-templates/calendar-template-2026/" className="related-card">
                  <div className="glyph">C</div>
                  <h4>Calendar 2026 Template</h4>
                  <p>Yearly planning with holidays and events.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/daily-schedule-template/" className="related-card">
                  <div className="glyph">D</div>
                  <h4>Daily Schedule Template</h4>
                  <p>Plan your day with time blocks.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/to-do-list-template/" className="related-card">
                  <div className="glyph">T</div>
                  <h4>To Do List Template</h4>
                  <p>Track tasks and priorities.</p>
                  <span className="link">View template →</span>
                </a>
                <a href="/excel-templates/budget-template/" className="related-card">
                  <div className="glyph">B</div>
                  <h4>Budget Template</h4>
                  <p>Personal finance and expense tracking.</p>
                  <span className="link">View template →</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* FINAL CTA */}
      <div className="final-cta-wrap">
        <section className="final-cta">
          <div className="final-cta-inner">
            <h2>Ready to Build Your AI Travel <span className="accent">Itinerary</span> Spreadsheet?</h2>
            <p>Stop organizing travel plans manually.</p>
            <p>Describe your travel workflow, and Formula Byte will generate a professional AI-powered Excel travel itinerary template with booking dashboards, transportation tracking systems, travel budgeting tools, activity planning workflows, and trip coordination reports in seconds.</p>
            <p>Create smarter travel planning spreadsheets with AI today.</p>
            <div className="btn-row">
              <a href="https://dashboard.formulabyte.com/" className="btn btn-primary btn-lg">Generate template →</a>
              <a href="/excel-templates/" className="btn btn-outline btn-lg">Browse all templates</a>
            </div>
          </div>
        </section>
      </div>

      {/* Interactive scripts */}
      <script dangerouslySetInnerHTML={{
        __html: `
          // Chip suggestions
          (function() {
            const chips = document.querySelectorAll('.hero-suggest .chip');
            chips.forEach(chip => {
              chip.addEventListener('click', () => {
                const textarea = document.querySelector('.prompt-textarea');
                if (textarea) {
                  textarea.value = chip.textContent;
                  textarea.focus();
                }
              });
            });
          })();
        `
      }} />
    </>
  );
}
